### ISSUE TITLE
add [toc] tag in .md docs

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#103]

**Comment by AndreWin** [comment]
It would be nice to add `[toc]` tag in .md docs. This TOC will not have any page numbers.
If user click on any line in TOC, he should be moved to corresponding header.
If .md doc doesn't have any header, TOC should be empty.
TOC shouldn't have own header (like "TOC") because of internationalization problem.
Or, it can be realized like so: 
```
[toc Оглавление]
```
P.S.: I really don't know what to write else...

**Comment by danyill** [comment]
Perhaps something similar to [mediawiki](https://www.mediawiki.org/wiki/Manual:Table_of_contents)? 
- automatic numbering
- stripping of any inline html
- customisable depth
- ability to choose location within the worksheet

**Comment by williamstein** [comment]
I don't understand what this is.  However, we do have table of contents that are autogenerated by markdown headers now.
