### ISSUE TITLE
Per-assignment grading snippets

### ISSUE THREAD

**Issue by rbeezer** [sagemathinc/cocalc#110]
When you grade a pile of Sage worksheets, you often make the same comment to many students.  (Being able to write in Markdown or HTML with LaTeX is real nice.) It would be nice to be able to save a frequent response as a sort of snippet that could be pasted into a new cell quickly and easily.

Right now, I have

``` html
%html
<div style="color:red; font-size:141%">

</div>
```

in my clipboard buffer, but I'd want to also have frequently used content there also - on a per-assignment basis.

**Comment by williamstein** [comment]
What's a good modern implementation of grading support these days?  Is Canvas or something else the "gold standard"?  I'm sure there's much much more than just snippets.

It might also be fun and useful for an instructor to be able to ask "Please run chatgpt with the following prompt on all assignments and make that output available to me."

**Comment by novoselt** [comment]
I think the original request can be solved by fancy clipboard apps or no so fancy text file opened in another window. My guess is that a good implementation is tricky to get right - so that it is intuitive and easily discoverable. AI grading can be a different issue with its own concerns about price and privacy.
