### ISSUE TITLE
terminal copy/paste shows control chars

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1250]
when opening up that terminal copy/paste dialog, I would expect a "clean" text representation of the content. for me here, in tmux (which is probably causing this), it's full of ascii-coded escape characters. maybe there is a way to filter them.

**Comment by williamstein** [comment]
This is nothing *a priori* to do with tmux, but with xterm.  They are xterm control codes, e.g., for colored prompts, etc.  The fix may be to just use term.js again to render that entire history as one single long terminal (hence as html still), but in a friendlier copy-able format, since it's all on one page.

**Comment by williamstein** [comment]
Obviously, trying to find a way to just make select/copy actually work in the normal way (so no popup dialog at all) would be way better.  This is definitely possible, since codemirror does solve exactly this problem.

**Comment by williamstein** [comment]
I got rid of that copy/paste dialog completely since it's now possible to pretty easily select all, and the xterm.js copy paste is much better anyways.  It even deals with wrapped lines!
