### ISSUE TITLE
implement: background terminal activity indicator

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1301]
before the latest terminal update, the terminal icon turned into orange to indicate activity. i.e. I always saw it when webpack's watcher was producing new output ... that's gone now.

**Comment by williamstein** [comment]
Re-opening and reverting my "fix".  It was the right fix, but for some strange reason now setting off the indicator completely breaks copy/paste.  This is very strange, but loosing copy/paste is obviously way worse.

**Comment by williamstein** [comment]
Changing this to enhancement, since it's been year(s) since we had this, and nobody expects it to  be there (so not a bug).    I don't even know if we have an activity indicator anymore after the react rewrite; I think it never got ported over. It would be VERY nice to have an activity indicator for any file/tab, not just terminals.
