### ISSUE TITLE
md editor: inconsistent undo after buttonbar action

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1323]
1. type in some text
2. select it
3. click "centered"
4. click the undo button

result: text is gone, redo reveals it. 

maybe there are two undos happening? it doesn't happen for bold.

**Comment by DrXyzzy** [comment]
I was able to reproduce the problem by pasting text into an .md file, doing center, and undoing. It does look as if there are two undo operations happening. If I make a change before centering, then undo the centering, the preceding change is undone as well.

Here are two situations when the bug does not happen:
1. Add a line anywhere with the single word `test`, center, and undo. It works.
1. Paste the text below into an empty .md file. Select the single word `50th`, center and undo. It works. If you trigger the bug by centering another word and undoing, the bug now happens with `50th`.

Sample text:
```
Planet Earth is quite heavy. It weighs 6,000,000,000,000,000,000,000,000 kilograms, give or take. In astronomical terms, though, Earth is a featherweight.

Imagine taking half-a-million Earths, and squishing them together into a space about 10 kilometres across. Such compact and absurdly heavy objects do exist out there in space.

Neutron stars are the smallest, densest objects known to science. Neutron stars are the collapsed cores of stars that have exploded in violent supernovae. They are among the most extreme, fascinating, and potentially useful astronomical objects out there – and it is believed there are 100 million of them in our galaxy alone.

To commemorate the 50th year of the discovery of neutron stars, here is some light reading (and some viewing, thanks to neutron star expert Victoria Kaspi) about these preposterously heavy things.
```
source: https://insidetheperimeter.ca/neutron-stars-are-awesome-and-here-are-lots-of-reasons-why/

**Comment by williamstein** [comment]
This is still a bug.   I can reproduce it using the steps @DrXyzzy gives above.  I don't know how "serious" it is, or what part of cocalc is causing it, but I better find out, since having undo not work 100% correctly could be really confusing.   Hopefully this is some really weird edge case caused only by text edits coming from those format buttons at the top (perhaps forgetting to fill in some field that identifies the user)... but it would be a good idea to fix this ASAP in order to make sure it isn't some more general bug at the sync level.    

Regarding the above steps to reproduce, the format operation is a single change just as it should be (according to TimeTravel), but the undo operation goes to a very wrong point in time.

**Comment by williamstein** [comment]
Keeping notes here....

Steps to reproduce:

1. Make a blank md file
2. Type `a b c`
3. Select `b` and click the center button at the top.
4. Click the undo button.
5. Select `c` and click the center button at the top.
6. Click the undo button.
7. BOOM - the document is empty!

It's important to **wait long enough for each revision to get commited** (commits are debounced), so open up a Timetravel panel, and as you do each step that makes a change, make sure to wait until the number of revisions goes up by one.  

- You can do the above with bold via ctrl+b on the keyboard instead of formatting.
- You can even quickly type two asterisks around the letter instead of using the formatting button or keyboard shortcut, so this has nothing to do with format buttons or keyboard shortcuts... hence is very serious... or maybe just an undesirable side effect of our sync algorithm being "best effort application of patches".  If it is such a side effect, I will change how undo is defined and implemented.
- You can use underscore instead of two stars (italics instead of bold).
- If multiple people are viewing the document at once then at least they do see the exact same thing -  eventual consistency of the editing sessions (the most important thing of all) is at least fine.
- Here's what the actual history of editing looks like with italics:
![image](https://user-images.githubusercontent.com/1276278/72762685-6510ff00-3b95-11ea-9242-2578d17f6d58.png)
Fortunately, this strongly suggests that there is nothing weird or wrong involving the sync algorithm or patching, but maybe there is something wrong with the undo implementation itself. I'm amazed that this bug has persisted through like 3 re-implementations of this code.  I wonder what it is.  Soon we will find out.  Maybe some index is off by one in some case.
-

**Comment by williamstein** [comment]
I figured this all out.   It's *NOT* a bug in the realtime sync implementation.  Instead, it's a mistake in some client code that uses it.  The API specifies that you have to exit undo mode.  This happens automatically for all the structured object type editors (e.g., Jupyter, tasks, etc.).  But for the pure text editors, as an optimization (and because syncing with codemirror is quite tricky) what happens is:

1. You enter undo mode when undoing bolding of b.
2. You then make c bold and this does NOT exit undo mode, because it's not typing -- it's using a format action.  That's the bug. This should also exit undo mode and it's easy to fix by just making it so only undo/redo changes don't exit undo mode (but everything else does).

That's it.  Nothing else is impacted... except Sage worksheets when you use the menus at the top to insert code snippets -- they also don't exit undo mode, but should.  I'll look into that next.
