### ISSUE TITLE
opening project settings directly (e.g., by clicking on collab names in project listings) should NOT start the project running

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1411]
To reproduce.

1. stop a project in project settings
2. refresh browser
3. project will start again.

Why?  I think because of some new directly listing request code that I think @johnjeng recently added when refactoring project_store....

Expected behavior: 3 shouldn't happen.

**Comment by DrXyzzy** [comment]
Opening a stopped project from the projects list and waiting at the Files page (without clicking anything) also causes the project to start after file listing is fetched. Is that a bug?

**Comment by haraldschilly** [comment]
no, I would say that opening the files listing should start it

**Comment by williamstein** [comment]
Definitely still broken after the cocalc rewrite.  Under the hood, I think a directory listing is getting requested too aggressively.

**Comment by slel** [comment]
To go one step further:

### Allow to start and stop projects from the projects list view

It would be nice if, from the projects list view at
https://cocalc.com/projects?session=default
clicking on a project status in the last column of the table
view of the list of projects would pop up a menu allowing to

  - start the project if it is stopped
  - stop it or restart it if it is running
  - visit the project's settings page

Currently, clicking on the status (which can be
"starting", "running", "stopping", "stopped")
takes the user to the settings page; if the
project is running, one can stop it there;
if the project is stopped, this visit to the
settings page starts it (this issue is about
changing that last fact).

One could also imagine a way to select multiple
projects, or all projects, or all projects that
match a search query, and to start or stop them all.
