### ISSUE TITLE
peer-grading: editing grading guidelines does not save state

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#1546]
When editing the peer-grading guidelines for a particular assignment, navigating to another file and then back to the course file seems to have the same effect as clicking "cancel", which has caused me to lose progress on several occasions (when I was trying to inspect another file while composing the guidelines). What would be better is if upon return, the editor returned to the same state as it was left in (neither saved nor cancelled), at least as long as nothing drastic has happened.

**Comment by DrXyzzy** [comment]
To replicate:
1. Open a .course file.
1. In the course tab, select an assignment and open the assignment.
1. Click the checkbox for peer grading.
1. Click `Edit` to the right of Grading guidelines paragraph.
1. Enter some text into the grading guidelines text box but do not click Save.
1. Open some other tab in SMC, then return to the course tab.
1. Peer grading dialog is now closed. If you re-open it and re-select `Edit` to right of guidelines, the entered text is gone.

**Comment by williamstein** [comment]
@johnjeng  I'm re-opening this.  It turns out https://github.com/sagemathinc/cocalc/pull/2065 surprisingly **fails to fix this**.  We were both evidently very sloppy in our testing.

1. Open any markdown editor (e.g., the course description) and edit in a course.  Or open peer grading for an assignment.
2. Change to another tab **in the course** then back, and things are fine.
3. Change to the files tab (of the project) then back, and things are **NOT FINE** -- all state is reset.

**Comment by johnjeng** [comment]
Oh, whoops. It needs to be enabled. I only applied it to assignment notes and forgot about the other markdown inputs.
