### ISSUE TITLE
public view of file listing should allow for sorting in various orders

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1564]
Kiran Kedlaya just showed me that right now there is no way to sort by anything except "last modified" when using the public view of a directory. 

The main point of this ticket is to serve as a reminder that when we finally properly implement sorting of the file listing by filename/size/timestamp/type (via columns) that should work both for public view and for normal use as a logged in collaborator.

**Comment by williamstein** [comment]
(and obviously be persistent)

**Comment by haraldschilly** [comment]
I'm closing this @johnjeng, because your additions for sorting file listings are also on the public file listing. feel free to reopen it or create a follow up ticket if you think there is something left to do. (e.g. william mentions persistence for public views? I wouldn't really bother with persistence in public listings ... i.e. my interpretation this would mean to encode the state as a query parameter, e.g. `?sort=+name` or `...-name` or whatever.)
