### ISSUE TITLE
discard NaN in 3d plot

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1598]
when plotting a 3d matrix like `[[ 1,2,3], [4, NaN, 5], ...]` then discard those points where an NaN appears.

**Comment by williamstein** [comment]
This works:
```
import numpy
a = numpy.ndarray(dtype='float', shape=(3,3))
list_plot(a)
```
But then this doesn't:
```
a[0] = NaN
list_plot(a)
```
with
<img width="1210" alt="screen shot 2017-01-26 at 11 39 28 am" src="https://cloud.githubusercontent.com/assets/1276278/22347243/1f4c3afe-e3bc-11e6-8082-c1489914f760.png">

Also, this is a bug, since the error message "error downloading /blobs/..." is incorrect.

**Comment by williamstein** [comment]
If anything, this would be a question for the SageMath issue tracker, not cocalc.
