### ISSUE TITLE
provide a way for instructors to easily see a description of how "engaged" their students are in a course

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1620]
This must at least answer the following question (of Kiran Kedlay):
> Did you have an automated way to verify class participation in your class? My TAs are trying to do it by hand and finding it quite time-consuming, but this checking of timestamps ought to be something scriptable.

**Comment by kedlaya** [comment]
In our case, the first piece of data we need to collect is, for all students in the course, the number of edits made in a particular handout during a particular period of time.

**Comment by novoselt** [comment]
Zoom had a way to track that the window is focused during the call. They removed it because of privacy issues. This seems to me like a similar situation - providing an easy way of surveillance over students without their consent. And adding such a consent may also be tricky, especially if it must be with an opt out because the number of edits or anything else is not required to complete the course. 

Anyway - I am strongly against adding it because of legal concerns, regardless of implementation efforts.
