### ISSUE TITLE
Give all students a dummy grade

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#1630]
My class uses SMC homework collection and peer grading, but not the grade distribution (for liability reasons we are required to distribute grades using a separate system controlled by the university). It would be very helpful to have a one-click method to populate all of the students' grade boxes with a single nonempty string (like "n/a"), rather than having to do it manually.

**Comment by haraldschilly** [comment]
I found this issue after searching for problems with grading. I think the actual solution here is to allow redistribution of all solutions despite not entering anything into the grades column. I.e. the rightmost "return" button should offer to return to everyone even without grades.

**Comment by kedlaya** [comment]
Yes, this would address the underlying issue more directly. 

It should be pointed out that the "liability issue" that I mentioned is really the US law FERPA, and so is quite serious; I don't know what would be required to get CoCalc to be certified as FERPA-compliant in some meaningful way.

**Comment by haraldschilly** [comment]
this is solved by being able to skip grading (checkbox at the top of the grading column)

**Comment by ulfarsson** [comment]
Great!

-- 
Best regards / Bestu kveðjur
Henning Ulfarsson
Assistant Professor, RU

On 4 December 2017 at 17:53:14, Harald Schilly (notifications@github.com)
wrote:

this is solved by being able to skip grading (checkbox at the top of the
grading column)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sagemathinc/cocalc/issues/1630#issuecomment-349045997>,
or mute the thread
