### ISSUE TITLE
projects show up multiple times while applying course upgrades

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1634]
projects show up multiple times while applying course upgrades. this is from a support request to describe the outcome:

> We have figured out the cause of the multiple instances, it occurs when 
> a subset of students do not receive upgrades. This occurred when a few 
> new students were added to the already upgraded cohort in the course.
>
> These instances vanish once the upgrades for the course were refreshed.

Maybe there is something not going 100% well while upgrades are applied.

**Comment by williamstein** [comment]
What does "projects show up multiple times " mean?   I have absolutely no idea what this means.   It's very ambiguous.  Where exactly do they show up?   

It seems way more likely it was different projects with the same title, and that everything was interrupted (due to recent server/db issues).  

I suspect this issue isn't meaningful and should be closed.

**Comment by williamstein** [comment]
closing since no feedback on my query.
