### ISSUE TITLE
Invited Student Names Don't Update Automatically

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/cocalc#1649]
To update your list of students with the ones who have signed up, you have to open and close the course file.

1. Add a student email who does not have an SMC account.
2. Keep the course file open.
3. In a different browser, create the student account with the appropriate email
4. Notice that the student listing doesn't change over to the student's name.

**Comment by DrXyzzy** [comment]
Replicated. Student name updates in .course eventually, when tab is refreshed, but not in real time. Also,
1. If student is added by email before the student creates an account, the student project is created with name `Unkown User - coursename`. When student signs up, name replaces email in .course student list, but project name is not updated.
1. Sometimes student email does not show up in the student list, ever. I'm looking for ways to replicate this. It happened with about half my students in a recent test course.
1. I also had a student whose project was created with name `student_email - coursename`. It raised some confusion because I told him to look for a project beginning with his name. So I also want to try replicating that.

**Comment by DrXyzzy** [comment]
Student email does not show up in student list if student already has an account and you search for student by name, then select and add the student.

**Comment by novoselt** [comment]
Looks like a collection of bugs that I have not seen complaints about, so I will assume that these have been fixed along the way.
