### ISSUE TITLE
course: allow student to (re-)submit assignment

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#167]
Suggested by S. Doty:

> Also, there is currently no way a student can notify me that they are re-submitting something, except by sending me an email. It would be nice if there was such a "notify professor" functionality in SMC itself.

**Comment by haraldschilly** [comment]
S. Quinn:

> In future, is it worth considering how students could actively submit 
> their assignment rather than the relatively passive collection approach?

**Comment by haraldschilly** [comment]
I removed "vague", because for this is about changing the pull model to a push model – or more general, to allow both and teachers can go through previous submissions of students by checking the backup history. 

(The last point indirectly implies that we implement a refined backup history specific to a subdirectory, such that it is easier to see previous revisions)

**Comment by williamstein** [comment]
> (The last point indirectly implies that we implement a refined backup history specific to a subdirectory, such that it is easier to see previous revisions)

The ZFS approach I wrote last summer, and am about to rewrite starting very soon, does this.

**Comment by williamstein** [comment]
I'm closing this since students don't submit assignments, and if a students wants to "re-submit" they could message the TA or instructor, who then decides to allow it and clicks a button.  That already exists.
