### ISSUE TITLE
jupyter GAP kernel

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#1706]
Updated goal (2018-12): install the GAP package "JupyterKernel".

- home: https://gap-packages.github.io/JupyterKernel/
- repo: https://github.com/gap-packages/JupyterKernel

The initial goal was to install the GAP package "jupyter-kernel-gap".

- https://github.com/gap-packages/jupyter-kernel-gap

which is now deprecated and replaced by "JupyterKernel".

**Comment by slel** [comment]
Installation works with

    sage -pip install jupyter-kernel-gap --user

after which selecting the GAP kernel in a jupyter notebook worksheet works fine.

Trying the jupyter console as follows

    jupyter console --kernel=gap

and then typing commands such as

    2 + 3;
    TransitiveGroup(10, 22);

reveals some error warnings, but results are ok
and the error warnings are not shown in a jupyter notebook.

**Comment by slel** [comment]
It's probably worth changing the `"argv"` value of `kernel.json`
to start with `"sage", "-python"` instead of the hardcoded
"/projects/sage/sage-7.5/local/bin/python" it gets after
installing via `sage -pip install`. See William's comment for
the PARI Jupyter kernel ticket: https://github.com/sagemathinc/cocalc/issues/160#issuecomment-317109302

**Comment by haraldschilly** [comment]
I'm wondering if `sage -i gap_jupyter` should work? see http://files.sagemath.org/spkg/upstream/gap_jupyter/index.html

Problem is, Sage doesn't find it !?

**Comment by haraldschilly** [comment]
Hmm, are these error messages (clearly some side effect of incorrect logging) reported upstream? We should do this...

**Comment by haraldschilly** [comment]
ok, also deployed, thank's for the help in testing this @slel !

**Comment by slel** [comment]
Regarding the error messages, it is a documented issue upstream, see
https://github.com/gap-packages/jupyter-kernel-gap/issues/36
https://github.com/gap-packages/jupyter-kernel-gap/issues/23

**Comment by slel** [comment]
Note that a complete rewrite of the GAP Jupyter kernel, written in GAP,
will be available with GAP 4.9. See the GitHub repo for this new kernel:
https://github.com/gap-packages/JupyterKernel

**Comment by slel** [comment]
Reopening this issue.

This comment initially posted at https://github.com/sagemathinc/cocalc/issues/791#issuecomment-446177455
might make more sense here.

GAP 4.10.0 is now installed on CoCalc. It seems that since then,
GAP's JupyterKernel went from "working until you divide by zero"
(which it was with GAP 4.9.3) to "not giving any output". Can
someone diagnose the problem, and open or point to
corresponding issues here or upstream as appropriate?

cc @markuspf @alex-konovalov @embray

**Comment by slel** [comment]
Is it maybe just because in CoCalc `gap` calls GAP 4.8.8
and one needs to call `gap4` to get GAP 4.10?

I suggest having `gap` call GAP 4.10, and, if there is demand for it,
have `gap-4-8-8` call GAP 4.8.8.

The new GAP JupyterKernel that works with GAP 4.10 relies on
either `gap` calling GAP 4.10 or there being an environment variable
`JUPYTER_GAP_EXECUTABLE` pointing to the GAP executable,
see http://gap-packages.github.io/JupyterKernel/doc/chap1.html

**Comment by haraldschilly** [comment]
well, I removed some older binaries, and I'm pretty sure it's fine. It just doesn't want to work properly on cocalc. First off, I really have to explicitly wait ~10 seconds to start up the notebook. Otherwise it's stuck (issuing a command too early, I guess). Then, either after the first or second cell (the second one is `1+1`), it hangs. It looks like that (currently in the experimental software stack)

In particular, it did print out the correct version.

![screenshot from 2018-12-11 17-42-45](https://user-images.githubusercontent.com/207405/49815596-67870f80-fd6c-11e8-83d4-4024993a0fc2.png)

**Comment by slel** [comment]
@williamstein The GAP Jupyter kernel works in Plain Jupyter and JupyterLab,
but not using CoCalc-Jupyter; can you have a look?

**Comment by haraldschilly** [comment]
@slel as explained in the chat, it hangs in certain situations. What exactly did you test, btw?

Here is cocalc's gap in the experimental software environment. It's stuck after "x", juypter kernel 1.0

![screenshot from 2018-12-15 12-01-41](https://user-images.githubusercontent.com/207405/50042240-a74a4180-0061-11e9-9586-ffb0abd710df.png)

Here is what you made on top of gap 4 with the jupyter kernel version 1.1

![screenshot from 2018-12-15 12-04-04](https://user-images.githubusercontent.com/207405/50042245-b4ffc700-0061-11e9-8428-1d79404eaeaf.png)

**Comment by embray** [comment]
Error handling in GAP is not great in general, and still an area for much improvement.  Though I don't see exactly how the issues I'm aware of would affect the GAP Jupter kernel (which is more or less just another GAP package, and which *does* do some odd things with error handling but nothing beyond the pale...)

In particular I have no idea why this would only be a problem in cocalc.

**Comment by haraldschilly** [comment]
@embray I also don't know exactly what's going on, but my suspicion is that during the very first initalization of cocalc <-> jupyter(gap), there is a slight problem and the evaluation halts. That case above, where it is completely stuck after trying to eval "x", is just another case, which exhibits similar symptoms.

**Comment by williamstein** [comment]
This is still totally broken today:

![image](https://user-images.githubusercontent.com/1276278/63077951-d5349e00-beee-11e9-86d6-ec6532674e2a.png)

This is pretty ridiculous.  Can we just **switch back to the pexpect kernel**?  Or maybe nobody uses cocalc-jupyter + GAP anyways?

**Comment by slel** [comment]
Apart from

- the original pexpect based kernel [[PyPI](https://pypi.org/project/jupyter-kernel-gap)] [[GitHub](https://github.com/markuspf/jupyter-kernel-gap)]
- the GAP-native kernel [[gap-packages](https://gap-packages.github.io/JupyterKernel/)] [[GitHub](https://github.com/gap-packages/JupyterKernel)]

there is now also

- the py-gap based kernel [[GitHub](https://github.com/markuspf/py-gap)]

if you want to give it a try.

**Comment by haraldschilly** [comment]
IIRC, I didn't get the pexpect kernel to work with the newer GAPs. It's an abandoned project. py-gap is maybe worth a try.

**Comment by embray** [comment]
Error handling in GAP is still a bit of a mess, and while I haven't trawled through the new GAP kernel in detail, I would not be surprised if there are some problems with error handling that it doesn't get right.

Sage's libgap interface is the only that I know of that gets error handling "right" (to the extent possible) (py-gap does not and is barely more than a hobby project).  My plan since reworking Sage's libgap interface has been to extricate it from Sage (very little of it actually depends on Sage, and the Sage-specific parts can easily live in Sage with the right refactoring) and spin it off as a more robust GAP interface for Python (I want to call it "gappy" but unfortunately that's already taken on PyPI for something less interesting :).  I wanted to get that done on OpenDreamKit time if possible.  Hopefully I can find something in the now ~20% I have to work on Sage-related things.  Otherwise, if someone else wants to take a stab at it, I'd happily provide support.

I think having a proper "gappy" with robust-ish error-handling will make it easier to write a more robust GAP kernel.  But who knows; maybe there are subtleties I've overlooked.

**Comment by slel** [comment]
The `JupyterKernel` GAP package should now be easy to install.

See for instance the recipe in the `gap-docker` dockerfile:

- https://github.com/gap-system/gap-docker/blob/master/Dockerfile

It would be nice to have it available in CoCalc.

**Comment by alex-konovalov** [comment]
Installation instructions depend on the version (were changed last year) and are in the package's README file - better to look there, then in the GAP docker container (not maintained any more, since we moved to using GitHub Container Registry - should delete or archive the old DockerHub ones).

**Comment by slel** [comment]
Thanks. The `JupyterKernel` package README, with installation instructions, is at

- https://github.com/gap-packages/JupyterKernel/blob/master/README.md

Installing it in CoCalc would extend CoCalc's new nbviewer-like feature
to GAP Jupyter documents, see

- https://groups.google.com/g/sage-devel/c/dQ8PXvp6o64/m/Zpv3lJnMAQAJ
- https://github.com/sagemathinc/cocalc/issues/6015#issuecomment-1172967091

**Comment by williamstein** [comment]
I'm closing this.  If we get new interest in using GAP via Jupyter in CoCalc by users who can't just install the kernel themselves, please open a new ticket.    We haven't had even a single request about this in years, and people can use GAP in other ways (e.g., via sagews and through sage itself).
