### ISSUE TITLE
false error "Cannot use '(' in a LaTeX filename"

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#1908]
To see the error:
1. Create a directory `DIR(foo)`.
1. Open `Files` view of that directory.
1. Click `+ New` and try to create a LaTeX Document with a file name that does NOT have special characters, for example `sample.tex`.
1. You will see the error `Cannot use '(' in a LaTeX filename`. Note that it _is_ possible to run `pdflatex` on the file with path containing the parens.

**Comment by williamstein** [comment]
this is already fixed (by you?)

**Comment by haraldschilly** [comment]
This one here puzzles me a bit. I think we have to check latex error handling, too.

i.e. there is a step "5" missing in your list: What happens if there is an error in the latex file? Are markers appearing?

If it fails to parse the log file, it should fail gracefully. I'm opening this and assigning it to me, just to see what's going on.

**Comment by haraldschilly** [comment]
ok, log file parsing for errors works. closing.
