### ISSUE TITLE
jupyter issue with tab completion and unicode

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#1994]
https://github.com/sagemath/cloud/issues/207

**Comment by stevengj** [comment]
Note that this affects both complete_request and inspect_request.

**Comment by williamstein** [comment]
It would be nice to have an example!

**Comment by stevengj** [comment]
Should be similar to the example in: https://github.com/nteract/hydrogen/issues/807#issuecomment-501337394

**Comment by stevengj** [comment]
As I commented in https://github.com/nteract/hydrogen/issues/807#issuecomment-522136141, I think you used the wrong test case — you need to use non-BMP characters.  That's why I suggested tab-completing 𝐚𝐚𝐚𝐚𝐚.

Also, don't look at whether completion succeeds — you need to look at the actual messages you are sending under the Jupyter protocol.

If you need a non-BMP example that is a valid Python 3 identifier and which does not normalize to some other character, try `𨭎𨭎𨭎𨭎𨭎`.

**Comment by williamstein** [comment]
Thanks for an actual test case.    My change does NOT work on 𨭎𨭎𨭎𨭎𨭎.
