### ISSUE TITLE
Login issue on Safari (iPad, Mac) to CoCalc running in Docker

### ISSUE THREAD

**Issue by ktaletsk** [sagemathinc/cocalc#2064]
Started my copy of CoCalc in Docker and it works fine when logging in from Chrome on different machines (Ubuntu PC, Mac, Android phone), but I can't log in from Safari on either iPad or Mac. It shows "connecting..."/"disconnected" in the upper right corner. At the same time, I can login to cocalc.com without any problem.

**Comment by williamstein** [comment]
NOTE: I think this is a security measure by Safari, and this security issue has been around forever.  Safari is not at all trustful of improper ssl cert setup.  Probably the only possible fix for this problem is setup a local PKI and make Safari trust it, or fully supporting using CoCalc without https.

**Comment by williamstein** [comment]
Since you're connecting with an ipad, I'm guessing you are hosting your docker image on some server somewhere.  It's very easy with CloudFlare settings to fake a valid ssl cert... I'll let you google for this.    But it's a way to solve your problem if you can go over the internet, rather than being restricted to a private local network.

**Comment by ktaletsk** [comment]
Thank you @williamstein, using CloudFlare solved the issue for me. Just need to choose "Full" mode for SSL and activate https redirecting in Page Rules.

**Comment by williamstein** [comment]
Cool!   I'll close this then.  Incidentally, 5 minutes ago I just got a new ipad pro, so expect to see some important usability improvements for ipad in the next few days (e.g., chat for files is currently completely broken).
