### ISSUE TITLE
iPad Pro: Tab completion doesn't work in SAGE worksheets. 

### ISSUE THREAD

**Issue by jonhanke** [sagemathinc/cocalc#2122]

**Comment by williamstein** [comment]
There are several issues like this that may be *completely impossible* to solve in a web application, due to how iOS handles input (the webapp never sees input until the user types a whole word and submits it).  In that case, having a tab button on screen that works, is the only possible fix.

**Comment by williamstein** [comment]
I'm WRONG -- these are definitely not impossible to solve.  E.g., regarding tab completion using the tab key on the iPad Pro keyboard, try this:
1. Open a terminal.
2. Put the cursor in the little text box at the very top of the terminal.
3. Start sage by typing "sage".
4. Type a little at the prompt, then focus the main terminal area (by clicking near the sage: prompt), and press the tab key.  It works!

![img_0053](https://user-images.githubusercontent.com/1276278/27344678-018868c4-559c-11e7-8aa2-a8413cae5349.PNG)

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.

If we do ever address this it would be a tab button that is available on mobile only, probably (or in the menu that is available by default on mobile).
