### ISSUE TITLE
Feature request - Rmarkdown build view

### ISSUE THREAD

**Issue by zeigerpuppy** [sagemathinc/cocalc#2237]
It would be useful to have a workflow for Rmarkdown (.rmd) files that allows calling a build script in a similar way to the existing .rnw.

For example, a simple build script (see below) will produce HTML/PDF output in a variety of formats using the *rticles* or *tufte* packages.

It would be great to have a `build` button above the HTML preview that allows outputting a PDF or HTML formatted output.

Also, I've noticed that cocalc creates .md files when making a preview from .Rmd files, these essentially have the code chunks substituted.  However, it may be clearer for users if these .md files were hidden.

```
require(knitr)
require(rmarkdown)
require(rticles)
require(tufte)

setwd("~/Article/") 

# build in article format: plos
# nb: marginnotes don't work in this format!
# rmarkdown::render("Article.Rmd", rticles::plos_article(), output_dir="_out_pdf")

# build in tufte format
# NB: multiple authors are not supported in this format
# see 
# - http://rmarkdown.rstudio.com/tufte_handout_format.html
# - http://rstudio.github.io/tufte/
rmarkdown::render("Protocol.Rmd", tufte::tufte_handout(), output_dir="_out_tufte_pdf")
rmarkdown::render("Protocol.Rmd", tufte::tufte_html(), output_dir="_out_tufte_html")
```

**Comment by haraldschilly** [comment]
I'm closing this issue. I wasn't aware of it when I changed several aspects how Rmd files are processed. That whole configuration can be done in the preamble, and PDF vs. HTML preview is selectable in the frame. There is also no longer such an intermediate .md file, because the processing pipeline changed.

Here is a quick example for such a tufte handout with two different outputs (config is in the preamble) https://share.cocalc.com/share/b9bacd7b-6cee-402c-88ed-9d74b07f29a1/tufte-handout/?viewer=share/
