### ISSUE TITLE
Install basic X11 support libraries, QT, etc., in our base linux image, to make building software easier

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2374]
Whether or not we support X11 forwarding or X11 in HTML5, we might as well do this.

**Comment by haraldschilly** [comment]
Hmm, maybe we should close this? It's possible to run quite specfic x11 apps, e.g. that vqe-playground. There are also many libqt5 packages installed. I'm assigning @DrXyzzy … since there is `P-hal`. What's this tag about btw? That it is a priority for you or that you're working on this? If not, please close it.

**Comment by slel** [comment]
@haraldschilly -- this originated in the discussion in
"CoCalc support request 4118" in the CoCalc ZenDesk.
Can you still access that?

**Comment by haraldschilly** [comment]
@slel  yes, but it's very old.

**Comment by haraldschilly** [comment]
I'm closing this, too vague and most likely outdated.
