### ISSUE TITLE
course: change the button title in courses from "Assign..." to "Reassign..." once an assignment has already been assigned.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2456]
People get confused.  If we made this change, it would be clearer that clicking the button again reassigns the assignment...

**Comment by johnjeng** [comment]
Got partway into this before realizing I should really be doing something else. 

If anyone looks at this, to change the header buttons, search 
```
_button: (status) ->
```
inside `assignments_panel.cjsx`to find all the functions that render those buttons.

Change the second half of `render_open_recopy_confirm: ` in `common.cjsx` to change the individual buttons.

**Comment by novoselt** [comment]
There is visual indication that assignment was assigned. It is a relatively special situation. And when the button is clicked for an already assigned assignment, there is a link to the doc regarding what exactly is going to happen, which is great - it is certainly not obvious. So the issue is taken care of.
