### ISSUE TITLE
implement email verification

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2470]
Email verification would work like this:
 - the account creation process remains 100% unchanged from now.
 - only applies if you have an email_address/password for your account, obviously.
 - if not verified, get a big annoying banner (with button) at the top of the screen asking you to verify your email.  Doesn't happen when fullscreen=kiosk (e.g., minerva shouldn't have to verify their emails).
 - user is also reminded somewhere of how to change their email if they try to verify and fail.  This is keeping in mind that people *do* make a lot of typos, so there will be a percentage like this.  when sending the verification it would display the email address we have for them.

The idea is that people would very likely do this within the first day or two of having their account, before the cookie expires.  This would dramaticlaly reduce the number of "i can't login because my account appears unknown (because I made a typo creating my account)".  People
might often think we just deleted their account right now.

**Comment by haraldschilly** [comment]
I have technical comments/ideas about how to store this information:

* since it is still possible to change the email, the entry about the verification shouldn't be a simple boolean, but maybe something like `verified:
 {"emal_address" :"..." , time: <timestamp>}`. That way we do not lose the email information upon changes. The timestamp isn't necessary, but probably neat to have.
* If there is no such `verified` entry or the current email differs from the verified one, the UI should show this action to verify.
* We should also think about the case of knowing that the email is ok (e.g. creating an account with a boolean flag that the email is known to be ok)
* Finally, when emails bounce back due to nonexistence, there should be a some way to mark it as invalid (but ok, so far there is no such integration, so that's for later)

**Comment by williamstein** [comment]
Yes, good point, there are several states:
  - 'no info'
  - 'verified' -- we know it is an address we can send messages to, and it belongs to the user
  - 'bounces' -- we can't send email to it. 
  - 'imposter?' - we can send emails and they don't bounce, but we have no evidence that the user controls this email address.

**Comment by williamstein** [comment]
obviously done long ago
