### ISSUE TITLE
in project settings there is a "Plain Jupyter Server" link -- make it work even the first time it is clicked

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2552]
Right now, clicking the "Plain Jupyter Server" gives a 504 error the first time, due to how long it takes jupyter to start.  CHANGE this to work.  

Ideas:

- Make the proxy server return something besides 504 within 3s (?) if the jupyter server doesn't respond; that returned content would be a small html page that says "loading" and uses javascript (?) to refresh the page again in 3s (say).

**Comment by haraldschilly** [comment]
I suggest we should do this in a general way, e.g. 

* add a minimal static page at the location `/static/loading.html`
* pass the URL you want to open as a parameter, e.g. `?target=<encodeURIComponent(url)>`
* write vanillaJS for loading the target via an ajax call, which retries it with some feedback, etc.

I've assigned this to me, because I'm pretty sure how to do the above.

**Comment by williamstein** [comment]
A much simpler more general approach is to make a special react component:
```
<LinkOpenWhenWorking href={...}>Plain ...</LinkOpenWhenWorking>
```
that just does an async javascript request to a given url (up to a given time) in the browser until the result doesn't 504 (or whatever), and only then redirects the user (via javascript) to the target.  

This is much simpler, generic, and doesn't require any extra infrastructure (so would work in our docker image, etc.).
