### ISSUE TITLE
additional 6 secs startup delay

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2557]
when starting cocalc, there is now a dependency on a file from a cdn. well, here is an example, where it took more than 6 secs to load it. only after that the usual loading of the website continued.

![cocalc-startup-delay](https://user-images.githubusercontent.com/207405/33724583-16208064-db70-11e7-98bf-3f150831c0b5.png)

IIRC this is for some styles in an early state of the page. I don't think it is good to almost double the average loading time just because of that. The outcome of this ticket is to find a better solution.

**Comment by williamstein** [comment]
This is probably a side effect of fixing another unprofessional "flicker" on startup (in which parts of the page would appear unstyled, then suddenly change and be styled), or of changes due to upgrading react-bootstrap. 

Also, what does "when starting cocalc" mean?  Are you measuring loading of the landing page?  Are you measuring a normal refresh once logged in?  Are you measuring the time from landing page to sign in page?  Are you measuring with caching disabled only?  Is this in dev mode or the production site?   What is your network profile?

Here's what I get when I just refresh after signed in, with caching enabled.  With caching **enabled** it only loads load that 22kb CDN css file once and never again at all, and my typical page load times are always about  2.5s at home.  With cachingdisabled it takes 133 ms at the beginning to load that css file and my overall page load time is about 3.0s every time:

![screenshot 2017-12-07 at 10 05 53 am](https://user-images.githubusercontent.com/1276278/33730910-522a5a38-db36-11e7-8436-959d64209f13.png)

> I don't think it is good to almost double the average loading time just because of that. 

I can't reproduce this claim.
