### ISSUE TITLE
issues or problems with saving files to disk (or database)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2561]
There are a million things that can potentially cause trouble saving a file, and Gabriel Indurskis says he has trouble saving files in some cases, so I've opened this ticket.

**Comment by gabindu** [comment]
Some information about the issue:

1. for unknown reasons, at a certain moment, the "save" button on a Sage worksheet suddenly gets the red warning message "NOT saved" (Note: this MAY have been due to auto-save, rather than me manually pressing the save button.)
2. the network connection, and the connection seems very good and stable (with very low latency)
3. manually pressing save has no effect
5. reconnecting the server connection has no effect (connection stays good)
6. saving other worksheets in the same folder works without any problems (including a newly created worksheet with the copy&pasted content of the original worksheet)
4. opening the TimeTravel for the original worksheet hangs: the history of the file tries to open, but shows an empty page without ever proceeding
7. reloading the page reopens the worksheet but with a previous state: the recent changes are lost.

**Comment by gabindu** [comment]
I should add that this is NOT an isolated incident for me: it has occurred several times during the last week, including once for a student during an in-class exam 2 days ago. (so it's not just related to my own computer/browser setup.)

**Comment by williamstein** [comment]
> for unknown reasons, at a certain moment, the "save" button on a Sage worksheet suddenly gets the red warning message "NOT saved" (Note: this MAY have been due to auto-save, rather than me manually pressing the save button.)

Thanks for clarifying what happens.  The entire time all of us thought your describing a completely different problem.  That message you are seeing refers to the connections between *your browser and the database*, and has NOTHING to do with the project, disk space, etc.   It's a problem I've never once witnessed myself ever, actually, where it didn't just go away in a few seconds.  It means for some reason the database is rejecting your writes.

**Comment by williamstein** [comment]
Replying to myself:
> It's a problem I've never once witnessed myself

And I'm logged in as admin... which is a major hint about what is wrong.

**Comment by williamstein** [comment]
Hopefully fixed now
