### ISSUE TITLE
webapp/library: store not always defined

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2585]
smc_git_rev: 2b31e49e8d69b2e6701077e37ea71f074ba9ff8a

Date: 2017-12-17 07:09:17.733075

`TypeError: undefined is not an object (evaluating 'e.get_store().library')`

```
success@https://cocalc.com/static/smc-d37030968ffce5fe3350.cacheme.js?d37030968ffce5fe3350:38:976
l@https://cocalc.com/static/lib-d37030968ffce5fe3350.cacheme.js?d37030968ffce5fe3350:22:14238
fireWith@https://cocalc.com/static/lib-d37030968ffce5fe3350.cacheme.js?d37030968ffce5fe3350:22:15005
r@https://cocalc.com/static/lib-d37030968ffce5fe3350.cacheme.js?d37030968ffce5fe3350:23:18674
https://cocalc.com/static/lib-d37030968ffce5fe3350.cacheme.js?d37030968ffce5fe3350:23:23526
```

which is in `smc-webapp/project_store.coffee`

```
    init_library_index: ->
        if _init_library_index_cache[@project_id]?
            data = _init_library_index_cache[@project_id]
            library = @get_store().library.set('examples', data)     # <==========
            @setState(library: library)
            return
```

**Comment by williamstein** [comment]
If you look at all the code I wrote in the project actions it does this sort of thing:
```
            store = @get_store()
            return if not store?
```
And most of the code other people wrote just assumes `@get_store()` returns something, and all those functions will likely fail in edge cases.

@johnjeng -- any thoughts about how to fix this particular thing right, in your opinion?

**Comment by johnjeng** [comment]
Generally, for now, it seems that 
```
async_foo = =>
  store = @get_store()
  return if not store?
```
is the best way to address this.

The only valid situation I can think of for this defensive code is when a user closes the UI responsible for the `store` in question **before** `async_foo` is called. 
In which case, don't do anything* because there's no longer any state.

It is a reasonable enough default to the point where I can see an argument for wrapping all actions inside something that checks for `store`. Not that I'm advocating for it, seems like unnecessary "magic".

Ideally our actions would async-await promise-like things but since the end result is making them [less cancel-able](https://stackoverflow.com/questions/37624144/is-there-a-way-to-short-circuit-async-await-flow), there's not enough [benefits](https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9) in my opinion.

*A pipeline of async functions which the user would want to continue is the exception to this. Eg. Creating student projects. However, telling the user not to close the page seems reasonable enough.

**Comment by johnjeng** [comment]
Only valid situation because the other situation I can think of (baring horrible mis-deletion of `redux.store`) is during initialization. I don't know why you'd be unable to fix the initialization order. Even then, I think the solution would be hoisting a version of `store.until` up to `redux.until`.

**Comment by williamstein** [comment]
OK, I think I'll just put this at the top of all functions there that use get_store, and have them use store (of course thinking if there are any special cases):
```
        return if not store = @get_store()
```

**Comment by williamstein** [comment]
OK, I hope https://github.com/sagemathinc/cocalc/commit/89681a637571fc003a67292db84726d088a5eb5d doesn't break anything badly.
