### ISSUE TITLE
Jupyter notebook sometimes hangs when no kernel is running

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2663]
user report:
> Unfortunately this is not a reproducible error, but it's happened to me (and some of my students) several times already this quarter. It sometimes happens that the Jupyter notebook thinks there is a cell executing (as indicated by the notation "In [*]:" where * stands for a circle with a left arrow inside) but the kernel has been interrupted (as evidenced by the fact that the "Interrupt kernel..." menu option is grayed out). Since the kernel has been interrupted, hitting the Stop button has no effect. In some cases, restarting the kernel also has no effect; the best bet is to reload the worksheet.

I have seen a similar problem with Sage worksheets occasionally after a long session of development. Flashing green bar indicates cell is running, but worksheet appears to have stopped. Clicking Stop and Restart, refreshing browser, and sometimes even reloading worksheet have no effect, bar keeps flashing and no cells execute. Might be the same issue. [hal]

See also: #2614.

Thanks to Kiran Kedlaya for reporting this problem.

**Comment by profbrady** [comment]
My students and I have had the same problem daily this semester. I hope it is already fixed (opened a ticket yesterday and heard that it may be). I am using CoCalc for all of my teaching this semester, there is no backup plan.

**Comment by williamstein** [comment]
There is a root cause for this problem, which I've been working fulltime on fixing for several days now.  Yesterday I created a temporary workaround, and after putting in a bunch of logging and studying it for hours today, I now know how to fix the root cause of the problem, and am working on that now.

What happens is that in certain cases (when the database connection fails for any reason) all outsanding messages to the webservers (either from the project or the user) just get dropped.  This stops certain things moving forward, which is precisely the issue you are observing.

**Comment by williamstein** [comment]
> Might be the same issue. [hal]

It's not.  It's sort of expected behavior in some cases, since we haven't yet implemented a proper stateful backend for sage worksheets, like for jupyter notebooks.  The flashing green bar is simply an indicator of the state of the document (an "r" in a certain place in a line that defines cell state), and there is no guarantee at all that anything is really running.    You could just open the sagews file in vim, edit the input line, and make a browser show flashing green...

**Comment by williamstein** [comment]
I think this is fixed these days...  I've not seen this in a long time, nor heard of any reports of it, and the 2019 project websocket architecture may have fixed it.
