### ISSUE TITLE
jupyter2: display an error in the output when there is an error evaluating javascript IPython messages, like what JupyterLab does.

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2732]
" if you need a Javascript library, please request it."

Does the error message [here](https://github.com/sagemathinc/cocalc/blob/1aa7caaea293cb01d8bed6b789dde06423cd0857/src/smc-webapp/jupyter/javascript-eval.coffee#L7) really make sense? With the dynamic re-rendering, this might not work at all in the first place. I think it's better to point to the classical notebook wiki page instead?

**Comment by jdeligt** [comment]
The error was thrown in a Python3(Anaconda) notebook

**Comment by jdeligt** [comment]
To replicate you can use:
%%javascript
require('//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min')
It triggers in (Unix)and(SageMath) notebooks as well

**Comment by williamstein** [comment]
This happens today.  Of course, nobody sees it since it is only in the console:

<img width="922" alt="image" src="https://github.com/user-attachments/assets/19b982eb-bef3-466d-bdf1-8b1d95d5b6f9">

And I don't think it makes sense.  This is still a bug, but a low priority one.

The fixed should be to make the javascript error itself (about no require) be visible in the output.

**Comment by williamstein** [comment]
What I just suggested for the fix is exactly what JupyterLab does (I didn't know that):

<img width="577" alt="image" src="https://github.com/user-attachments/assets/bc685591-d815-41d0-ac90-2270209ebd7d">
