### ISSUE TITLE
student email mixup leading to student list inconsistencies.

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2750]
There is a problem when a student is invited by the wrong email address, the account is created, and later the email address changes to the correct one. The situation leads to the state, where in the course file the account_id is correct, but the recorded email address is no longer the one from the account.

At least, that's what my hypothesis is. 

This issue here needs more work to figure out steps how to reproduce this.

Reference: ZD 5042

**Comment by gabindu** [comment]
I think this could be addressed by adding another (optional) account metadatum: a student-ID (or other unique identifier).

When students create their CoCalc account, they should be encouraged to put their current student-ID (given by their institution), and instructors can then add them by ID rather than email.  (Inversely, if the instructor invites students to create an account, the ID could already be prefilled from a CSV file.)

This would be especially useful for smaller institutions (like ours ;-) ) where students don't have an official school email.

**Comment by gabindu** [comment]
(I was about to add this as a new feature request, but then found this bug - I'll leave it up to you if you think this should become a new issue.)

**Comment by novoselt** [comment]
More generally: if I have a CoCalc account for email1 and somebody invites me to collaborate using email2, then instead of creating a second CoCalc account or asking to reinvite me using email1 it would be nice to "redirect" the invitation myself. This has to rely on me having access to both emails, i.e. I click on the link for email2, say on CoCalc that I actually want to use email1, and then a confirmation code is sent to email2.

Would this solve the problem with student emails too?..

**Comment by williamstein** [comment]
This is vague and 6 years old, and nobody even clarified it.  Closing.

Andrey -- your question is a real issue, but probably not really the same problem as this.   It could warrant a new issue.  That said, in 10 years somehow nobody ever complains about that theoretical problem, so it's not going to be a high priority.
