### ISSUE TITLE
course page (e.g. assignments) no longer restores scroll position 

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2780]
This is a very recent regression.

reported by Kelsey Johnson

**Comment by haraldschilly** [comment]
well, the `refs.editor_inner_container` always has a scrollTop of 0. Maybe just the wrong element being referenced?

**Comment by williamstein** [comment]
I think this should be managed by the editor itself, not here, since in many cases the "scroll position" is much more complicated (e.g., involving multiple panels); having this redundant state here is just begging for trouble.  But I'll merge hotfix for now, then entirely delete this code and put it back.

**Comment by williamstein** [comment]
hot fix at least fixes this.
