### ISSUE TITLE
keyboard handler in cocalc jupyter notebooks sometimes becomes inactive

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2806]
REPORTED BY: Kiran Kedlaya

> "Sometimes Shift-Enter mysteriously fails to do what it's supposed to
> do, but switching to another cell fixes the issue.

I've also seen this, I think.  It's an issue with reactivating the keyboard handler, I think. (New Task lists have a similar implementation, but work robustly.) 

@DrXyzzy -- any steps to replicate?

**Comment by williamstein** [comment]
I think I fixed this (I pushed a keyboard handler fix today).  Reopen if it can be replicated.

**Comment by kevinywlui** [comment]
I still notice it from time to time. I think it might be related to tab-completing an invalid sequence while a cell that will evaluate to an error is being run. Here's an example

![keyboard_handling](https://user-images.githubusercontent.com/1445341/43753984-4f58310e-99bd-11e8-815b-83320ea06f25.gif)

**Comment by kevinywlui** [comment]
To reproduce in general, you have to do an invalid tab completion while the backend is busy. There's a few ways to do this. 

Method 1
1. Start with new Jupyter file.
2. Type `x.fake` and hit tab a few times. This starts the backend.
3. Wait for the backend to idle after finishing starting.
4. Hit Shift-Enter and observe that you get a newline instead of a cell evaluation.

Method 2
1. Start with new Jupyter file.
2. Start the backend by first evaluating `1+1`.
3. Do some long (long enough so that you can do invalid tab completions) computation. For example,
```
import time
time.sleep(5)
```
4. While the long computation is running, type `x.fake` in a new cell and hit tab a few time to try to tab-complete this.
5. In a new cell, type `1+1` and Shift-Enter. Observe that you get a newline instead of a cell evaluation.
