### ISSUE TITLE
markdown link formatting is broken when the target link has a space in it.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2810]
1. Put this in a markdown file or task list:
```
[file with space](./a b.txt) and [file without space](./a.txt)
```

2. Notice that the first does NOT get properly converted!

![screenshot 2018-04-04 at 1 28 23 pm](https://user-images.githubusercontent.com/1276278/38332950-11331ad2-380c-11e8-90e7-a32081177f43.png)

REPORTED BY: Aaron Tresham

**Comment by johnjeng** [comment]
Uh, so it seems that markdown parsers are moving towards the common mark spec. https://github.com/markedjs/marked/issues/1202 However, common mark specifies that spaces aren't allowed in links http://spec.commonmark.org/0.28/#link-destination

So I guess I'll see if it's possible to write a plugin for our parser that allows whitespace inside links.

**Comment by williamstein** [comment]
I wonder if there is a good reason for excluding spaces?  I'm naive -- maybe allowing spaces causes some other parsing issues.  If there is a good reason, this could be a wontfix situation, and we can also change the "insert link" button bar to automatically put %20's in.

Note to readers -- one could use %20 in place of a space works:
```
[file with space](./a%20b.txt)
```

**Comment by johnjeng** [comment]
@joshbruce Note that in that example it's the link text which contains the space. In this issue, it's the link destination that needs the space. ie your example would have to be 

```
[link *foo **bar** `#`*](/uri/file with a space.txt)
```

Marked certainly parses this the way we want. Currently we're using [markdown-it](https://github.com/markdown-it/markdown-it) which doesn't do that because it follows the commonmark spec. My solution to this ticket would be to simply switch to using marked.js except for your ticket concerning commonmark

**Comment by joshbruce** [comment]
@johnjeng: Gotcha. Sorry, that probably was more obvious than it seemed to me after all the stuff I did today.

We should probably consider the HTML spec on URLs: https://www.w3.org/TR/html5/infrastructure.html#infrastructure-url

To be fair, Marked is trying to be as spec-based as possible because we would like to avoid debates of opinion and things like the CommonMark spec and HTML spec allow us to point to canonical sources for what rules to apply under certain circumstances. 

https://www.w3.org/TR/html5/links.html#links

**Comment by joshbruce** [comment]
ps. https://url.spec.whatwg.org/#urls

**Comment by williamstein** [comment]
Because github, etc. doesn't support this, and you should use %20's

 [file with space](./a b.txt) and [file without space](./a.txt)

 [file with space](./a%20b.txt) and [file without space](./a.txt)
