### ISSUE TITLE
Enable support for "from __future__ import ..." in sage worksheets

### ISSUE THREAD

**Issue by dv-extrarius** [sagemathinc/cocalc#2868]
In a previous ticket, I mentioned that I wanted support for the python 3-style print function (typically enabled via "`from __future__ import print_function`" in python 2 code) in sage worksheets, and a specific utility function was added to support that single use case.

However, I also want support for 'true division', which is typically enabled with something like "`from __future__ import division`" in python 2 code, and I'd really like to be able to stick to the common python 2 syntax for such things.

**Comment by williamstein** [comment]
This is now live.

Just out of curiosity, how would anybody ever find out about this functionality?

Is there any way to make it so typing
```
from __future__ import print_function
```
in a worksheet shows an error, and says `please use python_future_feature` instead...??

**Comment by DrXyzzy** [comment]
Note: this issue is related to #2862.

@williamstein - we could make the import `from __future__ import print_function` show an error - using logic similar to implicit multiplication detection in the commits for #2513. But with the approach in the present PR, the import simply works, as if the user were running a .py file. The latter seems preferable to me.

**Comment by williamstein** [comment]
> simply works.

oh -- nice!!
