### ISSUE TITLE
incorrect error banner on latex missing file error

### ISSUE THREAD

**Issue by tscholl2** [sagemathinc/cocalc#3023]
To reproduce:

1. Make a new latex file.
2. Add the line `\usepackage{thisfiledoesnotexist}` in the preamble.
3. Click build (or save if you have build-on-save enabled).

Expected: A banner that says what went wrong, i.e. a file was not found.

Actual:

![screenshot 2018-07-31 at 8 35 54 am](https://user-images.githubusercontent.com/8905985/43473181-48739978-94a4-11e8-914d-19fc69876e6c.png)

To be clear, I believe that the "formatting" of the document is correct.

**Comment by haraldschilly** [comment]
The PR contains a simplified message, hence it is probably ok to close

the underlying issue is that particular case here is that changing any dependency of the primary tex source file isn't reflected in the "last modified" timestamp which is used when running the build command. An idea is #3017 which would trigger a forced rebuild if a user tries "harder".
