### ISSUE TITLE
open returned GRADE.md in single-pane, rendered view by default

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3135]
Per #2987, grades are returned to students as `GRADE.md` files. Opening one of these as a student, I see the usual vertically split view, Code on the left and Rendered View on the right. It would make more sense for the student to see only the rendered view by default.

**Comment by williamstein** [comment]
Concern:  There's no way to do this in the current framework of CoCalc, and in order to enhance functionality enough to make something like this make sense... will probably be as hard as just creating much more serious ".student" functionality..

**Comment by novoselt** [comment]
I would be strongly against different behaviour for files with the same extension, it would be indeed better to make a new one, despite using md inside. But instead of just suppressing a frame, it would make more sense to have some better view of the assignment including grade and comments. If the current view is insufficient, however, we need a new issue and more thoughts ;-)
