### ISSUE TITLE
course assignment UI indicator could be stuck in assigning 

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3286]
I don't know if this is part of another ticket (haven't found one), but it is possible that the UI indication for assigning an assignment is stuck in the state of sending out for days. That doesn't make any sense. (neither refreshing browser, nor close/reopen of course file fixes that, btw.)

![screenshot from 2018-10-12 13-51-17](https://user-images.githubusercontent.com/207405/46867663-17500780-ce26-11e8-869a-16778687cb04.png)

**Comment by haraldschilly** [comment]
maybe interesting for debugging, assigning again claims that all are assigned. I think that's another issue, though.

![screenshot from 2018-10-12 13-54-16](https://user-images.githubusercontent.com/207405/46867750-5ed69380-ce26-11e8-952c-3fe22938ce46.png)

**Comment by williamstein** [comment]
Right now assignment is carried out by a particular web browser.    How about if we add something -- basically a "dead man's switch" -- to the .course file, where whatever is doing the actual assigning periodically updates it.   Then anything viewing the course can periodically check that, and if it is not updated, conclude that whatever was assigning has failed, and change state to reflect that.

Right now -- the way things are implemented, if you started an "Assigning" operation, then closed your browser, it *should* get stuck staying in that state basically forever.  It's not surprising at all that this happens, if you think about what we implemented.

The other option is to somehow move this entire operation to the backend... and obviously we'll need to do that for several operations for courses at some point!  Maybe we just need an api for course functionality, and manage-course (?) to handle all of it, similar to manage-copy.   It can't happen in projects because they are not always running, and they do not have permission to access other projects.

**Comment by novoselt** [comment]
@williamstein What is the status regarding your comment? Is it done in the backend now?

**Comment by williamstein** [comment]
Not done in the backend, and it's still a potential issue.  Moving everything to the backend would solve some problems, and probably cause others (and make dev much harder in some ways)... I don't know what will happen longterm.

**Comment by williamstein** [comment]
For the record, there is no location at all in the entire architecture of cocalc for this functionality to exist in the backend.  It can't exist in the project, because the project doesn't have access to any other project -- it's the *instructor* that has access to other projects, not the project.   We would have to significantly change/weaken the security of cocalc to allow the project to access other projects via the api.    This is a way in which courses are significantly different than jupyter (say).

Another possibility is to create an entirely new nodejs service that manages state of courses, but also can be trusted and has access to all projects, like the hub's now.    Such a service is of course very dangerous from a security point of view, because it would combine being all powerful with also having to do real nontrivial tricky work to support an application.  That's also not desirable at all. 

So there's really absolutely no possible way to move the entire functionality of courses to the backend without major negative security implications.  

An alternative is just slightly expanded the api for copying files to be more flexible.  If you want to copy a directory to 250 target projects, you make that request as a single api call and get back a token. You can then use that token to check up later on exactly what happened with any of those 250 copies (say), and the client then updates the course state accordingly.    
Also, this copy could be scheduled at a point in time in the future.  These sort of primitives are a much better approach to this problem, since they are more generally useful anyways, and don't require any changes to our security model.  Also, I think @haraldschilly  even mostly wrote something like this, which is a good sign that it can be done...
