### ISSUE TITLE
Grade sheet for students

### ISSUE THREAD

**Issue by stats-matt** [sagemathinc/cocalc#331]
I think it would be useful for students in a course to have a "gradesheet" where they could see all of the grades they have, instead of having to go to each folder to check for a grade. Something like the course view of the instructor would work very well - maybe being a member of a .course file could create a complementary .student file for each member of the class?

**Comment by williamstein** [comment]
Very good idea!   The .student file would get updated with status information, including grades, when things are due, etc -- similar to what is in the directory for each assignment.   Thanks for suggesting this, since I hadn't thought about it in any detail.  If you have more details about what you might want, don't hesitate to put them here.

**Comment by mthomas7** [comment]
Grades and deadlines were my two initial thoughts. Another possibility (that needs to be considered more carefully than the 30 seconds I have so far) is a "submit" button. This would allow the instructor to start grading things early as they are submitted. That could interfere with the "collect all" button for the instructor, though, maybe needing to be a "collect unsubmitted" or something like that, I'm not sure. This may be more than is necessary, since the collect button works just fine.

**Comment by mthomas7** [comment]
Another nice link might be direct links to the assignment folder and the "graded" folder for each assignment.

**Comment by mikecroucher** [comment]
In addition, I'd like to see the ability for an instructor to download all grades for all students as a single .csv file

**Comment by williamstein** [comment]
It's already there in settings. You can download as csv or as a python
script.

On Friday, February 19, 2016, Mike Croucher <notifications@github.com>
wrote:

> In addition, I'd like to see the ability for an instructor to download all
> grades for all students as a single .csv file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/331#issuecomment-186292841>.
>


-- 
Sent from my massive iPhone 6 plus.

**Comment by williamstein** [comment]
Here's what Google's looks like:

![screenshot 2019-02-16 at 8 49 18 am](https://user-images.githubusercontent.com/1276278/52902586-dd25b680-31c7-11e9-8474-4d36b3e4c411.png)

**Comment by novoselt** [comment]
I'll close this as not very concrete and very stale, the idea is basically that "student interface can be better"
