### ISSUE TITLE
x11: arrow keys do not work in snappy and octave

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3332]
REPORTED BY: Nathan Dunfield

> "I tried running the SnapPy app in X11 via: `sage -python -m snappy.app`
> Everything works, including the OpenGL 3D graphics, except for the arrows keys in the main window (titled "SnapPy Command Shell"). Specifically, hitting the arrow keys does not move the cursor at all; I'm using Chrome 70.0.3538.77 on macOS 10.12.6.

**Comment by williamstein** [comment]
Also, if you type `octave` then use the command line, arrow keys don't work there either.

**Comment by williamstein** [comment]
However, in every other application that I specifically tested, the arrow keys work (e.g., Rstudio, wxMaxima, etc., etc.).    This may be a bug in snappy/octave, which might be using some custom weird command line handling instead of (say) gnu readline, and it's just incomplete...

**Comment by NathanDunfield** [comment]
SnapPy uses Tk for the GUI, with the SnapPy Command Shell running an IPython shell.  The issue appears to be that Tk distinguishes between the arrow keys on the keyboard and those on numeric keypad, and it's getting the latter.  With the little script copied below, when I hit the right arrow key I get the event "KP_Right" instead of "Right" as I do when running the same script on a local Ubuntu Linux box.  

```
# Run with: sage -python this_file.py
# activate the "tk" window and hit keys.
from Tkinter import *
def key_pressed(event):
    print('Key: ' + repr(event.keysym))
main = Tk()
frame = Frame(main, width=100, height=100)
main.bind('<KeyPress>', key_pressed)
frame.pack()
main.mainloop()
```

This same script also illustrates the issue I am having with emacs in X11 where control is giving me meta; just hit "control" with the above script and I see "Alt_L" not "Control_L".

**Comment by NathanDunfield** [comment]
You can also use the `xev` command the ordinary CoCalc terminal window to see the X11 keypresses.  It is indeed getting the `KP_*` versions by X11's own reckoning:
 
```
   KeyRelease event, serial 36, synthetic NO, window 0x600001,
    root 0x298, subw 0x0, time 39786851, (34,332), root:(34,332),
    state 0x0, keycode 85 (keysym 0xff98, KP_Right), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

**Comment by williamstein** [comment]
@NathanDunfield  - thanks -- that should be enough for me to fix things.  CoCalc's X11 support uses a complete rewrite (by us) of the official XPRA html5 client, so we can easily change anything about how keys are mapped... in particular change their choice of how the arrow keys are mapped.

**Comment by williamstein** [comment]
OK fixed; will be live soon.

**Comment by NathanDunfield** [comment]
Thanks, I can confirm that the commit fixed my issue with the arrow keys.
