### ISSUE TITLE
changing account email in CoCalc does not update email address in Stripe

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3453]
to replicate:
1. create test account using email address
1. sync with stripe using admin tab
1. verify CoCalc account id's match in stripe and admin tab
1. change account email address using Cocalc `Account` > `Preferences`
1. sign out and back in with new email
1. verify new email address matches CoCalc account id in admin tab
1. sync with stripe again
1. search by CoCalc account id in stripe
1. observe that old address is still shown in stripe customer record under both "Account Information:Email" and "Billing Information:Send emails to"

**Comment by williamstein** [comment]
This doesn't surprise me, since we never implemented anything to do this.  They unique identifier between stripe and cocalc is the customer id, which we also have in our database (and also the  account_id metadata, but that's not used), not the email address.  Many users don't even have email addresses (e.g., maybe they use single sign on and don't provide one), or they have multiple addresses (one for github, one in cocalc, etc.).  

So to me this isn't a bug, but I can see how it could be confusing to you.   We could have a feature to add a link to the stripe page for a user to the admin page in cocalc, since the stripe url is just `https://dashboard.stripe.com/customers/customer_id`.

**Comment by williamstein** [comment]
Fixed, then made no longer relevant...
