### ISSUE TITLE
Install tldr-pages

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#346]
Please install tldr-pages: http://tldr-pages.github.io/

**Comment by williamstein** [comment]
I tried installing this system-wide and it requires *every* single user do `tldr --update`, even after I explicitly do that as root.  So it's really not user friendly for a system-wide install.    If users have to figure out how to do `tldr --update` themselves anyways, they may as well just install tldr into their own project using `npm install -g tldr`.

If you're the author of tldr, please make it so it can use a system-wide global cache by default, and only require the user to do something if they want their own update.  Otherwise it just feels sort of broken...

**Comment by waldyrious** [comment]
Linking https://github.com/tldr-pages/tldr-node-client/pull/48 for cross-referencing.

**Comment by slel** [comment]
There is now a [Node.js command-line client for TLDR-pages](https://www.npmjs.com/package/tldr).

Does this provide an easy way to install globally?

That would be a nice addition to the [recent addition of man/doc pages on CoCalc](https://github.com/sagemathinc/cocalc/wiki/SoftwareUpgrades#2018-09-01).

**Comment by slel** [comment]
It's now easy for any user to just type the following in a terminal
```
pip install tldr
```
and then they got tldr working.

This possibly also makes it super-easy to install system-wide?
