### ISSUE TITLE
erroneous "popups blocked"  warning

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3504]
I suspect this is a fallout of rel=noopener, or well, I only noticed it during testing right now. Maybe there was already a problem before that, I don't know. To trigger it, shift-click on an editor tab.

> Popups blocked.
> Either enable popups for this website or click on this link.

 But the window popped up fine.

My browser is `Version 72.0.3626.71 beta`, which could also be a reason for that.

**Comment by williamstein** [comment]
I see this also with 71.  It is likely rel=noopener fallout, since I added it to the code `misc_page` as well, which is used by chat.   

The problem for us that rel=noopener addresses is potentially so severe, I think we should:

1. Just change the message in the alert to say "Popup blocked?  If the popup did not appear, click this link." and have it always appear (as it is doing now).
2. Change any code that used that popup code in misc_page to NOT use it, and instead have an explicitly link that has to be clicked, then remove that code entirely from misc_page.   We can definitely do this in all cases.  E.g., at worst, you click somewhere, stuff happens in javascript for a while, then a link appears and you click on that.  That would likely be a better UI in all cases anyways.

**Comment by haraldschilly** [comment]
I've searched a bit around, and came across this "workaround": https://stackoverflow.com/a/49276673/54236

I'll look into this, maybe it will work for us.
