### ISSUE TITLE
sync: Uncaught Error: can't set until table is initialized  

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3595]
I'll add more notes later. I think I triggered this by using time travel to revert a small html file back to a previous version. (I also restarted the project, etc., but it keeps happening)

**EDIT** or, maybe it's because I have a terminal open and run a utility (`tidy`) on that file. this utility modifies the file and I think the error below happens when it should show the modified changes (they aren't showing up all the time). If I have more time, I'll try to make this reproducible.

```
smc-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:5 Uncaught Error: can't set until table is initialized
    at t.set (smc-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:5)
    at t.commit_patch (smc-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:5)
    at t.commit (smc-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:5)
    at t.syncstring_commit (smc-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:5)
    at t.save_syncstring (smc-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:5)
    at smc-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:5
    at o (0-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:6)
    at 0-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:6
    at e._wrapper.e._wrapper (smc-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:5)
    at smc-b4368edfb0c121c94907.cacheme.js?b4368edfb0c121c94907:5
```

**Comment by williamstein** [comment]
> by using time travel

That seems very plausible actually.  I bet the code there doesn't properly check the state of the syncstring or something... I'm planning to rewrite timetravel from scratch next (starting today), so should fix this along the way (and at least take care that this edge case is addressed properly).

**Comment by williamstein** [comment]
I just had an evil idea:

1. Open an ipynb file (say) and edit it,
2. Disconnect yourself from the internet
3. Edit slightly more and close the file.
4. Go to files and try to open the file again.
5. Reconnect to the internet.
6. BOOM -- it never loads and there's a useless red "timeout" error. 

---

I just tried 1-6 again and it worked fine (no problems). Then tried again and edited actively while offline... and it resulted in this traceback:

![screenshot 2019-02-18 at 2 36 33 pm](https://user-images.githubusercontent.com/1276278/52979602-2e31d800-338b-11e9-88f0-dd5ee923ade3.png)

---

Flaky connections are critical to have fully work right, since our backend can have nodes come and go, and autoscale up and down, and that can have a similar impact, even with a perfect network.

**Comment by williamstein** [comment]
Even after waiting to fully reconnect, this keeps happening:

![screenshot 2019-02-18 at 2 51 09 pm](https://user-images.githubusercontent.com/1276278/52979929-ac42ae80-338c-11e9-8d7a-97ffeb380bef.png)

**Comment by williamstein** [comment]
I think the root cause of the problem is missing reference counting code.  This is sort of like a double free in C++. Making this a blocker.
