### ISSUE TITLE
Add @ mentions for chat

### ISSUE THREAD

**Issue by matthew-brett** [sagemathinc/cocalc#3599]
The chat feature is very useful, but it's difficult for instructors to keep up with the chat outside class hours.   We have 11 student projects, and five instructors.  Most of the time students will be chatting each other.  It's hard for instructors to monitor Cocalc all the time for stuff they should attend to.

It would be good to have an `@name` mention feature, as in `@matthewbrett`, in the chat, which would email the named user.  A nice extension would be `@group` where `group` was a defined group of users, say instructors, so `@instructors`.

**Comment by williamstein** [comment]
Do you use gitter? If so, is this much like how gitter works?  What's your favorite chat program in terms of @mentions?

**Comment by matthew-brett** [comment]
I don't use Gitter or any other chat really - I was only thinking of Github, where I use @mentions a lot.   For our use case, we'll probably have to ask the students to email us when they have something they want us to look at in chat, which is less convenient.

**Comment by johnjeng** [comment]
Looking into this because it's something I really want...

**Comment by williamstein** [comment]
1. A few seconds of googling finds [this](https://github.com/signavio/react-mentions), which does most of the frontend work.

2. We do some backend work at a mention_user api call that sends an email.

Boom -- the functionality you need is available.

Then there is a lot to add **later**, e.g., muting project or path, throttling notifications, showing past notifications, etc.

**Comment by williamstein** [comment]
Hi -- a minimal version of `@mentions` is now live on cocalc.com.  You may have to refresh your browser.  Then in a chatroom or side chat, type @ and mention somebody (in the list) who is a collab on the project.  They should get an email with a link to the chat (unless filtered by a spam filter, of course).   If you mention the same person again within 8 hours they do NOT get notified again.   That's it for now...

**Comment by matthew-brett** [comment]
Is there any way to configure the 'within 8 hours' criterion?   I'm working with a student, and it's very easy to get into the situation where I've left the session, and she still needs to ping me via email easily.    0 hours would be my choice for default, in that situation.

**Comment by williamstein** [comment]
> Is there any way to configure the 'within 8 hours' criterion?

No, nothing is implemented, but I think it would be relatively easy to do the following:  If a user does @mention, and the person they are mentioning isn't actively using the file (as is known by their face/avatar appearing at the top), then they get an email notification.   If they are not actively using the file, they always get an email.

When we first wrote @mention, I think it would be critical to have a way of muting emails from a given file/project/user though before implementing the above,  since otherwise it could be abused.  Email did get abused badly and we cut it off completely unless the project has been upgraded to have network access, so basically only paying customer can send emails via @mention.  This means in practice that @mention doesn't get abused, which means it's much more reasonable to implement the above before worrying about muting.  Thoughts?

**Comment by williamstein** [comment]
Moved to https://github.com/sagemathinc/cocalc/issues/4010
