### ISSUE TITLE
restore xpra html5 copyrights

### ISSUE THREAD

**Issue by totaam** [sagemathinc/cocalc#3617]
As per:
https://github.com/andersevenrud/xpra-html5-client/issues/1
The original authors of those files should be preserved.

**Comment by williamstein** [comment]
Just to clarify:

1. Your comment only applies to this directory: https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/frame-editors/x11-editor/xpra/

2. You do NOT consider the detailed license discussion we include here to be sufficient: https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/frame-editors/x11-editor/xpra/README.md
Note that we definitely did not change the license, and in fact complain in that file about somebody else improperly doing so. 

3. What is the license of Xpra-html5-client?    I thought it was GPL (like xpra) when I did work on this last year, but looking now it says MPL. 

4. In addition you want us to add back copyright headers.  Note that the code very much isn't just "Changing the code structure and language does not allow you to remove the copyright notice, or change the license.".   The code is months of work, that has been massively refactoring, rewritten, restructured, with some completely new files added.   I agree that definitely it is a derived work.  It's much less clear that it make sense to put exactly the xpra-html5-client copyright header on the top of a typescript file that I wrote, which shares no code with the xpra-html5-client.   It's very clear that this client is a derived work and must make that clear.  But how?

**Comment by totaam** [comment]
1. Yes
2. I'm not blaming you guys for the removal, this was clearly done before you took the snapshot.
3. MPL
4. I appreciate that it is months of work, refactoring, rewritten, etc. Nonetheless, you can still clearly see the ancestry for most of those files, which is why the copyrights should be preserved.

(side note: had we been contacted about this porting effort, we could have worked together on this. As it stands, we're likely to start again from our version of the code and diverge further..)

**Comment by williamstein** [comment]
> 3. MPL

That's very good news -- it's a much better license for us than GPL.

> (side note: had we been contacted about this porting effort, we could have worked together on this. As it stands, we're likely to start again from our version of the code and diverge further..)

Much of the code I wrote is customized for a tabbed/tiled interface, rather than a standard window layout, which is what cocalc uses.  There's also a lot of worry in my code about dpi and scaling.  This made things much easier in some ways (and harder in others).    What would have helped a lot would be even better documentation for the Xpra client protocol; maybe that will come out of the future work you're planning?   

> 4. ...ancestry

I ready more about MPL, and I can see why per-file-copyright headers are so critical, since it's a per-file license.   I'm adding the following:
```
 * CoCalc's Xpra HTML Client
 *
 * ---
 *
 * Xpra
 * Copyright (c) 2013-2017 Antoine Martin <antoine@devloop.org.uk>
 * Copyright (c) 2016 David Brushinski <dbrushinski@spikes.com>
 * Copyright (c) 2014 Joshua Higgins <josh@kxes.net>
 * Copyright (c) 2015-2016 Spikes, Inc.
 * Copyright (c) 2018-2019 SageMath, Inc.
 * Licensed under MPL 2.0, see:
 * http://www.mozilla.org/MPL/2.0/
```

This will be in our code very soon.

> (side note: had we been contacted about this porting effort, we could have worked together on this. As it stands, we're likely to start again from our version of the code and diverge further..)

XPRA awesome, and I'm glad you guys are working further on it.   Hopefully there can be some opportunity to collaborate going forward.   When I was working on this, it was a sort of accident where I just trying to integrate something (guacamole, or one of the other html5 clients for x11), and things got surprisingly more complicated than expected, and this code emerged. It wasn't at all planned.

**Comment by totaam** [comment]
> I'm adding the following...

The copyrights vary from file to file.. so you don't need to add them all to all the files. I'll let you be the judge of that.

> Hopefully there can be some opportunity to collaborate going forward.

I've created a new ticket scheduled for the next milestone:
http://xpra.org/trac/ticket/2165
(not sure what's going to go in it just yet)

> .. things got surprisingly more complicated than expected, and this code emerged. It wasn't at all planned.
Haha. I know the feeling!
