### ISSUE TITLE
Erlang dark theme with CoCalc Jupyter notebook is only effective while cell is being edited

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3647]
Reported by Daniel K.

**Comment by williamstein** [comment]
This is more of a NotImplementedError, since it's very hard to implement.  

WORKAROUND: A workaround is to select View --> "Toggle all line numbers", and the notebook will fall back to a mode that renders every cell using codemirror, hence all cells will be in whatever theme you select.   However, this is significantly slower if your notebook is really large.
