### ISSUE TITLE
x11: xpra 2.5 breaks websocket connection

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3703]
The current upstream version of xpra is `xpra v2.5-r22135`. It also switches from python 2 to python 3, i.e. there is `python3-xpra` now. I started a branch, but there is no real progress: https://github.com/sagemathinc/cocalc/pull/3702

2.5 news: http://xpra.org/trac/wiki/News

The error is 

```
WebSocket connection to 'wss://cocalc.com/14eed217-2d3c-4975-a381-b69edcb40e0e/port/56754/bc6f81b3-25ad-4d58-ae4a-65649fae4fa5/server/51218/' failed: Error during WebSocket handshake: Unexpected response code: 502

createWebsocket @ connection.ts?6df9:25
Connection.open @ connection.ts?6df9:80
Client.connect @ client.ts?ef43:200
(anonymous) @ xpra-client.ts?85da:139
step @ xpra-client.ts?85da:1
(anonymous) @ xpra-client.ts?85da:1
fulfilled @ xpra-client.ts?85da:1

```

**Comment by williamstein** [comment]
We might have to fork upstream, unfortunately.

**Comment by haraldschilly** [comment]
I think I at least understand what's going on at a higher level. previous to 2.5, the python client was for version 2 and packages with xpra. For 2.5, they separated that and there is a python3-xpra package. I'll downgrade and see if that works. What I haven't tried is to install python2-xpra instead.

**Comment by haraldschilly** [comment]
good news, I got it working. It's working again by installing python2-xpra and **not** (the default) python3-xpra package. I just uninstalled/installed with `install --reinstall` or whatnot. I never directly saw an error, but my guess is that either there is a python 3.5 vs 3.6 incompatibility, or some dependency library is slightly off. 

for reference

```
root@c094a84fed18:/# dpkg -l | grep xpra
ii  python2-xpra                                                     2.5-r22135-1 
ii  xpra                                                             2.5-r22135-1 
ii  xpra-html5                                                       2.5-r22135-1 
root@c094a84fed18:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

**Comment by williamstein** [comment]
Any thoughts about cocalc docker?  I don't explicitly install python2-xpra or python3-xpra... just the "xpra" package.

https://github.com/sagemathinc/cocalc-docker/blob/master/Dockerfile#L238

**Comment by haraldschilly** [comment]
> python3-xpra is not meant to be the default anywhere

I ran `aptitude safe-upgrade` and it was there. I saw that upon xpra startup it checked for python2, didn't find it, and then selected the python3 xpra library. So, explicitly installing `python2-xpra` will solve it.

> So maybe the bug is in your client?

This is definitely a possibility. However, since I am not familiar at all with that code (neither in cocalc nor xpra), I don't know how to extract more information about what's going on behind the scenes with python3 xpra vs. the client.

**Comment by totaam** [comment]
> I ran `aptitude safe-upgrade` and it was there.

I don't know how aptitude chooses one over the other. Maybe the one that has fewer new dependencies to install? (it would make sense since python2 is on its way out)

> I don't know how to extract more information about what's going on behind the scenes with python3 xpra vs. the client

I would first try connecting with the python client and / or the official html5 client to verify that this works.

If the bug does occur with those then the bug is in xpra. The server's `-d network` log output should have more details.

If it does not occur then the bug is very likely to be in your client only, and I can't really help much with that, except to point out that unless your client exposes this new feature flag:
https://xpra.org/trac/changeset/21544
Then it will be using the old behaviour `LEGACY_FRAME_PER_CHUNK` mode:
https://xpra.org/trac/changeset/21542
Maybe that's exposing a backwards compatibility problem in the xpra server - unlikely but possible.

In any case, if your client does not have the same websocket frame parsing bug as this:
https://xpra.org/trac/changeset/21511
Then you should also expose the new flag to use the newer / better websocket packet framing code.
