### ISSUE TITLE
xpra compression_level=9 should not be used

### ISSUE THREAD

**Issue by totaam** [sagemathinc/cocalc#3704]
Landed on this setting by accident here: https://github.com/sagemathinc/cocalc/pull/3702/commits/26badffa7c95569a45d7a0379f2c2277262ea141

Since you have lz4, the man page reads:
```
Select the level of compression xpra will use when transmitting data over the network. 
With the lz4 and lzo compressors, there are only two possible values:
0 (meaning no compression) and 1 (compression enabled).
The zlib compressor supports values between 0 (meaning no compression) and 9, inclusive.
It should only be used when lz4 and lzo are not available.
```

**Comment by williamstein** [comment]
Thanks -- I'll fix this asap.  We were not using lz4 initially (since the javascript client is large), and the lz4 client that the os-js dev had attempted first to use instead didn't work at all.    I ended up using the same lz4 javascript client as is used in the html5-client, and hence got lz4 support.

**Comment by williamstein** [comment]
And obviously, many thanks for looking at our code!!
