### ISSUE TITLE
sometimes cocalc-Jupyter shows a (probably harmless) timeout message in red at the top.  This is disconcerting since it's not clear what timed out.

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3784]

**Comment by DrXyzzy** [comment]
![red-timeout](https://user-images.githubusercontent.com/528072/56845762-daaca080-688b-11e9-9a5e-b122c73884a9.png)

**Comment by brianfields** [comment]
We have also encountered this issue. It wasn't harmless though, since the notebook no longer worked. We saw many instances of the following message in the console:

VM756:3524 WebSocket connection to ‘wss://cocalc.com/6e5fcfa8-5822-47cc-8df6-6ab8485e8547/raw/.smc/ws?_primuscb=Mh2MzTn’ failed: Error during WebSocket handshake: Unexpected response code: 504
opening @ VM756:3524
emit @ VM756:352
reconnect @ VM756:3554
emit @ VM756:331
reconnect @ VM756:2681
emitter @ VM756:146
emit @ VM756:1245
delay @ VM756:1087
tickedtock @ VM756:1555
e._wrapper.e._wrapper @ smc-25e69581d6cb85e4382f.cacheme.js?25e69581d6cb85e4382f:5
(anonymous) @ smc-25e69581d6cb85e4382f.cacheme.js?25e69581d6cb85e4382f:5

**Comment by brianfields** [comment]
We were running many projects simultaneously in a large classroom with breakouts when we encountered the above problem. The upgrades applied to the projects (~60 projects) were:

        "small-upgrades": {
            "cores": 1,  # 1 upgrades
            "memory": 2000,  # 2 upgrades
            "memory_request": 0,  # 0 upgrades
            "network": 1,  # 1 upgrade
            "cpu_shares": 0,  # 0 upgrades
            "disk_quota": 0,
            "member_host": 1,  # 1 upgrade
            "mintime": 86400  # 1 upgrade
        },

**Comment by williamstein** [comment]
Too vague and haven't heard about this in 1.5 years.  Maybe the vague messages are now gone?
