### ISSUE TITLE
jupyter ipywidgets - standard widgets that don't work right

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#3789]
- [x] DatePicker doesn't work right.

![image](https://user-images.githubusercontent.com/1276278/56841251-78c74900-6841-11e9-922c-f623fe8267ad.png)

(there is no output -- using the datepicker isn't resulting in it properly propagating state to the backend.)

versus

![image](https://user-images.githubusercontent.com/1276278/56841257-7fee5700-6841-11e9-8456-91009495bbb6.png)

**Comment by DrXyzzy** [comment]
- [ ] No output after clicking button, but nice icon choices are available:

<img width="701" alt="cocalc-button" src="https://user-images.githubusercontent.com/528072/56844145-4d5c5280-6871-11e9-8d4a-54d12e8c927f.png">

versus

<img width="676" alt="classic-button" src="https://user-images.githubusercontent.com/528072/56844152-5baa6e80-6871-11e9-993f-1de2744accc9.png">

**Comment by DrXyzzy** [comment]
- [ ] color picker does not show color or pop up native color picker with Safari - Classic notebook does the same thing

CoCalc with Chrome (native color picker pops up when you click the color swatch):

![chrome-color-picker](https://user-images.githubusercontent.com/528072/56844306-f73cde80-6873-11e9-806c-d16eb8bbda6a.png)

CoCalc with Safari:

<img width="344" alt="cocalc-color-picker" src="https://user-images.githubusercontent.com/528072/56844310-0459cd80-6874-11e9-95a9-ac295419ffaa.png">

Classical Jupyter with Safari:

<img width="443" alt="classic-color-picker" src="https://user-images.githubusercontent.com/528072/56844313-10458f80-6874-11e9-9caf-58a9a6a13ea8.png">

**Comment by DrXyzzy** [comment]
- [ ] another issue with date picker: the widget does not show up with Safari - like the color picker, this is a [missing feature in Safari](https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari)

**Comment by DrXyzzy** [comment]
- [ ] Box items are displayed vertically instead of horizontally:

CoCalc:

![cocalc-box](https://user-images.githubusercontent.com/528072/56844557-be9f0400-6877-11e9-9992-3d48b1d0cac1.png)

Classical:

![classic-box](https://user-images.githubusercontent.com/528072/56844559-c494e500-6877-11e9-8ec5-dedfb94a85bc.png)

**Comment by haraldschilly** [comment]
I found a fun one, that's the example in the event chapter, about linking widgets and setting continuous update. This breaks with two open notebooks, and is clearly a sign of the sync mechanism fighting back whatever delay mechanism is happening (I think the second slider is debounced in some way). The way to trigger it is to move the second slider. The gif below looks less dramatic than in reality due to dropped frames. The jitter is maybe  5 to 10 movements per second...

```
import ipywidgets as widgets

a = widgets.IntSlider(description="Delayed", continuous_update=False)
b = widgets.IntText(description="Delayed", continuous_update=False)
c = widgets.IntSlider(description="Continuous", continuous_update=True)
d = widgets.IntText(description="Continuous", continuous_update=True)

widgets.link((a, 'value'), (b, 'value'))
widgets.link((a, 'value'), (c, 'value'))
widgets.link((a, 'value'), (d, 'value'))
widgets.VBox([a,b,c,d])
```

![cocalc-ipywidgets-continuous-upgrade-issue](https://user-images.githubusercontent.com/207405/56847023-79f68580-68d6-11e9-8cf7-31b49af48ef4.gif)

**Comment by ruhanprasad** [comment]
Layout of Box widgets cannot be changed.  Box widgets with default parameters work, but changing their Layout (i.e. height, width, etc.) is not interpreted in Cocalc.  This issue is not present with most other widgets such as Buttons, sliders, and text boxes.  I have attached screenshots showing how the ipywidgets should work in classic JupyterLab and how they appear in Cocalc.  The kernel that was used in Cocalc was Python 3 (Anaconda5).  

Working widgets in JupyterLab:

<img width="1255" alt="Screen Shot 2019-08-01 at 10 15 24 PM" src="https://user-images.githubusercontent.com/52712386/62339662-cdb2d500-b4aa-11e9-900f-c2ff411a04ed.png">

Widgets in Cocalc:

<img width="1608" alt="Screen Shot 2019-08-01 at 10 14 54 PM" src="https://user-images.githubusercontent.com/52712386/62339673-dc00f100-b4aa-11e9-80db-270d5b591c34.png">

**Comment by williamstein** [comment]
> I found a fun one, that's the example in the event chapter, about linking widgets and setting continuous update.

This one works fine now.  

Also we now literally use exactly the latest upstream Lumino/ipywidgets renders for rendering absolutely everything, instead of custom ones I wrote.  This fixes all these bugs, except possibly anything caused by some weird CSS issues (I'm not aware of anything left that I didn't already fix).  Closing this.
