### ISSUE TITLE
after starting juno in iPad pro, trying to open a stopped project first takes you back to sign-in

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3826]
I tested Juno just now on an iPad Pro. Here's what happens:

## case 1 - works ok if I open a running project first
1. If Juno is running, start a new test run by stopping Juno: hit Home button twice, then swipe Juno app up to stop it.
1. Open Juno Servers list and choose COCALC.
1. Get a list of projects.
1. Choose a running project. It opens and I can use it.
1. Go back to COCALC project list and choose a stopped project. It eventually opens and I can use it.

## case 2 - problem if I try to open a stopped project first
1. Start a new test run by stopping Juno: hit Home button twice, then swipe Juno app up to stop it.
1. Open Juno Servers list and choose COCALC.
1. Get a list of projects.
1. Choose a *stopped* project. Juno goes through about 5 iterations of trying to connect, then bounces me back to the CoCalc API Key Access sign-in screen shown below. At this point, I can't use Juno with CoCalc until I sign in again.

![juno-sign-in](https://user-images.githubusercontent.com/528072/57721393-ac7bde80-7649-11e9-99df-795a3dde26da.png)

**Comment by navoshta** [comment]
Responding to @williamstein's comments in #3817:

> What's the cookie situation initially as Juno signs in? What's the expiration time on remember_me?

When user signs in, all cookies seem to be set correctly: it has `remember_me` with expiration set 6 months from now, and `has_remember_me` expiring 1 month from now, among other CoCalc specific cookies.

> Can you at least change Juno to check whether or not the user is signed in, and if not, redirect the user to sign in again? No matter what, you'll need to do that, since a user might click "Sign out everywhere" from the browser.

Juno does this now, which is why user is eventually redirected to the login page after a few failed attempts to start a project — for instance, this happened in @DrXyzzy's **case 2** above. Ideally I want to know this before user tries starting it though, is there a reliable way to tell if user is signed in?

I've investigated further based on @DrXyzzy's findings, and it seems that when the app is restarted, which forces iOS to wipe session cookies, CoCalc no longer seems to find user session. The cookies that CoCalc sets during login, and which are marked as session-only, are `cocalc_version`, `SMCSERVERID3` and `connect.sid`. Is there any chance one of these cookies is required for session to be valid?

**Comment by williamstein** [comment]
> Is there any chance one of these cookies is required for session to be valid?

Yes.  If cocalc_version is not set, then client will definitely be rejected.  Try clearing it in a normal browser session and you'll see that.   So the root cause of your problem is that cocalc_version isn't being updated.  I think that explains everything. 

I'm ok with making cocalc_version not session only, since it's a nondecreasing number.  Let me give that a shot and update this issue when it's done.

**Comment by williamstein** [comment]
(that close was automatic)

**Comment by williamstein** [comment]
The fix is live -- please test now.

**Comment by DrXyzzy** [comment]
Works. Case 2 above no longer times out and returns to sign-in. Selecting a stopped project first after starting Juno takes maybe 20 seconds to connect, then the project is open in Juno and running.

**Comment by navoshta** [comment]
Yep, I can confirm it all works as expected now — thanks @williamstein and @DrXyzzy!
