### ISSUE TITLE
Haskell syntax highlighting only works in Classic Jupyter

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3887]
Reported by Ki Yung Ahn.

Neither CoCalc Jupyter notebook nor the JupyterLab notebook highlights Haskell code when running Haskell kernel.  Syntax highlighting only works in the Classic Jupyter, viewed either by selecting `File` > `Switch to classical notebook...` or by launching Plain Jupyter Server from Project settings.

To view the bug, create a .ipynb file, set kernel to Haskell, and put the following in a code cell:
```
import System.Info

do
    print os
    print arch
    print compilerName
    print compilerVersion
```

Note that syntax highlighting is only seen as noted.

Confirmed with Chrome Version 75.0.3770.80 (Official Build) and Safari 12.0.3 (14606.4.5).

During testing, I noticed that the Haskell kernel stopped and would not restart. This is a known issue, with workarounds reported: #2820

**Comment by williamstein** [comment]
Haskell gets highlighted fine in CoCalc Jupyter:

![image](https://user-images.githubusercontent.com/1276278/59296290-6f037480-8c3a-11e9-943e-a47880b2928d.png)

It's possible the person reporting this actually hit https://github.com/sagemathinc/cocalc/issues/3657, which is still open.

Haskell highlighting not working in JupyterLab should probably go in the JupyterLab issue tracker, not ours.  (And also be tested with an independent JupyterLab install -- maybe it's just their choice of which codemirror languages to support -- I don't know...)

**Comment by williamstein** [comment]
Maybe it's only highlighting for me since that's left over from the previous kernel.  Highlighting doesn't work until the kernel itself actually works, since the kernel reports the highlighting mode. I bet if the kernel were to actually work, then JupyterLab would also show highlighting.

This does sort of seem to work:

![image](https://user-images.githubusercontent.com/1276278/59297050-32387d00-8c3c-11e9-890d-9b02b10f9693.png)

My opinion: The Haskell kernel is completely broken, and we should remove it immediately.  Maybe we can support Haskell via a new custom image, but that's it.

**Comment by DrXyzzy** [comment]
> the kernel reports the highlighting mode

I bet that is the problem. I can reproduce the missing highlighting reliably by the following process, which also incidentally shows how broken the Haskell kernel is:

1. Open Jupyterlab.
1. Click the Haskell button in the launcher - usually top row.
1. Rename the notebook to "ht01.ipynb" or such.
1. Paste the following into the first compute cell:
    ```
    import System.Info
    do
        print os
        print arch
        print compilerName
        print compilerVersion
    ```
1. Wait for the kernel to die, shown by "No Kernel!" at upper right in the notebook.
1. Click the "Restart the Kernel" button (refresh icon) and click Run. No output is produced.
1. Wait until you see "No Kernel!" again.
1. Close the notebook tab in JupyterLab.
1. Go back to the CoCalc Files tab and open the test notebook there.
1. Most of the time, highlighting is absent at this point. If it is visible, close the tab for the notebook and reopen it, and it will be gone.
1. Note that syntax highlighting is visible in TimeTravel view, even when it's not visible in the .ipynb tab.

**Comment by haraldschilly** [comment]
I don't agree that the kernel is broken. It needs a lot of resources, but once it is there it works fine for me.

**Comment by williamstein** [comment]
> I don't agree that the kernel is broken. It needs a lot of resources, but once it is there it works fine for me.

OK, so what we really need to do is better detect when a kernel fails to start due to lack of resources, inform the user of this, and suggest a project restart or other action?  That's for another ticket, and I've changed the title back.

Regarding syntax highlighting, since the kernel list is pretty stable, we should just add a kernel --> syntax highlighting mode mapping, so that highlighting always works (for at least our standard kernels), even if the backend kernel doesn't provide proper information.  This is a good idea anyways, since it is faster and likely very easy to implement.  I'll make a new ticket for this.  https://github.com/sagemathinc/cocalc/issues/3890

**Comment by haraldschilly** [comment]
ad 1: yes, e.g. reporting back the error when a startup failed would be good, etc. this is very similar to julia kernels, which might also fail due to lack of resources.

ad 2: we could add the codemirror mode directly to the kernel.json file, e.g. `metadata: { cocalc: { cm_mode : "..."}}}` and firmly adhere to that information and only fall back to other means of deriving the cm_mode, when this field isn't available.

**Comment by williamstein** [comment]
https://github.com/sagemathinc/cocalc/pull/3889 fixes this

**Comment by williamstein** [comment]
> ad 2: we could add the codemirror mode directly to the kernel.json file, e.g. metadata: { cocalc: { cm_mode : "..."}}} and firmly adhere to that information and only fall back to other means of deriving the cm_mode, when this field isn't available.

That's definitely not how I would do this.   We have pretty good heuristics for cm modes based on various information (e.g., as we use for the Format button).   I think whatever is done for #3890 should be similar to that and entirely in the frontend.  Then new random user kernels also may benefit, and the kernels in cocalc-docker or somewhere else don't all need to have some "secret metadata" set in them.
