### ISSUE TITLE
Historical CoCalc Usage Statistics info plots are not displaying

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3891]
Reported by c.d. mclean, with:
Chrome Version 75.0.3770.80 (Official Build) (64-bit) -Incognito 
Firefox 67.0.1 (64-bit) -Private

Also seen on macOS 10.14.3
 with Chrome 75.0.3770.80 (Official Build) (64-bit), Firefox 67.0.2 (64-bit), and Safari 12.0.3 (14606.4.5).

1. Log into CoCalc as non-admin.
1. Click "i CoCalc" Information in the top bar.
1. Scroll down to the Statistics section and click `Historical CoCalc Usage Statistics...`.
1. Note that plots show as broken image links, but "Recent Data" table renders correctly.

<img width="604" alt="missing-usage-plots" src="https://user-images.githubusercontent.com/528072/59401894-e849b700-8d61-11e9-9bf7-0d956cabd0ef.png">

**Comment by haraldschilly** [comment]
interesting, opening that link in incognito mode, just tells me about a version problem. some cookie seems to be required. in any case, I suggest to change the link to https://share.cocalc.com/share/7561f68d-3d97-4530-b97e-68af2fb4ed13/stats.html?viewer=embed

**Comment by williamstein** [comment]
> I suggest to change the link to

That will not work **currently**, because the share server is not updated just because files change in the project.  The update *only* happens when (1) there is *user activity* to trigger a check for changes, and (2) files actually change.

Since I'm working on share server stuff anyways, I should just change this behavior, e.g., make (1) happen periodically anyways while the project is running, e.g., once very 15 minutes.  Then switching to the share server link will work fine.

**Comment by haraldschilly** [comment]
ahh! good point, I forgot about that. pushing changes every 15 mins, or well, maybe making automatic updates configurable, sounds good. we should collect all these ideas.

**Comment by williamstein** [comment]
No longer public.
