### ISSUE TITLE
with safari, display of uploaded files can obscure closing X at upper right

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3923]
Seen with Safari 12.0.3 on macOS 10.14.3.

NOT seen with Chrome on same OS.

1. Open Files list.
1. Click `Upload` at upper right.
1. ~~Upload 10 or so files, enough to fill the top row with confirming images.~~ Upload 1 or more files. It's not necessary to fill the top row to see the bug.
1. Note that `X` at upper right to close the pane of images is obscured.

<img width="935" alt="safari-upload-no-X" src="https://user-images.githubusercontent.com/528072/60150728-7df03800-979f-11e9-98b0-3644f0b16165.png">

**Comment by haraldschilly** [comment]
Interesting. I have the feeling this is a dup of #3904 ... it looks different, but this "check all" button on top of the create files dialog is the same layout issue: some line wrapping isn't happening, hence it is on top of each other.

it's really interesting that you see this with safari, because I thought what I saw is a beta-issue of chrome.

next time this happens to me, I'll try to closer inspect how the divs are composed to do the layout.

**Comment by slel** [comment]
This can also happen with Opera on macOS 10.10.5.

![scr-2019-06-15T231834Z](https://user-images.githubusercontent.com/2786973/60177462-3e663200-9819-11e9-9bed-06c1c8a6313c.png)

**Comment by haraldschilly** [comment]
@DrXyzzy  @slel can you please check again? Last week I changed how the nested layout is done on that files page.  I've not looked into opera at all, so that will be a good thing to check as well.

**Comment by williamstein** [comment]
This now works fine on Desktop safari.
