### ISSUE TITLE
filter project log by type

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3955]
There are many entries in the project log and it is hard to find specific aspects. This ticket is about adding some UI (buttons?) to filter the entries. e.g. to only show all file actions (or just the ones about copying a file), or only the `'set'` actions for changing title/description, etc.

**Comment by williamstein** [comment]
I think the solution is typing in the search box the name of the action.  This works.  If there is a specific case where it doesn't, or where an alias is needed, add that to the search.  

Right now the code that defines the text search is here:

https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/project/history/types.ts#L151

> "e.g. to only show all file actions (or just the ones about copying a file), or only the 'set' actions for changing title/description, etc."

searching for "copied" and "renamed" do the above for files.  Searching for "set" does it for titles.  It's of course not perfect, since there's a little overlap (e.g., if you had a file named set it would get mixed in), but it's minimal.  

Anyway, I'm not convinced it is worth the extra weight on the UI to add buttons / menus for this.  If we ever do, then they should be hidden under an advanced setting (similar to google search's non plain text search option).
