### ISSUE TITLE
cannot scroll up to create project with custom software image

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4054]
Seen on MacOS 10.14.3 with
* Chrome Version 76.0.3809.100 (Official Build) (64-bit)
* Safari Version 12.0.3 (14606.4.5)

1. Click `Projects`.
1. Click `Create New Project...`.
1. Enter a project title, say "CSE-foo".
1. Click `Advanced...`.
1. If `Default` is selected, note the position of the green `Create Project` button.
1. Click `Custom beta:...`.
1. Observe that a list of custom sofware environments appears and that the `Create Project` button is below the list of CSEs.
1. Note that the part of the page that contains `Create Project` does not scroll. If your screen is not tall enough to show the button, it's out of reach.
1. Workaround is to shrink text size until `Create Project` is visible.

See also: #4053, #4052.

**Comment by haraldschilly** [comment]
this is clearly broken due to changing the list of projects to use that windowed list. here is a screenshot of an old dev version, back in end of may. I'll try to fix this.

![Screenshot from 2019-08-31 09-59-52](https://user-images.githubusercontent.com/207405/64061113-25417f00-cbd6-11e9-83ef-aff39df1bfa2.png)
