### ISSUE TITLE
display whether student has paid to upgrade in the student list in course file

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4090]
This will be helpful in resolving subscription issues. Instructor will know if students are on the one-time plan without needing to check with CoCalc support.

**Comment by williamstein** [comment]
In addition to this, I wonder if we should take a completely different approach.  If a user goes to the subscription page and they have a non-upgraded project that is part of a course (and no active subscription yet), they should always get a clear option to buy the $14 one time upgrade for that project, even if the instructor has not selected student pay...

It would be easy to do the above, and if we do so, it would prevent all the recent problems we had with students buying the wrong plan...

Harald or I could also do a db query and quickly figure out the situation with all students in a course, rather than relying on the students or instructor to do something.

**Comment by DrXyzzy** [comment]
Putting the one-time option in the subscription page would eliminate much confusion and rework. It has always seemed odd to have the one-time option available only in the student project banner.

OTOH, I think there was one instance recently of an instructor adding students to a course before subscribing.

**Comment by williamstein** [comment]
> OTOH, I think there was one instance recently of an instructor adding students to a course before subscribing.

Yes, we would have to prevent that...

Maybe just flat out require the instructor to explicitly choose between: [ ] students pay, [ ] instructor will eventually pay..., [ ] trial for free....  whenever they open the course.   Then take this information into account when communicating with students.

**Comment by DrXyzzy** [comment]
+1 to the explicit 3-way choice: 

> [ ] students pay, [ ] instructor will eventually pay..., [ ] trial for free....

**Comment by williamstein** [comment]
this is very clear already, since the hosting type of the student project is listed....
