### ISSUE TITLE
admin: project settings do not load

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4137]
as admin, opening a project of someone else, the settings page doesn't load. workaround is impersonation. must be a fallout of type-scripting this recently.

![Screenshot from 2019-10-08 10-34-48](https://user-images.githubusercontent.com/207405/66380264-5c663580-e9b7-11e9-940a-b7c62bb2431e.png)

**Comment by williamstein** [comment]
Root cause: @j3 changed a `null` into an `undefined` with no comment. This wasn't caused by decaffeinate, which leaves it as null.  Why the change?  I want to make sure @j3 understands what's going on here and why this totally broke stuff, so it doesn't happen with future conversion from coffeescript...  The reason is because we're constructing a query that will be json'd and sent over the wire, and null behaves VERY differently than undefined for the purposes of JSON.  Look:
```
JSON.stringify({a:undefined})
"{}"
JSON.stringify({a:null})
"{"a":null}"
```
For our query system, `null` means "fill in the value".  The nice way to address this would be to introduce something like a Javascript "symbol"... but that would greatly complicate JSON'ing, I worry.
