### ISSUE TITLE
live update jupyter's introspection frame when cursor moves

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4208]
It's incredible helpful for me to see the API documentation for a class or function when I code something up. In particular, I would like that the introspection frame updates whenever I place the cursor on a token. There could also be a toggle button to enable/disable this live update behavior.

What I try to avoid is having to add questionmarks and so on.

Below is a short screencast how Jupyter Lab's contextual help frame works. It updates all the time.

![Peek 2019-11-03 18-29](https://user-images.githubusercontent.com/207405/68089360-653c1100-fe68-11e9-9188-547087297551.gif)

**Comment by williamstein** [comment]
In the current version of JupyterLab I can't figure out how to even show the introspection frame anymore?  It seems like it was completely eliminated in favor of a popup, which of course goes away when you move the cursor.  In any case, after 15 minutes of poking around and googling, I can't even figure out how to show that frame, if it still exists.

I also don't agree on this design.  I like to pop up introspection, then type code, and if the frame constantly updated, it would make the docs I'm trying to look at disappear.

I'm closing this due to lack of interest and activity and also it not being a jupyterlab compat issue anymore.    If you're interested in implementing this, e.g, as an option -- maybe the introspect frame has a checkbox to make it autoupdate to wherever the cursor is -- then open this again.
