### ISSUE TITLE
Improvements to drop-down menu for multi-file latex editing

### ISSUE THREAD

**Issue by crockeea** [sagemathinc/cocalc#4224]
#904 introduced the ability for native multi-file TeX editing. This feature introduced a drop-down list of files, but there are a few problems with the UI.

First, it doesn't seem to extend past one "frame" horizontally. This means that long file paths are truncated. Second, it seems to have a limited height, and no scroll bar. Next, I think it makes sense to *only* show .tex files in this list, but many TeX temporary files are included (*.bbl, *.out, *.w18, *.pygstyle).

Note in the source file that I'm including "minibatch", but minibatch.tex isn't showing in the drop-down menu, and there's no scroll bar to find it. The list is pretty cluttered by non-.tex files, making it hard to find the one you want.

I've included an image showing the problem. I'm using Chrome on Windows, running my own version of the server from the no-agpl docker image.

![cocalc](https://user-images.githubusercontent.com/4899463/68509918-0f2fea80-0227-11ea-9133-bce6bdfa0261.png)

**Comment by williamstein** [comment]
Can you provide source files that replicate the issues that you describe here?  For example:

> Note in the source file that I'm including "minibatch", but minibatch.tex isn't showing in the drop-down menu, and there's no scroll bar to find it. 

Right now the files listed in the dropdown are the ones that are processed by latex (they are parsed out of the latex build log).   If minibatch.tex isn't there, then maybe it isn't processed for some reason?    We're certainly not going to parse the actual tex file for \include statements, since that would be pretty difficult to use (e.g., what if one file includes another file that includes other files...?)   

Having an extra option to open any file at all (or add a new one) isn't implemented yet.  That said, you can open a terminal frame, then use the "open" command on the command line to open any file at all (and just ignore the dropdown list).

> First, it doesn't seem to extend past one "frame" horizontally. 

I don't know how to solve this problem, unfortunately.   Perhaps some CSS guru can inspect the DOM and figure it out.

**Comment by crockeea** [comment]
`minibatch.tex` *is* in the list, it's just not visible or easily accessible. If I click on the drop-down menu and use the down-arrow key, I can scroll down the list and minibatch appears. It seems like a UI bug.

**Comment by williamstein** [comment]
Thanks for the clarification. I just looked into this and I'm pushing the following changes to master:

- only show .tex files in the dropdown
- I rewrote the dropdown using the Antd UI framework, and it eliminates these UI bugs involving dropdowns in the frame.  We are in the process of switching from Bootstrap to Antd everywhere in CoCalc anyways, so this change fits our roadmap.

![image](https://user-images.githubusercontent.com/1276278/68534220-9b551700-02e6-11ea-8ee5-baa9351e4fed.png)

Will be live on cocalc.com very soon, and on the Docker image in a week.

It would be helpful if you could test cocalc.com to make sure that this works for your use case, and if not, let us know before we cut the next Docker image.
