### ISSUE TITLE
sagews: unable to play wav file in markdown

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4240]
Given you have a soundfile like `sound.wav` in the same directory as your sagews file:

This markdown snippet shows the html5 audio player, but the URL to the file isn't converted to point to the raw server and hence it can't play the file.

```
%md
<audio controls=true src="sound.wav"/>
```

**Comment by williamstein** [comment]
Tagging this as wontfix, because it will be fixed indirectly by creating a sage worksheet style mode (and kernel) for Jupyter notebooks. That will be https://github.com/sagemathinc/cocalc/issues/6374.

In Jupyter exactly the above does work fine in a markdown cell.  Confirm with a sound file from https://www2.cs.uic.edu/~i101/SoundFiles/
