### ISSUE TITLE
files: creating file in search box must be missing "capabilities"

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4264]
today I noticed that – despite running a project with all capabilities – the panel for creating a new file when I search for a file that doesn't exist, only shows the always working file types. the +new panel and the dropdown still show everything. expected: show all available file types as well.

![Screenshot from 2019-12-05 11-24-32](https://user-images.githubusercontent.com/207405/70227019-298bb400-1752-11ea-82d8-067404dcc9de.png)

**Comment by williamstein** [comment]
Wow, this is a *huge* bug.   Glad you found it.

**Comment by haraldschilly** [comment]
I haven't checked the code at all. At some point in the past the buttons did show up, but now it's either gone or a property isn't set.

**Comment by williamstein** [comment]
> I haven't checked the code at all. At some point in the past the buttons did show up, but now it's either gone or a property isn't set.

I'll fix it.  This is the code that @johnjeng recently rewrote in Typescript and refactored, and he likely introduced this bug in that refactor (and I missed it in review).

**Comment by williamstein** [comment]
@johnjeng refactored the code in src/smc-webapp/project/explorer/explorer.tsx from cjsx to typescript.  It used to have a meaningful variable "name" in scope, which is now **GONE** due to how reduxProps now works.  But other code assumed it was still there. Unfortunately, restructuring this did not get caught by typescript because somehow there is still something called "name" in the global scope (no idea why or what -- except it is an empty string).   Anyways, using this.props.name fixes the problem.  @johnjeng please notice this.
