### ISSUE TITLE
add a collaborative "whiteboard"

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4283]
this ticket is about adding a new editor for a collaborative whiteboard. the main goal is to take notes with a digital pen to draw (free hand, shapes, etc.) and later share this. Regarding the whiteboard, a similar app is  https://miro.com or Google's Jamboard

Requested by: Dmitrij Moreinis

**Comment by dimpase** [comment]
+1

**Comment by dimpase** [comment]
preferably with a capacity to type in TeX, too

**Comment by williamstein** [comment]
There are some open sourced projects from like 5 years ago that do this, which may be useful for reference and inspiration:

- https://github.com/lovasoa/whitebophir
- https://github.com/spacedeck/spacedeck-open

@dimpase I appreciate Dima pointing out that what **we** do for CoCalc should maximally leverage our unique strengths.  For example, we should support latex, markdown, embedding computations (using a Jupyter kernel), chat.

@haraldschilly 
> the main goal is to take notes with a digital pen to draw (free hand, shapes, etc.) and later share this. 

It would be very, very helpful to clarify the main goals.  Why do the above?   What motivated you to make this issue.   My random ideas:

- brainstorming ideas, e.g., for research or development  and sketching out architecture of systems
- slides for a classroom style presentation
- an online way to draw and edit svg's (probably way too hard since we would want to parse svg).
- a way to grade student solutions (by attaching little sketches with a pen to particular points in any document).
- a non-linear UI for interacting with Jupyter kernels (like MathCad)

Harald you wrote "main goal is to take notes", so are you imagining somebody in a lecture **taking notes** inside a cocalc project?  Why would they do that, rather than using the myriad of vastly superior note-taking applications?  E.g., on an ipad there is "$5 app" that also records the audio of the lecture and syncs it with the notes you draw on the screen, organizing everything, etc., (and it was really mature already 5 years ago).  How do we compete with that?

**Comment by williamstein** [comment]
REQUESTED BY: Oliver Pechenik

> "The main thing we've been missing in CoCalc is that the chat rooms don't have a shared whiteboard feature. There are some other video conferencing systems that have this and it is quite useful for math because everyone can sketch diagrams collaboratively. We've had to open separate software when we needed to do this, but it would be great to have it all under one CoCalc roof."

**Comment by dimpase** [comment]
I have been playing a bit with https://idroo.com/

**Comment by slel** [comment]
Possibly related:

- jupyterlab-drawio: a diagram editor for JupyterLab
  https://blog.jupyter.org/a-diagram-editor-for-jupyterlab-a254121ff919

**Comment by mforbes** [comment]
What I would love is a whiteboard for teaching: I would like to be able to deliver online lectures via Jitsi (or Zoom), working down a column as if it were an infinitely tall chalkboard, while allowing students to work off to the side, asking questions, doing calculations, etc.  I tried [spacedeck-open](https://github.com/spacedeck/spacedeck-open) but it did not seem to support interactive editing. Inserting other content would be great, but just a place to draw would be fantastic.  

Many of the open-source web-based platforms don't work with my surface (pen input becomes a bunch of dots wherever the pen hits the screen, not lines).  The commercial versions seem to work.

**Comment by slel** [comment]
OpenBoard: http://www.openboard.ch/index.en.html

**Comment by williamstein** [comment]
https://news.ycombinator.com/item?id=24676125

**Comment by slel** [comment]
Tableaunoir: https://github.com/tableaunoir/tableaunoir

**Comment by slel** [comment]
Related, mentioned at https://trac.sagemath.org/ticket/30537#comment:32

> `tableaunoirxcas` -- a blackboard for online teaching
> where you can insert Xcas, MicroPython or Javascript magnets
> - home:
>   https://www-fourier.univ-grenoble-alpes.fr/~parisse/tableaunoirxcas/index.html
> - example:
>   https://www-fourier.univ-grenoble-alpes.fr/~parisse/tableaunoirxcas/#mat309/myblackboard.tableaunoir

**Comment by williamstein** [comment]
Related JupyterLab issue: https://github.com/jupyterlab/jupyterlab/issues/9194

**Comment by williamstein** [comment]
This is now merged into master and will be live in production soon: https://github.com/sagemathinc/cocalc/pull/5674

It's still definitely beta: expect some bugs and UI issues, which will get addressed as reported.  I also have a very long todo list still, but nothing listed as **absolute blocker**.  I think this is now at least "useful" and well worth it for people to try out.
