### ISSUE TITLE
unable to remove license key

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4356]
1. add valid license key to a project → works
2. how to remove it?

I tried to test a key, but now it's sticky with the project and always upgrading it.

Expected: either a delete button and/or deleting the whole content and clicking save should get rid of it.

Also, just deleting + save doesn't throw an error, like it does with an invalid uuid.

What I ended up doing is generating a fresh uuid v4 and replaced what's there.

**Comment by williamstein** [comment]
I'm closing this because (1) deleting and save does remove it properly (it can take a few seconds, and you probably didn't wait -- I just tested this many times), and (2) this is only meant as a very quick temporary UI, mainly for testing and for some key users to deal with edge cases while the actual UI for managing allocation of keys is implemented.
