### ISSUE TITLE
site license upgrades seem to disappear when course file is created

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4381]
Tested with Chrome in production.
1. Create a standard plan site license with run limit of 10.
1. Create a new non-admin account with no upgrades.
1. Create a new project in the test account and wait for it to start.
1. Open project Settings, click "Upgrade using a license key", and add the key for the site license just created, being sure to click Save.
1. See red confirmation message:
    ```
    ...
    Currently providing no upgrades - you probably need to restart
    your project (it's also possible that the license limit has been reached)
    ```
1. Still in Settings, click "Restart Project..." and "Yes, restart project".
1. Note that shortly after the "Starting..." message appears under "Project control", the upgrades for Member Hosting, Internet Access, etc. appear to be applied and the red warning is replaced with green status:
    ```
    ...
    Currently providing the following upgrades:
    Member Hosting 1 hosting upgrade
    Internet Access 1 internet upgrade
    Idle Timeout 6 hours
    Shared RAM 1000 MB
    Shared CPU 0.5 cores
    ```
1. Wait for the project to restart.
1. In Files view, click +New, then enter filename "foo", and click "Manage a course".
1. Wait for course file to open.
1. Observe that about a second after the "Add students to course" prompt appears in a blue box, a banner appears at the top of the browser tab saying:
    ```
    Upgrade this project. It is on an unpaid trial server and has no internet access.
    Expect poor performance and no email notifications.
    ```
1. Open project Settings and see that upgrades are removed.
1. Click "Upgrade using a license key" and see that the license key field is blank.

**Comment by williamstein** [comment]
I realize what is happening here.    In
```
12. Open project Settings and see that upgrades are removed.
```
the client **thinks** the upgrades are removed but actually they are still there.    The project does have network access and is upgraded, but it says it isn't to the user, which is obviously confusing.  

Regarding:
```
13. Click "Upgrade using a license key" and see that the license key field is blank.
```
That is *always* blank because it is a text input field.  

Also regarding:
```
5. See red confirmation message:
```
that is NOT a confirmation message.  It is a box that indicates there is a site license code set for this project, and give the status of that license.  It'll be there any time you open settings until you completely remove the license.

**Comment by williamstein** [comment]
OK, I looked at the actual code and the above is 100% intentional in the code:
```
      if (site_license_id) {
        await actions.add_site_license_to_project(
          course_project_id,
          site_license_id
        );
      } else {
        // ensure no license set
        await actions.remove_site_license_from_project(course_project_id);
      }
```
The idea was that you would *only* enter the license key in the course file, and that would then ensure that the project is upgraded.  And if there is no key, it would make sure it isn't.  That latter case could be confusing, I see now, so I'll just leave the license in place in all cases.
