### ISSUE TITLE
jupyter: make altair work with coalc's jupyter notebook

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4468]
this code inserts some html, but nothing shows up. something similar like that did work in the past. if I copy/paste the inserted code (via the debug console) into an html file, it seems to work. so, maybe what this needs is to wrap it in an iframe?

```
import altair as alt
alt.renderers.enable('html')

import pandas as pd

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

alt.Chart(source).mark_bar().encode(x='a', y='b')
```

![Screenshot from 2020-03-25 13-44-26](https://user-images.githubusercontent.com/207405/77537745-e428f900-6e9e-11ea-8c28-98bba96406d5.png)

**Comment by williamstein** [comment]
> Is Altair supported on CoCalc Jupyter Notebook? 

No, it definitely won't work because it contains a bunch of output html that is full of <script type=\"text/javascript\"> tags, and we don't run those in cocalc-jupyter, for security reasons.  Other libraries like plotly solve this problem using an iframe, which is what altair should do (it's much more secure).  Alternatively, CoCalc could just render all html in an iframe, though that has a number of drawbacks as well.   

I briefly checked [altairs github issue](https://github.com/altair-viz/altair/issues?q=is%3Aissue+iframe) and it seems like using an iframe for rendering isn't even on their roadmap or something they've worried about.

For now you will have to Jupyter Classic or JupyterLab to use Altair in CoCalc.

**Comment by williamstein** [comment]
Altair now works in cocalc 🤷
