### ISSUE TITLE
jupyter/sage: @interact inputs shouldn't eval after keystrokes

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4471]
setup: firefox, cocalc's juypter notebook, kernel "sage 9.0/8.9" and this cell:

```
@interact
def f(a="1+1"):
    print(eval(a))
```

problem: when changing the input, e.g. just to `1+`, it triggers an error. with larger code blocks this is quite annoying …

expected: only evaluate after you're ready with editing the input box and hitting return

(in sage worksheets it delays until after hitting return as well, as far as I can tell)

**Comment by williamstein** [comment]
I'm closing this because it is the official behavior of Jupyter widgets.

The correct way to accomplish what you want is to use [the auto_update option](https://doc.sagemath.org/html/en/reference/repl/sage/repl/ipython_kernel/interact.html#module-sage.repl.ipython_kernel.interact): 
```
@interact
def f(a="1+1", auto_update=False):
    print(eval(a))
```


(Side comment: when reporting an issue with cocalc-jupyter, it is always considerate to check to see what the status is with jupyter classic.)
