### ISSUE TITLE
improve UI for undeleting students

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4484]
user feedback: 

> the discoverability of this button is very poor. I would have expected it somewhere above the list of students.

and more general, i.e. when searching/adding  a deleted student

>  But even more important, it would have been great to have the button to revert the delete status of a student when I search for him and cocacl tells me that it is already added or deleted.

**Comment by arnaudlegout** [comment]
To complement my feedback. 

When you are in your .course/Students and you seach for a name of email address to add a student. If it turns out that the student you search for has been deleted before, the message is not specific

`Already added (or deleted) student or project collaborator:`

Here I would have expected the following message

`This user has been deleted from the course. Do you want to add it back? [undelete]` 

when [undelete] is a button to undelete this user. 

In case multiple users can be undeleted, there might be an [undelete all] button

**Comment by williamstein** [comment]
@arnaudlegout that's #4061
