### ISSUE TITLE
deleting a student from a course does not remove them from collaborators on the shared project for the course

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#4495]
1. create a course with at least one student
1. create a shared project
1. open the shared project and verify that the student is listed as a collaborator
1. in the Students tab, click on student name and then click Delete to remove the student from the course
1. open shared project again and verify that the deleted student is still a collaborator on the shared project
1. restarting the shared project and closing/reopening the course file do not cause the deleted student to be removed as collaborator on the shared project

Reported by Arnaud Legout.

**Comment by novoselt** [comment]
I've tried to test this, but the shared project of this course https://cocalc.com/projects/35dd0d93-f702-4bd4-90dc-f5a3c2117ba2/files/tests/Course%20Management.course has no collaborators attached at all. I've deleted it and created again - same story.

**Comment by williamstein** [comment]
> I've deleted it and created again - same story.

The real problem is that you have to explicitly do "Reconfigure all projects" after creating the shared project.  That should be automatic but isn't. 

If you have "Allow arbitrary collaborators" then the student is not removed. If you uncheck that box, then reconfigure all projects, then the deleted student *is* removed.

I'm making this unclear.  However, it's definitely a bug having to manually do "Reconfigure all projects" after creating the shared project.
