### ISSUE TITLE
continue where you left off

### ISSUE THREAD

**Issue by mkarakoc** [sagemathinc/cocalc#450]
Would it be nice to have "continue where you left off" feature in SMC for project and files as in google chrome and and as in many other modern browsers for web sites?

So that one do not need to re-open every other file when reopen a project.

**Comment by williamstein** [comment]
Maybe.    However, there is a very subtle issue, because the URL you see when using SMC is the URL of the *current* document you are looking at, not of all open documents (and this is very useful).   If you copy and paste that URL into another tab, and open it, you definitely expect to see only that one document, since that's the one you just opened.   However, security and information-wise, copying and pasting the URL and opening it is completely equivalent to refreshing the current page.

**Comment by mkarakoc** [comment]
Today, there was a power outage here. Now, I have to open every single SMC file once again. I feel it would be nice but I am open any thoughts.

**Comment by williamstein** [comment]
I'm certainly not against this feature.  It's just that I currently don't exactly see how to "define" it.

**Comment by iScienceLuvr** [comment]
I would simply like to say I agree with @williamstein

**Comment by johnjeng** [comment]
A possible solution is to allow users to save their current working environment as a snapshot that they can access from user settings (or elsewhere). 
eg. Implement a button which saves the paths to all files the user currently has open. The user can then name this snapshot and can navigate back to it later. Since this could be a lot of files, the interface could gray out similar to when SMC goes on standby and a blue box would say something like "Setting up your workspace. This could take a few moments"

Comments on this idea:
- Doesn't really implement a "where you left off" feature the same as Chrome and other browsers.
- Feels a little more clunky than "where you left off" since it's not automatic.
- Does add flexibility for various sets of files if, for example, the user runs a course, does research, and has development workspaces that she would like to have quick access to.
- If a file path has since changed, the tab where the file would be should gracefully tell the user that the file was not found.
- Not sure if this would be better at the project level or if workspace snapshots would include open projects as well as project files.

**Comment by williamstein** [comment]
On Sun, Mar 27, 2016 at 5:30 PM, John Jeng <notifications@github.com> wrote:

> A possible solution is to allow users to save their current working
> environment as a snapshot that they can access from user settings (or
> elsewhere).
> eg. Implement a button which saves the paths to all files the user
> currently has open. The user can then name this snapshot and can navigate
> back to it later. Since this could be a lot of files, the interface could
> gray out similar to when SMC goes on standby and a blue box would say
> something like "Setting up your workspace. This could take a few moments"
>
> Comments on this idea:
>
>    - Doesn't really implement a "where you left off" feature the same as
>    Chrome and other browsers.
>    - Feels a little more clunky than "where you left off" since it's not
>    automatic.
>    - Does add flexibility for various sets of files if, for example, the
>    user runs a course, does research, and has development workspaces that she
>    would like to have quick access to.
>    - If a file path has since changed, the tab where the file would be
>    should gracefully tell the user that the file was not found.
>    - Not sure if this would be better at the project level or if
>    workspace snapshots would include open projects as well as project files.
>
>
I like this idea.


>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/450#issuecomment-202176699>
>



-- 
William (http://wstein.org)

**Comment by williamstein** [comment]
@timothyclemansinsea did sort of implement this in a scary way...

**Comment by timothyclemansinsea** [comment]
@williamstein what was scary about it?

**Comment by johnjeng** [comment]
I think this is sufficiently implemented. Any reservations about the current system should go in a new issue.
