### ISSUE TITLE
implement an "Open in CoCalc" badge/link

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4525]
Here's what it should basically do, but in some standard way:

Yes, though we haven't really advertised it as such yet. 

1. Create some content that is shared on https://share.cocalc.com/share/
2. Open it and you'll see a big green button labeled "Open in CoCalc with one click!"
3. Right click on the button and click copy link address, and get something like 
```
https://share.cocalc.com/app?anonymous=true&launch=share/aa502d8f25af3b6026cc1f90e5645fc3372ee0e7/Classical.sagews
```
4. That link is very similar to the link Colab provides, but for cocalc.  It's actually technically even better, since the user does NOT have to have a cocalc account at all, whereas with colab you must be signed in with a google account. 

We have a little badge:   
![image](https://user-images.githubusercontent.com/1276278/79802237-785a7480-8314-11ea-9f8f-249cf5a1d827.png)

[Internal link](https://cocalc.com/projects/92848d19-8432-46c8-ba59-2b0d9521c9f2/files/marketing/artwork/launch-cocalc-badge.svg?session=default)

**Comment by nathancarter** [comment]
For others who drop by here, this post was partially in response to an email I sent to help@cocalc.com.  Thanks for the super-fast reply, William!

This answers a lot of my questions, but not 100%.  For others who came here, the original question I asked was this:

> I noticed today that Google Colab has a feature called “Open in Colab” that lets any Jupyter Notebook on GitHub be converted easily into a link for opening that notebook on Colab and running it.  This works for only Python 2 and 3 notebooks, of course, since that’s what Colab supports. [See here for details.](https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcolab.research.google.com%2Fgithub%2Fgooglecolab%2Fcolabtools%2Fblob%2Fmaster%2Fnotebooks%2Fcolab-github-demo.ipynb&data=02%7C01%7Cncarter%40bentley.edu%7C7c0888eb9bc74857eb6a08d7e5731f31%7C9030beae3cfc4788a9e2130204ff1f10%7C0%7C0%7C637230154933098336&sdata=AIl7f7HEwMwNHVCi1VDYi2vI%2BRX1DGJJgiI%2Fobv9v6U%3D&reserved=0)  Is there any similar feature for CoCalc?

It seems from what's said above that if I have a notebook on GitHub and want to launch it in CoCalc, my workflow should be:
 1. Transfer the content to share.cocalc.com/share.  (I don't know for sure, but I think that is a manual process that involves creating a CoCalc project, uploading the file from GitHub, and then making that file public.)
 2. Find the file on share.cocalc.com/share and copy the link from there, which as far as I know is also a manual process.

I'm interested in a more automated process, if there is one.  The process I described above for Colab is literally string replacement, into a URL of the form `https://colab.research.google.com/github/USER/REPO/blob/master/PATH/FILENAME.ipynb`.  That is, Colab does the GitHub extraction for you as part of visiting that URL.

I ask because I'm creating a reference website with lots of code samples and it would be great to make code samples launchable as part of the website's build process.  Right now I could do that with Colab but only for Python 2 and 3.  If CoCalc had a similar functionality, I could support all the languages that CoCalc supports.

Thank you!

**Comment by huonw** [comment]
[We](https://github.com/stellargraph/stellargraph) are interested in a similar external-link process. For instance, we have dozens of demo jupyter notebooks, like <https://github.com/stellargraph/stellargraph/blob/a310143ff/demos/node-classification/gcn/gcn-cora-node-classification-example.ipynb>, and each of them has a pair of links at the top (and the bottom), to automatically open and execute the notebook from GitHub on Colab and also on [Binder](https://mybinder.org).

The source for those links is:

```html
<table>
  <tr>
    <td>Run the master version of this notebook:</td>
    <td>
      <a href="https://mybinder.org/v2/gh/stellargraph/stellargraph/master?urlpath=lab/tree/demos/node-classification/gcn/gcn-cora-node-classification-example.ipynb" alt="Open In Binder" target="_parent"><img src="https://mybinder.org/badge_logo.svg"/></a>
    </td>
    <td>
      <a href="https://colab.research.google.com/github/stellargraph/stellargraph/blob/master/demos/node-classification/gcn/gcn-cora-node-classification-example.ipynb" alt="Open In Colab" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg"/></a>
    </td>
  </tr>
</table>
```

As an additional constraint: we're working on a library which is required for those notebooks (as well as some other dependencies). We're happy to install when required, but we do need a way to detect this case. For Colab, we do this by checking for the `google.colab` module; is there currently a reliable way to detect executing-in-CoCalc? (Binder automatically "installs" the library, because it turns the whole repository into a docker image.)

Also, additional prior art close to this space is https://nbviewer.jupyter.org, which accepts an arbitrary URL and renders the notebook, in addition to special cases for GitHub (although rendering is not nearly as intricate as making available for execution, I'm sure).

Thanks for CoCalc, and we're excited for this if/when it is available!

**Comment by haraldschilly** [comment]
hi @huonw from stellargaph. This looks quite cool. I used it as a test for our [custom software image](https://doc.cocalc.com/software.html#custom-environments) feature. It's not 100% done, but I think you see the potential for your case. Basically it builds a docker image like mybinder does, adds some cocalc specific extras, and packages this up like other projects. You can access it by creating a new project and selecting stellargraph as the underlying software image. It will populate it with your files. Below is a screenshot for this step and then another one where I ran a notebook.

> is there currently a reliable way to detect executing-in-CoCalc

I think the best way is to check for environment variables. In particular, I think we'll never change the following one, because it's quite helpful and has a prefix in its name: `'COCALC_PROJECT_ID' in os.environ`

additional notes: I wasn't lucky with all demo notebooks. some seemed to run for long time? maybe I got impatient after a minute. Another one – `demos/spatio-temporal/gcn-lstm-LA.ipynb` – failed in the middle with: `TypeError: __init__() got an unexpected keyword argument 'lstm_layer_sizes'` … and other ones are too heavy on the memory side.

![screenshot-test cocalc com-2020 04 27-11_39_33](https://user-images.githubusercontent.com/207405/80357912-f1f5e380-887b-11ea-981c-1003bf3a65e8.png)


![2020-04-27-stellargraph-test](https://user-images.githubusercontent.com/207405/80357759-b824dd00-887b-11ea-94ef-e42e9841fc4b.png)

**Comment by huonw** [comment]
> This looks quite cool. I used it as a test for our custom software image feature. It's not 100% done, but I think you see the potential for your case. Basically it builds a docker image like mybinder does, adds some cocalc specific extras, and packages this up like other projects. You can access it by creating a new project and selecting stellargraph as the underlying software image. It will populate it with your files. 

That's awesome!

That would be perfect for us: it seems closer to the Binder workflow, which we find nicer/smoother than the Colab one. We definitely hit all of the negatives mentioned in the "Compared to the MyBinder service" section, so being able to recommend CoCalc and see those benefits would be great.

> It will populate it with your files

It looks like that current environment uses the in-develop version of StellarGraph. It would make more sense for us to use the latest release because the develop version may be somewhat broken. Is that someone we as an external project can contribute/control, easily? (Including updating the environment when we do new releases?)

> I think the best way is to check for environment variables. In particular, I think we'll never change the following one, because it's quite helpful and has a prefix in its name: 'COCALC_PROJECT_ID' in os.environ

Makes sense, although if the custom environment approach works it wouldn't be needed 👍 

> additional notes: I wasn't lucky with all demo notebooks. some seemed to run for long time? maybe I got impatient after a minute. Another one – demos/spatio-temporal/gcn-lstm-LA.ipynb – failed in the middle with: TypeError: __init__() got an unexpected keyword argument 'lstm_layer_sizes' … and other ones are too heavy on the memory side.

Yeah, some of them take a while, and that code is indeed broken at the moment. Thanks for trying them 😄

**Comment by haraldschilly** [comment]
thanks for testing!

so, this "custom software image" has a few differences. In particular, your changes to the files are stored persistently, just like with other cocalc projects. They're copied once when you create the project. Later on, there is a button to copy the files again (on top of what you already have in your project) … which picks up changes to the files if there are some. That doc page explains this a little bit.

In any case, it is possible to pin a specific version reference and well, I have to check, but also makes sense to just take the files from the subdirectory with the notebooks and not everything. Right now, I control the configuration and build it the image. There is nothing automated. In particular, we want to avoid that automatic builds fail or there are random delays. Rather, we build, check if the new image works, and then keep it stable. That was helpful for courses  as well – i.e. exactly the same software and files throughout the semester.

So, in any case, specific releases are very good :-)

Adding some options to such a "magic link" to end up in a stellargaph project shouldn't be too hard, but we didn't came around to actually do this yet.

**Comment by AllenDowney** [comment]
I would love this feature.  

I am doing this now with Jupyter notebooks that are stored on GitHub and accessible from Colab. 
 The work flow for me is good because I just push changes to GitHub.  And it works well for users who can click a link and run the notebooks.

If you are working on this feature, I volunteer to help with testing.

**Comment by williamstein** [comment]
@AllenDowney 

> I would love this feature.
> 
> I am doing this now with Jupyter notebooks that are stored on GitHub and accessible from Colab. The work flow for me is good because I just push changes to GitHub. And it works well for users who can click a link and run the notebooks.
> 
> If you are working on this feature, I volunteer to help with testing.

If you're still around, this is now (PARTLY) implemented in cocalc!  Please test.  The URL functionality is implemented, same as nbviewer, but there's not a badge quite yet and it only works to *edit* individual files (not whole git repos).

```
https://user-images.githubusercontent.com/1276278/177587186-dfb8e8ea-08aa-4fcb-911a-96f0ae93425b.svg
```

Here's a working badge to browse the CoCalc GitHub repo itself in CoCalc:  [<img src="https://user-images.githubusercontent.com/1276278/177587186-dfb8e8ea-08aa-4fcb-911a-96f0ae93425b.svg">](https://cocalc.com/github/sagemathinc/cocalc)

which I made via

```md
[<img src="https://user-images.githubusercontent.com/1276278/177587186-dfb8e8ea-08aa-4fcb-911a-96f0ae93425b.svg">](https://cocalc.com/github/sagemathinc/cocalc)
```

**Comment by williamstein** [comment]
> [To me, there's a small conceptual mismatch here: I think of what I am doing as running the notebook rather than editing it. In this use case, where the notebook comes from GitHub, "edit" suggests that the user is editing my notebook and the changes would go back to GitHub]

Conceptually this will be **exactly the same as GitHub's edit button**.  However, as mentioned above, the implementation in CoCalc is not finished yet:

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/1276278/177594854-a7363c88-046a-4217-859b-b1ae4a5d7cc1.png">

> Running the first few cells worked as expected. It took about 30 seconds to run the first cell, so I assume it was starting the runtime env.

No, the Docker container is already running.  The only thing that is happening is the Python kernel is started and the code is run. If the time is really 30s to run the first cell, that can only mean the filesystem and available CPU when you started the notebook was very slow, which could be the case when using cocalc anonymously (where you have lower priority and are on a heavily loaded node).

> The second code cell in this notebook downloads a file using the requests package. But that failed with the error below. I assume that's because as an anonymous user I don't have network access? It would be good to get an error message to explain that.

That's correct.  There's a big banner at the top, but it appears to be disabled for anonymous projects (since people tend to ignore it or complain about it.).  We'll re-enable it. 

> So I logged in and reloaded the notebook. I pressed the "Start Project" button and now that's been spinning for about a minute. Not sure what the problem is.

It sounds like you signed in with your existing account then tried to load a project that belongs to that anonymous user?  Due to security constraints, you should have no access to that project, and it shouldn't work.  Instead, go to https://cocalc.com/github/AllenDowney/ModSimPy/blob/master/chapters/chap01.ipynb, then click "Edit" again to copy that file to one of the projects you have access to.

**Comment by williamstein** [comment]
My impression in 2024 is that this sort of functionality is basically a way to attract abuse, spam, and security problems and it doesn't help with good growth at all.
