### ISSUE TITLE
can't view PDF files with non-lower case filename extension

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4562]
1. Make a valid pdf file a.pdf
2. Rename it to `a.PDF`
3. Try to open it, and get an error. 
4. It works fine if you rename it back to `a.pdf`.

**Comment by slel** [comment]
Fixed by

- #4562 -- webapp/pdf viewer: fix uppercase extensions

Many devices such as cameras, phones, etc, use all-uppercase
filenames, including the file extension, giving lots of files ending in
.JPEG, .JPG, .MOV, .MP3, .MPEG4, .MP4, .PDF, .PNG, .PDF, etc.,
and not all systems cope with that well (latex includegraphics,
some operating systems...). Good to see CoCalc get it right.
