### ISSUE TITLE
Set brace behavior depends on choice of math delimiters in markdown cells

### ISSUE THREAD

**Issue by StevenClontz** [sagemathinc/cocalc#4596]
Typing `$\{0,1,2\}$` displays set braces as intended, but `\(\{0,1,2\}\)` does not:

![image](https://user-images.githubusercontent.com/1559632/82100120-924a6580-96ce-11ea-89ce-2757eeed1f2d.png)

Confirmed on CoCalc.com and on the latest Docker image.

(FWIW, I don't see anything in the docs about which math delimiters are officially supported, but I tend to use `\(...\)`.)

**Comment by StevenClontz** [comment]
Bumping this as I hit this issue again today.

**Comment by williamstein** [comment]
I am going to soon deprecate using anything except dollar signs to signal math in markdown everywhere in cocalc, due to there being too many subtle issues/conflicts with markdown itself, and **things like parents are not allowed in Jupyter classic either**.  I've already deprecated them in the following PR, but this isn't merged yet: https://github.com/sagemathinc/cocalc/pull/5147
