### ISSUE TITLE
course homework collection: add option to set all files in homework folder to read only when collecting, to prevent student from working further

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#465]
Requested by: Robert Nyqvist

**Comment by williamstein** [comment]
He adds: 
> And perhaps a possibility to toggle back to writable files again if the students have to do a completion? Or not? Perhaps it is better if the teacher create a new assignments for completions.

**Comment by johnjeng** [comment]
We have TimeTravel to see these changes. Also, collection creates a copy of the file at collection time. The current solution allows for easy recollection if for example the student gets permission to "turn it in" late.

I'm not sure what the upside is other than clarity to the instructor about what is happening. Even then it would seem to me that the instructor might be *more* confused with this option because one might think "Oh, make it read only after collection? Does that mean usually they are connected and the student could work on it more without me knowing?".

**Comment by GregoryBard** [comment]
+1. I think perhaps this can be solved by better explaining the current
practice, rather than changing the current practice.
---Greg

**Comment by williamstein** [comment]
-1

However, let's change this to something else, which will be part of the next generation of course management.  The obvious thing is: "course homework collection: explicitly notify student when an assignment has been collected".

The vision is that there is a foo.student file for each student project, and it will have state information about what has happened so far.    When opened it will guide students to their assignments, tell them the state of collection, etc.

**Comment by johnjeng** [comment]
This is the first I've thought of 
>the next generation of course management

I'm inferring that it's a whole undertaking that we don't want to touch yet this summer.

**Comment by williamstein** [comment]
On Tue, Jul 5, 2016 at 3:39 PM, John Jeng <notifications@github.com> wrote:

> This is the first I've thought of
>
> the next generation of course management
>
> I'm inferring that it's a whole undertaking that we don't want to touch
> yet this summer.
>
 We could totally do that stuff this summer.  The faster we can iterate the
better.

-- 
William (http://wstein.org)

**Comment by DrXyzzy** [comment]
Requested by Fabricius Somogyi.

**Comment by DrXyzzy** [comment]
Also may be of interest to Nathan McNew.

**Comment by novoselt** [comment]
#2709 about student notifications would be better. What if a student *wants* to keep working anyway and read-only status breaks things?
