### ISSUE TITLE
deleting own terminal causes tab to be stuck

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4717]
1. create `delme.term`
2. check it is working via `ls` or whatever
3. `rm delme.term` in that terminal

it is deleted and a warning tells you about this, but there is still a tab in the open editor bar. clicking the "x" doesn't help either, it's stuck there.

deleting such a terminal while it isn't visible works fine.

also, other files seem to be ok. e.g. I did this:

1. create `delme3.md`
2. open a cocalc terminal in a second window
3. while `delme3.md` is visible in the first window, run `rm delme3.md` in the second window. all good.

**Comment by haraldschilly** [comment]
quick note: I just saw the same symptom (tab exists, but not functional at all) for a *.ts file. I am not sure what it happened, maybe deleting earlier or reconnecting. So, this is more than just terminals, they're easy to reproduce.

**Comment by williamstein** [comment]
This bug is caused by my *fixing* the activity indicator!  The problem is that reporting activity on a file causes that tab to spring back into existence in very minimal (and not closeable state), and there can be some activity right when the tab is being closed.  Funny.   The fix, of course, is to make the code for reporting activity be more careful.
