### ISSUE TITLE
Navigation bar is confused by similarly-named folders

### ISSUE THREAD

**Issue by StevenClontz** [sagemathinc/cocalc#4793]
To reproduce:

1. Have two sibling directories `~/foo` and `~/foobar`
2. Browse inside `~/foobar` -- navigation says `~/foobar`
3. Browse back to `~` -- navigation says `~/foobar` with foobar grayed out (intended behavior I expect)
4. Browse inside `~/foo` -- the correct files appear and the URL is correct, but navigation still says `~/foobar`.

**Comment by haraldschilly** [comment]
hmm, thank's for reporting this. I remember fixing something like that a while ago, but this must be clearly a similar edge case I missed.

**Comment by williamstein** [comment]
Wow, I've never noticed this bug before, but there it is.  Putting this at high priority because it's potentially very confusing!

**Comment by williamstein** [comment]
@haraldschilly I fixed this since there as an obvious logical mistake with a "startsWith" that would produce exactly this sort of bug.   That said, in your code you define some variables `is_adjacent` and `is_nested` around line 1005 of project_actions.ts, and it sure would be nice if there were comments explaining what these variables are supposed to represent:

```
    let history_path = store.get("history_path") || "";
    const is_adjacent =
      path.length > 0 && !(history_path + "/").startsWith(path + "/");
    // given is_adjacent is false, this tests if it is a subdirectory
    const is_nested = path.length > history_path.length;
    if (is_adjacent || is_nested) {
      history_path = path;
```
