### ISSUE TITLE
sudden webapp crash

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4850]
while I was in another tab, this happend … the webapp crashed in the background. weird.

![Screenshot from 2020-09-11 17-13-13](https://user-images.githubusercontent.com/207405/92942790-36140a00-f452-11ea-8047-9b41cab89d2c.png)

**Comment by haraldschilly** [comment]
OK, I had this again, while I was working in a `.tsx` file. I saw a red "not saved" warning, for maybe 5 seconds, and then it seemed to fell apart. Strange indeed …

first one:

![Screenshot from 2020-09-18 19-19-45](https://user-images.githubusercontent.com/207405/93626677-147fc900-f9e4-11ea-8167-2101c989e249.png)

down below the console, there are several identiacal ones, but at the end, there is this one slightly different

![Screenshot from 2020-09-18 19-21-41](https://user-images.githubusercontent.com/207405/93626810-485aee80-f9e4-11ea-978f-5c814d5af627.png)

**Comment by williamstein** [comment]
I think I should change useActions to work when the actions are not
defined, then make all the client code deal with that (typescript will
ensure it).  Better do it now when not much uses this, rather than later
when a lot more code uses useActions.

Thanks for reporting this.  I've never seen it but in theory obviously it
can happen!

**Comment by haraldschilly** [comment]
for the record, this just happened again for me. cocalc wasn't used by me, i.e. it crashed in the background while I was in another window on my desktop.

![Screenshot from 2020-09-25 18-47-27](https://user-images.githubusercontent.com/207405/94294178-bb71e100-ff5f-11ea-9482-d7119631fb93.png)
