### ISSUE TITLE
Website down status page says "CaCalc" instead of "CoCalc"

### ISSUE THREAD

**Issue by gabindu** [sagemathinc/cocalc#4887]
See the title.  Clearly less important than fixing the actual cause of the downtime - but still important. ;-)

**Comment by williamstein** [comment]
>  the actual cause of the downtime

I think the quick summary is: CoCalc has a free tier, CoCalc is very resource intensive, and there are a *lot* of random people in the world who want to use CoCalc all at once for free, and the only reason millions aren't already is because they don't know about it.    We're taking measures right now to mitigate this problem, and our primary strategy is to prioritize paying customers first and foremost!

**Comment by gabindu** [comment]
oh, I wasn't questioning the cause, I'm quite aware of the difficult issues you have to deal with. I just wanted to report the typo. ;-)

**Comment by haraldschilly** [comment]
this is fixed. right now the file is cached somewhere, so, probably looks still the same right now but the source file is modified.
