### ISSUE TITLE
Question about realtime sync in notebooks

### ISSUE THREAD

**Issue by dgoerger** [sagemathinc/cocalc#5034]
For realtime sync, where two users are logged in and viewing the same notebook and one is typing, I've noticed that the text sync only appears to run (1) after the user stops typing; (2) every 3-5 seconds (regardless of whether anyone is typing); and (3) when the cell's run. I'm having trouble finding this in the code, but if this understanding is broadly correct, is case 2 configurable? In particular I wonder if it might be possible to force sync the display every second.

I've set up the docker image as a beta test for a project, and the only negative feedback I've gotten is that the realtime sync appears to lag and doesn't feel very fluid. I set up two similarly-spec'd computers side by side, on the same VLAN etc, and set about trying to map the sync behaviour---that's how I came up with the three cases reference above, but of course it's entirely plausible I'm seeing patterns that simply aren't there.

I'm seeing similar behaviour whether I use cocalc.com or the self-hosted cocalc docker image.

Thanks so much for your help!

**Comment by williamstein** [comment]
> For realtime sync, where two users are logged in and viewing the same notebook and one is typing, I've noticed that the text sync only appears to run (1) after the user stops typing; (2) every 3-5 seconds (regardless of whether anyone is typing); and (3) when the cell's run. I'm having trouble finding this in the code,

It is [here](https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/jupyter/codemirror-editor.tsx#L518):
```
this._cm_change = underscore.debounce(this._cm_save, SAVE_DEBOUNCE_MS);
```
where `SAVE_DEBOUNCE_MS` is a constant hardcoded at the top of the file and set to 1500
and underscore.debounce is defined [here](https://underscorejs.org/#debounce).

In particular, changes by one user are only commited when they stop typing for 1.5 seconds.  Thus your assumption "(2) every 3-5 seconds (regardless of whether anyone is typing); " isn't correct (sync happens 1.5 seconds after a user stops typing and never when they are actively typing more quickly than one character every 1.5 seconds).

>  In particular I wonder if it might be possible to force sync the display every second.
> but if this understanding is broadly correct, is case 2 configurable? In particular I wonder if it might be possible to force sync the display every second.

It's possible, but only if you modify the source code of CoCalc and build from source.   In particular, you might start by changing the line I copied above to be `underscore.throttle(this._cm_save, 1000)` instead of what it is now. 

I won't make this change on cocalc.com because it would result in a large increase in the amount of network traffic and patches saved in the TimeTravel history, which would cost more money and potentially slow everything down.  It would also make TimeTravel history much more awkward to navigate.    Yes, with significant additional work the realtime sync and history system in cocalc could be revamped to store this additional information with minimal UI and other overhead (e.g., by truncating this history and only saving the state longterm after a burst of activity).   That's a significant amount of time and effort.
