### ISSUE TITLE
jupyter save: usage of method after close?

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5057]
saving after closing, I think that's what is triggering this warning. … ~~and well, more general I wonder what that error really is.~~ it's rather easy to reproduce. there need to be changes and then close the tab of the notebook. I wonder if there is a way to still let that final save operation run?

![Screenshot from 2020-12-02 14-34-01](https://user-images.githubusercontent.com/207405/100895263-a5335480-34bd-11eb-90a9-804f563076cc.png)

code

![Screenshot from 2020-12-02 14-34-32](https://user-images.githubusercontent.com/207405/100895290-aa909f00-34bd-11eb-8a57-abd1badfe440.png)

debugging that err, it's err_2 … tells me `project_id` is already undefined

![Screenshot from 2020-12-02 16-46-43](https://user-images.githubusercontent.com/207405/100895574-00fddd80-34be-11eb-86e5-c14c252379c3.png)

**Comment by williamstein** [comment]
The save function isn't written correctly -- after each async operation happens it's important to check if the object has been closed in the meantime.  The code in save doesn't do that check at all.  I've fixed it.

I also notice that the close function in misc deletes all functions too (which is why set_error is gone).  That seems like overkill given that functions are unlikely to cause memory leaks (and the sole purpose of close is reducing memory leaks).  I'll change that to only delete the non-functions.
