### ISSUE TITLE
Offer option to not start kernel when opening Jupyter document

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#5063]
Reasons for opening a Jupyter document include

0. having a look at it
1. showing it to someone
2. copying something in it to paste it elsewhere
3. editing markdown cells
4. rendering markdown cells
5. editing code cells
6. running code cells
...

Only some of these these actions require starting the kernel.

Starting it when it is not needed is
- a waste of time for the user
- a waste of resources for CoCalc

I would suggest not starting the kernel by default,
and starting it only when the user asks for it,
either via a dedicated button or menu item,
or by running a code cell.

Providing a checkbox in project settings or user preferences
would also work for me.

I realise this might as well be an upstream feature request
to Jupyter -- does Jupyter specify that opening a Jupyter
document systematically means starting the kernel?

**Comment by williamstein** [comment]
For what it is worth, I long ago made Sage worksheets behave exactly like you describe.  I also think what you suggest above makes way more sense.

One tricky part is that for Jupyter there is an assumption that the kernel runs in order to get information about editor and syntax highlighting modes for that kernel.   That's probably the hardest problem to solve.

The other tricky part is that the first cell execution will feel slower since the kernel has to start.     By starting the kernel immediately on opening the document, the first time you execute a cell feels a lot faster.   So we'll possibly get a lot of people complaining that "cocalc is slow"...

There might be other hidden reasons for starting the kernel that I'm forgetting.   It is definitely the case that Jupyter classic (and Jupyter console) does so and assumes this.

**Comment by williamstein** [comment]
I would rather make this work well enough and have it for everybody, rather than have to maintain two separate modes (which especially can make support and debugging harder).

**Comment by slel** [comment]
Thank you! This makes CoCalc much more stable for me.
