### ISSUE TITLE
Create an API parameter to hide the red buy a license header

### ISSUE THREAD

**Issue by realtimclemans** [sagemathinc/cocalc#5077]
For my purposes there won't be a need for a user of https://learnmaterialize.com (under construction) to buy a license. I'm happy to put up a header saying "Powered by CoCalc" or something. The red header is extremely annoying.

**Comment by realtimclemans** [comment]
My workaround is in a cell:
```
%hide
html('<style>.alert {display:none !important}</style>')
```

**Comment by williamstein** [comment]
>  The red header is extremely annoying.

It is also annoying to me to have people use CoCalc via the free trial mode and think the performance they get is representative of the non-free version of CoCalc.  We pack a large number of free projects into small servers and those free projects do not always work very well as a result.  There is no way around doing this, since cocalc is popular at this point.    Not making this very clear to people using cocalc is not fair, hence the banner is important since it makes it crystal clear that they should have very low performance expectations.

**Comment by williamstein** [comment]
That said, if cocalc-docker ever shows a banner in a similar situation, it definitely makes sense to have an option to disable it there.
