### ISSUE TITLE
jupyter classic vs cocalc-jupyter: make which should be used to open a notebook be set on a file-by-file basis, and be set in the metadata of the ipynb file itself (so it even works for public notebooks)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5124]
We should set some preferences for opening an ipynb file, which would hold for anybody who opens it.  In particular, there are notebooks that people want to share on share.cocalc.com, and they only work properly in Jupyter classic.  We should make it so that when those are opened in CoCalc, they open using Jupyter classic automatically without the person opening them having to do anything special.

As a side effect, this will solve a lot of problems we've had over the years:

 - if a notebook is opened in both jupyter classic and cocalc-jupyter at the same time, problems occur.  This would prevent that.
- it would be possible for a user to use jupyter classic and cocalc-jupyter notebooks at the same time, rather than having to use only one or the other.

There will always be a need for jupyter classic, since it supports 100% of the big Jupyter classic plugin ecosystem perfectly, so instead of deprecating it, longterm we should plan to double down on supporting it and making it even better in cocalc.   That's what I'm planning to do already, and the feature requested in this issue is just something along those lines.

**Comment by williamstein** [comment]
@jasongrout any comments about using .ipynb metadata for preferences for how an ipynb gets opened?  Is this something you've ever thought about?   E.g., maybe in JupyterLab there is an option to show or hide line numbers, and that's the sort of thing that could also be stored in the ipynb file.    More generally, it might be nice if one finds a random ipynb file on the web to know what Jupyter client was used to develop that file: nteract, jupyter classic, jupyterlab, cocalc-jupyter, auto conversion from sagenb or sagews, etc.

**Comment by jasongrout** [comment]
A couple of thoughts:

1. Having notebooks that only work in one frontend is kind of an anti-pattern, in that the point of a standard is that the notebook works in all compliant frontends. In reality, people and packages sometimes (maybe even often?) write all sorts of js in a notebook that depends very heavily on a specific environment. Part of the design of the ipynb format, and the rich display messages in particular, is to have reasonable fallbacks for different frontends with different capabilities. Having a notebook that only runs in one frontend reminds me of the days that a webpage would only really work in a certain browser - I'm really glad that we are mostly not in that era anymore and standards count for something.
2. For options like line numbers, we considered where that metadata should live, and decided it was best to leave that at the tool level. In other words, if I open your file, I likely want my *own* editor line number setting to take effect, not yours.
3. For informational purposes, I think it might be nice to have the provenance of a notebook, i.e., what software was used to create it, or perhaps the last frontend to save it. However, I really hope that doesn't turn into having many different incompatible variations on the notebook file standard.
4. We sort of punt on an issue like this right now, which has been discussed at various times - we don't have a good standard for the exact Markdown spec the notebook supports, so it is really just best effort with whatever library the frontend is using. Luckily many implementations are converging on CommonMark, so that is over time becoming our de facto markdown cell standard.

**Comment by williamstein** [comment]
@jasongrout thanks.  

I have to disagree with your point 1, since unfortunately extension support is not uniform across all clients, and that's the main reason for this issue.   Expanding on this, it is interesting that a notebook explicitly specifies the kernel it needs, but does not specify anything about the extensions it might need (except in informal comments).  The kernel is a requirement for using the notebook in much the same way that some installed extensions are.

Just recording for myself some of the steps that may be involved in this project:

  - rewrite current Jupyter-classic-in-iframe-with-realtime-sync code in typescript and react.
  - make it so Jupyter classic is just a way to interact with a **specific** Jupyter notebook (not a mode for all of them)
  - make the cocalc project backend fully aware if the notebook is being used in classic mode or cocalc mode, and don't allow both at the same time (unless I can be ridiculously clever)
  - make it so the system-wide default (in account prefs) is just the default, but you can still have multiple notebooks working both ways at the same time.
  - (!!!!) Notebook metadata would include the default way to use it, so mode choice is preserved when you copy an ipynb file (e.g. instructor copies files to students).  This is what's discussed above, where I disagree with @jasongrout, and will view "built to work with Jupyter classic" (say) as an explicit setting much like the choice of a kernel.   Of course, the user can change that setting, but things might not work.
  - challenge: use the same running kernel at the same time with both cocalc-jupyter and Jupyter classic.

**Comment by williamstein** [comment]
There will be no further development on jupyter classic in an iframe, except to deprecate and remove it -- https://github.com/sagemathinc/cocalc/issues/7706
