### ISSUE TITLE
There is at least one computer where the CoCalc WebApp crashes when opening notebook on Windows 10 browsers

### ISSUE THREAD

**Issue by sheinb** [sagemathinc/cocalc#5166]
While I normally use Chrome and Safari on MacOS, I wanted to verify everything worked as expected on Windows (10).  Tests with both Edge and Chrome led to webapp crashes as soon as I tried to open existing notebooks (and these repeated with reloads - never successfully launching the notebook editor).

**Comment by williamstein** [comment]
This seems really unlikely, given that:
 - most of our users are using Windows 10 and we've had no complaints like this, and
 - for the last few years, I have mostly used Windows 10 myself to develop cocalc (though today I'm mainly using an M1 Macbook pro),
 
Questions:

1. Do you have any extensions installed in your browser?   Can you try in incognito mode, which usually disables extensions by default.
2. What happens if you create a new notebook?  Maybe there is something specific to your notebook?
3. What happens if you use Firefox?

**Comment by sheinb** [comment]
Well, we definitely might have extensions - I tried to turn off those in Chrome and ran in incognito.  This is a family machine, and I was just curious if I were to have students use it, what the experience on Windows would be like.  As you can see - that didn’t change the message. These were each after my choosing +New Jupyter Notebook.  Edge gave the same.

So while it might seem “unlikely”, it does seem to happen?  I’m sure there’s something installed in this system that is the culprit (but it’s not my usual work machine, so that’s not so much my concern).

**Comment by williamstein** [comment]
How much RAM does the computer have?

**Comment by williamstein** [comment]
I've updated the title to be more accurate.

**Comment by sheinb** [comment]
I disabled a few more extensions and did manage to get notebooks to open without crashing.  Maybe the Evernote web clipper?  If I can get a definitive on which extension may be the culprit, I'll add that info.  The machine has 12Gb of RAM, btw.
