### ISSUE TITLE
Inconsistency with cocalc and Jupyter notebook with cell magics and ? 

### ISSUE THREAD

**Issue by jkitchin** [sagemathinc/cocalc#5179]
In a Jupyter notebook I can define this code:

![image](https://user-images.githubusercontent.com/1610070/105088226-9a328480-5a69-11eb-86a6-a4386fdb7492.png)

The same code in cocalc does not work though. The ? Seems to trigger an introspection:

![image](https://user-images.githubusercontent.com/1610070/105088439-e1b91080-5a69-11eb-94f7-48547ebe9418.png)

I think that is a bug.

**Comment by williamstein** [comment]
I agree that this is a bug and have tagged it as such.

**Comment by williamstein** [comment]
It's annoying that to work on this I have to tediously type in the code from a screenshot, but here it is:

```py
from IPython.core.magic import (register_line_magic, register_cell_magic, register_line_cell_magic)

@register_cell_magic
def cmagic(line, cell):
    "my cell magic"
    return line, cell.split('\n')
```

then

```py
%%cmagic test
a
b
c?
```

This is closely related to https://github.com/sagemathinc/cocalc/issues/3714, since we need to align our introspection heuristic with jupyterlab's.

I do 100% agree this is a bug and should get fixed.
