### ISSUE TITLE
Issues with slate.js markdown editor

### ISSUE THREAD

**Issue by jasongrout** [sagemathinc/cocalc#5204]
First, congratulations on launching the markdown editor! It seems very nice. I especially like the table and math editors.

Here are a few issues I noticed when playing with it (macOS Catalina, Firefox 85):

* Pressing up or down arrow keys moves the cursor directly to the top or bottom of the document. I expect it to move up or down a single line instead.
* The toolbar buttons for inserting links, images, or special characters show dialog boxes, but seem to do nothing after I fill out the dialog and submit it. Curiously, the cursor also moves to the top of the document when I submit the dialog box.

**Comment by williamstein** [comment]
Just confirming that:
1. I can reproduce this, and
2. It is *only* a problem on Firefox.  Both Safari and Chrome do not have this behavior.

I do not know if this is an upstream bug, since their demos run a significantly older version of slate.

**Comment by williamstein** [comment]
> Pressing up or down arrow keys moves the cursor directly to the top or bottom of the document. 

This is not exactly what happens.  More precisely the cursor keys work fine *within* a paragraph. The problem is when you try to move from one paragraph to the next. 

OK, here is an upstream bug report for exactly this bug, but the strange thing is they observe it only on Chrome and Safari but NOT on Firefox:   https://github.com/ianstormtaylor/slate/issues/3977

**Comment by williamstein** [comment]
OK, for the record, the root cause of both problems is windowing (for scalability to very long documents).  The solution for now is to disable windowing always on Firefox.
