### ISSUE TITLE
file navigation background is gone

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5206]
there is suddenly no background for the file navigation, example screenshot below. goal of this is to restore it.

![Screenshot from 2021-02-11 17-13-04](https://user-images.githubusercontent.com/207405/107664235-7d662700-6c8c-11eb-9f31-5b712ecf30c1.png)

**Comment by williamstein** [comment]
I don't understand how to reproduce this or what the bug is.  Whatever it is, I probably caused it recently, since I was working with a project in which the path was long (so more than one line) and fixed things so that displayed properly.  For me (on Chrome), directories do display properly in all cases, as far as I can tell.

By "file navigation" do you mean "current directory path"?

**Comment by haraldschilly** [comment]
as a reference, this is an image from the documentation, showing the gray background. and yes, I mean this cliackable directory path to navigate files.

![](https://doc.cocalc.com/_images/mini-terminal.png)

**Comment by haraldschilly** [comment]
I'm reopening this. There is now some background, but it's not as it should be, nor does the color match the color scheme.
