### ISSUE TITLE
Provide option to format with Black.

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#5285]
Currently the `Format` button runs [`yapf`](https://github.com/google/yapf) for python files and notebook cells which is fantastic, but it might be good to allow one to allow one to use [`Black`](https://github.com/psf/black).  The main advantage of `Black` is that it is -- by design -- does not allow customization beyond specifying line-length.

Not sure of the best place to select this:
* Editor settings: good for users, but it maybe should be a project-specific setting (especially if customization options are provided) so that projects can maintain uniformity.
* It would be really nice if somehow the tools could be run in the directory containing the notebook/file so that any repository specify configuration (black uses [`pyproject.toml`](https://github.com/psf/black/blob/master/pyproject.toml)) would be respected. This would solve make it uneccessary to provide configuration options beyond selecting between `black` or `yapf` in the project or editor settings.  (Not sure how hard it is to launch the process in the directory of the file/notebook.  If it is easy to do this, then I think `black` will do this by default, but not if using `blackd`.)

Comments:
* There is a [jupyter notebook extensions](https://github.com/drillan/jupyter-black) that implements this (see also #5284). This programmatically calls `black` from python [code here](https://github.com/drillan/jupyter-black/blob/master/jupyter-black.js) using javascript and relies on the Kernel having `black` installed.  This does not appear to use any local configuration.
* There is a daemon [`blackd`](https://github.com/psf/black/blob/master/docs/blackd.md) that reduces the overhead needed to run a python process each time.  (Might be a solution to the `yapf` performance limitation mentioned in #4343.  This will not use any local configuration.

**Comment by haraldschilly** [comment]
well, I'm happy if cocalc provides more formatting options. it's just that  I personally can't work with black because it messes up lists :man_shrugging: 

I think it should be a project wide setting. It makes little sense if two collaborators constantly undo each other formatting results.

The somehow "easiest" first idea that comes to my mind is to store the choice somewhere in `$HOME/.config/cocalc/...` (following the xdg layout). when a python formatting request is received by the project (which does the heavy lifting) it checks if a specific config file exists, reads it, and branches accordingly.

we could implement the project related code first …  and later come up with a UI config panel in the project settings, for more convenience.

**Comment by williamstein** [comment]
Watch out for
```py
>>> 2\
... %3
2
>>> (2
... %3)
2
```

**Comment by williamstein** [comment]
It's many years later and so far there isn't a single option for customizing any of our formatters, and also nobody ever asks for them.  I'm closing this in favor of cocalc just being opinionated with things like this, at least for the nearterm.
