### ISSUE TITLE
crash (in codemirror?) causing white page

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5383]
I wasn't working on cocalc, but when I came back the page was empty and just white. seems like that fallback error no longer shows up in that case. Here are a couple of screenshots, i.e. there is still "something in the DOM" and first, there was a CodeMirror error, and then some react issues.

![Screenshot from 2021-06-16 18-53-56](https://user-images.githubusercontent.com/207405/122261357-9bf75b80-ced4-11eb-9db7-069df0746b6f.png)

![Screenshot from 2021-06-16 18-54-23](https://user-images.githubusercontent.com/207405/122261387-a3b70000-ced4-11eb-8446-e78180970175.png)

![Screenshot from 2021-06-16 18-54-42](https://user-images.githubusercontent.com/207405/122261807-0dcfa500-ced5-11eb-9a4a-8f8e3cff1f6b.png)

![Screenshot from 2021-06-16 18-54-54](https://user-images.githubusercontent.com/207405/122261410-aa457780-ced4-11eb-87a4-147f614a159c.png)

**Comment by williamstein** [comment]
> seems like that fallback error no longer shows up in that case. 

That fallback error approach is gone, because in my opinion (being somebody who uses cocalc on mobile) it caused way too many worse issues that I could not figure out how to solve (e.g., with it being visible on mobile, at certain points when loading, etc.).  Now, window.onerror is configured in src/packages/static/src/webapp-error.ts and when triggered, the crash message defined here is displayed src/packages/static/src/crash-message.tsx.

Regarding the bug here, there are two points in our code where arbitrary codemirror options gets set on a running editor.  I've changed that code to skip over changes to inputStyle; for that, the user can close and open that tab (though they are unlikely to notice a difference -- it mainly matters for spell checking).
