### ISSUE TITLE
sagemathcloud as a maxima notebook server

### ISSUE THREAD

**Issue by mistguy** [sagemathinc/cocalc#54]
Sometimes I only use sage for symbolic computation, and I find it convenient to use solely maxima, so I  use `%default_mode maxima`, But I have the following problems:
- if I begin a cell with `%`, the server fails. For example: `%e, numer` will raises `ValueError`
- `%typeset_mode True` will not work, even if I manually wrap every cell with `tex()`

Actually, I think it would be great to have a separate maxima notebook(just like jupyter) on sagemathcloud. But for now, is there a work around?

**Comment by williamstein** [comment]
There are no workarounds that I know of for the bugs you listed here, since I didn't know about these bugs, as nobody had reported them until right now.

**Comment by billpage** [comment]
You could try a SMC mode hack like this:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/maxima_md%20test.sagews

to use Markdown to process Maxima output.

**Comment by mistguy** [comment]
Incredible! thanks bilipage. `%e, numer` doesn't works because `%` indicates a magic command right?

**Comment by billpage** [comment]
I'm glad you like it. I use something very similar for FriCAS computation
on SMC.  This was originally suggested by William Stein.  If you happen to
develop any improvements to this maxima_md mode please share it here.

Yes SMC treats ALL lines beginning with % as special. Use the equivalent
expression:

  ev(%e, numer)

to avoid this and also when you need to specify evaluation options.

>
https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/maxima_md%20test.sagews

**Comment by mistguy** [comment]
Can you share with me how you set up your FriCAS smc notebook?

**Comment by billpage** [comment]
I am glad to share it. Please refer first to the SMC FAQ:

https://github.com/sagemathinc/smc/wiki/FAQ#modes

This describes the initial version of the FriCAS mode. The current version
is here:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/fricas_md.py

As noted there as a minimum a small patch is required to the Sage
axiom/fricas interface. My most recent version of the source for fricas.py
is here:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/fricas.py

Using this version of fricas.py on SMC requires that a few other Sage
interface files be copied into your local project:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/expect.py
https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/axiom.py
https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/cleaner.py
https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/quit.py

Here is an example worksheet:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/Fricas
Work.sagews

Since FriCAS supports unicode I have also done some work to support the use
of unicode characters in FriCAS worksheets.  This involves either modifying
the (very) old version of pexpect included with Sage or upgrading pexpect
to a newer version.  There is a Sage trac post about this.

I also use Octave in SMC a lot and found that I needed to improve
octave.py. See:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/octave.py

Finally, note that the most recent revision of the Maxima mode is here:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/maxima_md.py

and here:

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/maxima_md
test.sagews

It now implements multiple statements per line and the use of $ to suppress
output.

I would be glad to help make this stuff available on SMC and in Sage but my
motivation to do so depends on the expressed interest of others.

Bill Page.

**Comment by billpage** [comment]
Sorry. Here is a corrected link to

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/Fricas%20Work.sagews

(for some reason cut-and-paste from the public share link in SMC did not
encode the blank character in the URL - bug I guess)

**Comment by billpage** [comment]
Also

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/maxima_md%20test.sagews

**Comment by mistguy** [comment]
Jupyter now supports a lot of languages and software, for maxima: https://github.com/robert-dodier/maxima-fishbowl
Is it possible that smc will implement some of them?

**Comment by slel** [comment]
To recap some of the discussion here, with some extra thoughts.

## Maxima in CoCalc

### Maxima in CoCalc's `sagews` worksheets

Using Maxima inside CoCalc's .sagews worksheets is easy by using the
cell magic to set the whole rest of the worksheet to Maxima mode after
typing at the beginning of a cell:
```
%default_mode maxima
```

#### Some issues

Some issues are then:

- the cell-magic mechanism conflicts with Maxima names that start with `%`
  when they are at the start of a cell, how to work around that?
- how to get the output to be typeset?
- how to get embedded graphics?

These points will arise when trying to follow one of the tutorials listed at
http://maxima.sourceforge.net/documentation.html
such as for example "A 10-minute tutorial for solving math problems with Maxima":
https://mathblog.com/a-10-minute-tutorial-for-solving-math-problems-with-maxima/

#### Cell-magic mechanism and Maxima names that start with `%`

In Maxima, the mathematical constants $\pi$ and $e$ are represented by `%pi`
and `%e`, so there might be a conflict with the parsing of .sagews worksheets
where starting a cell with `%` is interpreted as a cell magic.

Similarly, one would normally get numerical expression for $\pi$ and $e$
by evaluating the following in Maxima:
```
%pi, numer
%e, numer
```

#### Workarounds for cell-magic

Working around the problem is actually easy: it is enough to put
something before the `%` expression at the start of the cell, such as

- an initial space,
- an initial blank line,
- an initial comment,

so that `%` is no longer the first character in the cell,
and thus does not get interpreted as a cell magic.

See an example worksheet:
https://cocalc.com/share/fc94de41-6af4-4ee1-a684-c33a9e56b2b0/maxima-in-sagews.sagews?viewer=share

Another workaround suggested by @billpage is to use `ev` as in:
```
ev(%pi, numer)
```

#### Typeset output

Solved by the `maxima_md` mode suggested by @billpage at
https://cocalc.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/maxima_md%20test.sagews?session=default

#### Embedded graphics

Not sure what to do here.

### Maxima kernel for Jupyter

There is a Maxima kernel for Jupyter:
https://github.com/robert-dodier/maxima-jupyter

Not sure how to get it installed in CoCalc yet.

One of the issues here is that the installation instructions
are written for Clozure Common Lisp (CCL, previously openmcl)
with sometimes some indication of how to adapt to SBCL, but
we would need to use Embedded Common Lisp (ECL), on which the
version of Maxima shipped by Sage is based.

If someone is interested in working on that, let me know.
https://cocalc.com/projects/25769047-e4df-4229-9f55-98579a2e9f17/files/README.md?session=default
