### ISSUE TITLE
sagews: help via questionmark does not work.

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5403]
e.g. `solve?` ends up with various errors and no useful output. I don't know if this is related to recent front-end updates or a newer version of Sage. Maybe both.

![Screenshot from 2021-07-01 15-45-24](https://user-images.githubusercontent.com/207405/124134691-5feef980-da83-11eb-974b-6ad85600cf4a.png)

(I took the above in Firefox on Linux)

**workaround:** `help(solve)` outputs the help text

**Comment by williamstein** [comment]
I can confirm that this worked fine before my major webpack5 rewrite, since things work fine at this URL:

https://cocalc.com/static/old.html

However, at the first tagged new release (which I found from):
```sh
[prod3.default] kucalc-prod3-ctl-ws:/storage/shares/static/default/static> ls *.html
app-1.12.0.html  app-1.12.2.html  app-1.7.0.html  app-1.7.4.html  app-1.7.7.html  app-1.7.9.html  app-1.9.0.html  old.html app-1.12.1.html  app-1.12.3.html  app-1.7.2.html  app-1.7.5.html  app-1.7.8.html  app-1.8.0.html  
```
by going to https://cocalc.com/static/app-1.7.0.html, it is broken.

In any case, another workaround until I fix this is to use https://cocalc.com/static/old.html
