### ISSUE TITLE
graphical octave does not start up

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5427]
`octave --gui` fails in x11 with: `octave: GUI features missing or disabled in this build`

but I'm pretty sure those features aren't disabled. hmm …

in any case, we should remove the button in X11 to avoid confusion – or figure out what to do with octave to make it work. maybe there is a newer version available...

**Comment by williamstein** [comment]
In the cocalc-docker image I do not get that error and the GUI does start up.  However, it then shows this error:

> "The settings file
> /projects/2eaa2d8f-06f1-47fb-8b5c-048c26403944/.config/octave/qt-settings
> does not exist and can not be created.
> Make sure you have read and write permissions to
> /projects/2eaa2d8f-06f1-47fb-8b5c-048c26403944/.config/octave 
> Octave GUI must be closed now."

Indeed, looking at `/projects/2eaa2d8f-06f1-47fb-8b5c-048c26403944/.config/octave/qt-settings` I find that it's a file with NO permissions:

```sh
~/.config/octave$ ls -l
total 1
---------- 1 2eaa2d8f06f147fb8b5c048c26403944 2eaa2d8f06f147fb8b5c048c26403944 77 Jul 30 02:19 qt-settings
```

I thus think it's likely that the Ubuntu devs have totally screwed up in packaging Octave.

In cocalc docker I *only* do `apt-get install octave` and nothing else.  No optional `octave-*` Ubuntu packages are installed.

I doubt this has anything to do with our X11 server.  Octave used to work fine, but probably just got broke by newer versions of Ubuntu.

I agree that we should just remove the button from the launcher.    Don't remove octave, of course, since the Jupyter kernel works well.
