### ISSUE TITLE
Exceptional cases of percent signs in LaTeX syntax highlighting

### ISSUE THREAD

**Issue by kedlaya** [sagemathinc/cocalc#5463]
The LaTeX editor treats everything from a percent sign to the end of a line as a comment and does syntax highlighting accordingly. There are a few cases where this isn't the right behavior though: the most common ones are verbatim blocks and URLs as function arguments (e.g., for \url or \href).

**Comment by williamstein** [comment]
This is an upstream bug, since it is also present here: https://codemirror.net/mode/stex/index.html

Also regarding {verbatim} blocks, CodeMirror it just syntax highlights everything as if it a isn't a verbatim block at all.

Here's the actual syntax highlighting mode implementation for tex (it's only about 200 lines of code):  https://github.com/codemirror/CodeMirror/blob/bd1b7d2976d768ae4e3b8cf209ec59ad73c0305a/mode/stex/stex.js

**Comment by kedlaya** [comment]
I've reported this upstream:

https://github.com/codemirror/CodeMirror/issues/6772

Kiran

**Comment by williamstein** [comment]
This probably never going to be fixed and Marjinh basically said "I won't work on this" because it's impossible using the approach Codemirror takes to syntax highlighting (which is NOT a parser, BUT fast). Closing.
