### ISSUE TITLE
email invitation to student not sent; "reconfiguring" status does not go away

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5468]
Seen with Chrome and Firefox. Reported by Simon Charlow, replicated by Hal...

1. Sign into a non-admin CoCalc account that has Internet Access and Member hosting upgrades.
2. Create a course file.
3. In the Students tab, add an email address for an email account you control that does _not_ have a CoCalc account.
4. Check the student email, including spam folder, for an invitation. None is received.
5. In the course file, open the Configuration tab and click "Reconfigure all projects" and wait.
6. No email invitation is received after several minutes.
7. The status spinner stays up for at least several minutes as well. Refreshing the browser window clears the status pop-up.

<img width="698" alt="reconfiguring-1-project" src="https://user-images.githubusercontent.com/528072/131180465-4a5f2a6f-d721-4957-921c-c7a7715558f4.png">

**Comment by williamstein** [comment]
> No email invitation is received after several minutes.

Confirmed - I reproduced this.  I think this is because the student project itself isn't upgraded with network access, so invites don't go out via email.   This is obviously not good. 

> The status spinner stays up for at least several minutes as well. 

I was not able to reproduce this right now;  for me the configuration information finished and went away quickly.
