### ISSUE TITLE
improve sorting of students in a course

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5518]
Request: 

> "Hi. In the list of students, students are ordered by surname, but not by first name within surname. When marking against an ordered spreadsheet for example, this makes it easy to make a mistake as the ordering is slightly different, when you have a number of students with the same surname (eg Chen). Could they please be order by surname and then first name? Thanks."

**Comment by akshatakulkarni25** [comment]
Hello, I'm new to open source and i'm interested in solving this issue.Could you please help in getting started with this project and guide me through this issue. Thanks

**Comment by novoselt** [comment]
This is still the case:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/798af6e2-c4bf-4204-88af-cdbdc0cee22f)

I am surprised that this issue is not coming up in support, although people may just not be willing to spend their time to complain. I've had an issue when "complicated last names" were sorted differently in different systems and it was a huge pain to fix the final grades once they were posted in the university system, not to mention the stress for students.

My guess is that it is quite easy to fix and indeed William has marked it that way.
