### ISSUE TITLE
python3 with jupyter & FuncAnimation does not produce visible animation in non-cocalc notebooks

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5574]
The code below produces a visible animation when run as a .py from an X11 CoCalc terminal. No animation is visible when the code is put into a code cell in a Python 3 (system-wide) Jupyter notebook and run with any of:
- classical jupyter notebook, launched from CoCalc notebook using File / Switch to classical notebook
- Jupyter Classic notebook server, launched from project Settings
- JupyterLab server, launched from project Settings

Sample code, based on an example in https://pythonforundergradengineers.com/live-plotting-with-matplotlib.html

```py
from random import randint

import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# create empty lists for the x and y data
x = []
y = []

# create the figure and axes objects
fig, ax = plt.subplots()

def animate(i):
    pt = randint(1,9) # grab a random integer to be the next y-value in the animation
    x.append(i)
    y.append(pt)

    ax.clear()
    ax.plot(x, y)
    ax.set_xlim([0,20])
    ax.set_ylim([0,10])

ani = FuncAnimation(fig, animate, frames=20, interval=500, repeat=False)

plt.show()
```

Reported by Alon Levy.

**Comment by williamstein** [comment]
Quick thought:

1. What about other Python kernels?
2. With some kernels this is expected behavior because you didn't do
```py
%matplotlib notebook
```
I think we edit the kernel config in a nonstandard way to automate that for some kernels.

Anyways, imagine somebody using a Jupyter notebook fully loocally on their laptop, who wants plots or anything else to pop up in their own window.  Some developers like to do that, which is why `%matplotlib notebook` isn't uniformly the default...

**Comment by DrXyzzy** [comment]
The test program works as a single compute cell in a Python3 (system-wide) Jupyter notebook running on the classical Jupyter server, if I put `%matplotlib notebook` as the first line.

It also works with "Python3 (sagemath)" and "Python3 (Anaconda 2020)" kernels.

Closing this ticket.
