### ISSUE TITLE
CoCalc Internal grading system intermittently removes cursor from text field 

### ISSUE THREAD

**Issue by tomgrubbmath** [sagemathinc/cocalc#5660]
I am currently grading an assignment in CoCalc and every once in a while the cursor is being removed from the current text entry field, so that when I type on my keyboard to enter grades/comments the keystrokes are being used as nav commands or, in bad cases, bashing other text fields from previously graded entries. This is causing a very choppy/negative experience. 

Happening on Chrome browser; I know this is not a very useful bug report right now but I just thought I'd open the issue, I will try to circle back with possibly a screencap or something else that would be more helpful later on.

**Comment by williamstein** [comment]
Hi,  We once had a similar bug report like this and were easily able to fix it when it was clear how to reproduce it, etc.  I think last time it was caused by "infinite scroll", i.e., the relevant field was getting removed from the visible window and put back, but without focus.  In any case, just give us some steps to reproduce the problem, and we will likely be able to fix it quickly if we can also reproduce the problem.     Or, at least we can tell if it is related to browser extensions or something else.  It's also possible that just changing a parameter (related to infinite scroll) will help a lot.

**Comment by tomgrubbmath** [comment]
After a while I think I was able to pin down the problem: To reproduce this (Using Chromium Web Browser on Ubuntu), do the following:
1.) Open the grading portal for an assignment 
2.) Hit "Enter Grade" in any of the students boxes
3.) Scroll using the mouse wheel

This removes the cursor from the box and the next keystroke ends up in a very unexpected box. I'll link to this in a CoCalc support ticket as recommended above; I have a video recording of the behaviour if that would be helpful.

**Comment by williamstein** [comment]
Thank you for this update.  I definitely understand what is going on based on your report and will implement a fix soon.
