### ISSUE TITLE
jupyter notebook keyboard shortcuts

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#5711]
This may be the same as #2806.  User today reported:

> "Using keyboard shortcuts to edit a jupyter notebook
> WHAT HAPPENED?
> The keyboard shortcuts, such DD or BB for deleting or creating a cell, stop working. Then occasionally the shortcuts work.
> HOW DID THIS DIFFER FROM WHAT YOU EXPECTED?
> This has been problem for a while now, the functionality was fine in older versions."

**Comment by slel** [comment]
I get that in CoCalc-Jupyter with some frequency. When it happens,

- <kbd>Shift</kbd><kbd>Enter</kbd> has the effect of <kbd>Enter</kbd>
- <kbd>Esc</kbd> is not taken into account

Usually things get back to normal after a while.
No idea how to trigger it or how to resolve it.

**Comment by haraldschilly** [comment]
Is there anything "special" showing up in the output of the cells? I wonder, because maybe one of these elements is taking up the focus. It's definitely something that's hard to reproduce, though. I saw this a long time ago from time to time, but not in the recent months. Another possibility, it's maybe related to a specific browser version. I usually use Firefox on Linux. 🤷🏻‍♂️

**Comment by williamstein** [comment]
Relevant code has been rewritten...
