### ISSUE TITLE
xterm.js errors can cause a congested websocket communication

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5771]
I just ran into a weird edge case, where there are "bad characters" (or I don't know what) are in a terminal. This causes xterm.js to issue warnings/errors, because it isn't working properly. That in turn causes many errors to be reported, which are not successful. So, there are at least two questions:

* what causes xterm.js to break? if it is due to character codes in the output, a way to deal with this is to reset all its buffers and reset it.
* why are there problems reporting these errors? because there are so many at once? In any case, I this is weird as well. 

The symptom I saw is a red connection indicator in the top right, saying there are 17 pending messages, ... and an ever growing queue.

WORKAROUND: first close the problematic terminal, then refresh the cocalc page and wait a few seconds to make sure this isn't happening again. Then open a new terminal. Just deleting the history file wasn't enough (I'm guessing, one has to restart the project as well to clear out the problematic history)

I saved two screenshots about this. 

![Screenshot from 2022-03-03 10-40-04](https://user-images.githubusercontent.com/207405/156548043-ab5b6079-313b-4a42-a2a3-9de5bc901f32.png)

![Screenshot from 2022-03-03 10-40-17](https://user-images.githubusercontent.com/207405/156548072-a6d376b0-4738-4ad8-bd71-c672469e48a5.png)

**Comment by williamstein** [comment]
OK, I just hit this again, so I'm fixing this ASAP.

**Comment by williamstein** [comment]
Easy way to reproduce this:
```sh
~$ head `which head`
```
Then you have a terminal such that looking at it "breaks everything".   Do the above a few times to get up to the 17 message threshold needed to block further messages getting processed by the hub.

The cause is non-utf8 characters in the output, which causes trouble somewhere (not sure where yet).  xtermjs shows an error in the console, but that might just be a "friendly side effect", not the root cause of the problem, i.e., it's very nice behavior on the part of xtermjs to show this error, which makes debugging this easier.
