### ISSUE TITLE
course license needed project count is off by 1 (or misleading)

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#5785]
1. create a license with run limit 1
2. create a course with 1 student
3. in course config, add the license and make sure "Upgrade instructor project" is **disabled**
4. expand the view of the license in course config and see the following: "NOTE: This license can only upgrade 1 simultaneous running projects, but there are 2 projects associated to this course."

That note is either wrong or misleading because the user has configured the course to not use a course license for instructor project, i.e. a run limit of 1 should be perfectly adequate for the course config.

**Comment by novoselt** [comment]
Still there, but the message is not wrong - the instructor project IS associated to the course, regardless of using the license or not. I am not sure how useful that message is - it is hard to get to it unless you know what to do. If we do want to show a warning, it should not be buried in the middle of some detailed expanded view, it should be obvious either as a course banner (maybe even for students - "Your project is not upgraded, because your instructor is too cheap and didn't provide enough resources for all students" in a slightly more polite way) or at the very least as some very visible message on the course configuration tab, so that it is not in your face all the time, but it is impossible to miss by mistake.

**Comment by williamstein** [comment]
This is in frontend/course/configuration/upgrades.tsx in the function "render_licenses".  Certainly the message should be reworded.
