### ISSUE TITLE
jupyter: kernel status is suddenly narrower, not same height as menu

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5908]
this looks off: the kernel status is narrower in height, no longer fits with the menu.

![Screenshot from 2022-05-05 09-34-16](https://user-images.githubusercontent.com/207405/166880145-fe41b839-4853-41b4-80cb-0a5a13fccf13.png)

**Comment by williamstein** [comment]
Yes, that's intentional.  It has about half the vertical content, and I'm using the same component in other places -- e.g., the whiteboard and maybe the slate markdown editor soon -- where there is no menu off to the left.

Adding margin:5px here in Jupyter makes it look perfectly centered, so I'll do that.

**Comment by williamstein** [comment]
![Uploading Screen Shot 2022-05-05 at 7.12.14 PM.png…]()

**Comment by williamstein** [comment]
<img width="1146" alt="Screen Shot 2022-05-05 at 7 12 14 PM" src="https://user-images.githubusercontent.com/1276278/167055375-2e1c4ffe-9596-4a92-970e-1b6982ce096c.png">

(wow, even in cocalc I made it so you can't accidentally submit while uploading an image...)
