### ISSUE TITLE
jupyter: scroll position not retained in firefox

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5909]
1. jupyter notebook with many cells
2. scroll down somewhere, put your cusor there … nothing unusual
3. tab to "files" and back

- expected: same position
- reality: back at the top

note: this is fine in chrome, but not in firefox (I'm running version 99.0)

**Comment by williamstein** [comment]
It turns out that this was caused by elements in the DOM getting reordered, which chrome could handle, but firefox couldn't.  It caused Virtuoso to reset the scroll pos as a symptom, but could have caused other issues with state as well. So it's really good that it's fixed now!  It took quite a while and a lot of random ideas until I finally figured this out today.

**Comment by haraldschilly** [comment]
ok, I see, this is definitely not a trivial bugfix ^^
