### ISSUE TITLE
Hidden <details> blocks do not render properly with fenced code.

### ISSUE THREAD

**Issue by mforbes** [sagemathinc/cocalc#5933]
In the CoCalc notebook interface, the following does not render properly ([e.g.](https://cocalc.com/projects/d8321832-12e5-4c52-ac0b-46b5f29e9740/files/Test.ipynb)):

````
<details>

```
# Some code
1+1
```

</details>
````

This renders with the code leaking out of the `<details>` block:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/1028433/168494169-74d35b61-e444-4a29-a82d-14c1d64e542f.png">

It should look something like this (works on GitHub and the classic Jupyter server):

# Details Issue

<details>

```
# Some code
1+1
```

</details>

**Comment by williamstein** [comment]
This is a design decision made by the markdown-it parser.  

Try your example at https://markdown-it.github.io/, where it does the same thing.   In general, markdown-it automatically terminates an html block when there is a new top level block as indicated by a newline, so 
```md
<details>
```
# Some code
1+1
```
</details>
```
works as I would expect, i.e., it's all part of a single details.  Of course, you literally get backticks, since it's all interpreted as html.

---

I don't know why the choice to terminate when there is a blank line was made.  It seems weird.  It's NOT what GitHub does, which is consume everything up until the closing tag, and also turn *some* markdown into html and not other markdown!?:

<details>
# In GitHub

```
# Some code
1+1
```

</details>

My guess though is that markdown-it does what it does for speed and to have a good way of handling the case when the user forgot the corresponding closing tag (i.e., the markdown-it choice is most likely to be usable in that case).  But I don't know.

---

JupyterLab, which uses marked I think (yet another markdown processor) is pretty much the same as GitHub in how it handles the above, so probably that's what you're expecting.

---

I find it quite weird that the backticks code works inside of HTML in Github/Jupyter, but the # heading doesn't work.  That's just weird.  It's **directly contradictory** to what is said at https://daringfireball.net/projects/markdown/syntax which is 

> "Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style *emphasis* inside an HTML block."

Markdown-it claims to follow the commonmark spec by default.  **Ah ha!** that spec is very clarifying.  In particular, look at [this](https://spec.commonmark.org/0.30/#html-blocks), where it very clearly lays out precisely when an html block starts and ends.  It depends on the type of html block.  E.g., a pre block can have blank lines in it.  However, a details block  starts with <details> and:

> "End condition: line is followed by a blank line"

That's it.  So the only possible legal way to end a details block is with a blank line, according to the commonmark spec.  

So markdown-it is properly following commonmark wrt to your question, and definitely Jupyter and GitHub are not.  So let's see what the GitHub Flavored Markdown spec says (https://github.github.com/gfm/#html-blocks).  Oh, it seems to just be a copy of the commonmark spec.

Ok, so I've come I think to the conclusion that GitHub and Jupyter are violating the spec and CoCalc (via markdown-it) gets this right.  What do you think?

**Comment by williamstein** [comment]
Upon further reflection, what's going on is that the parsers are just outputing **invalid html** in the case when the html block is invalid, so it's having the above effect, which you like and depend on.     In contrast, CoCalc does NOT output invalid html when the html block is invalid, hence you don't accidentally get the effect you want.   The reason is because CoCalc parses the markdown into an internal tree structure (an AST), then generates a guaranteed valid React tree and renders that directly, possibly running it through XSS safety stages (in case of the public share server) and certainly ensuring any HTML it places in the DOM is valid.      In contrast, all these other markdown renderers are just doing a "garbage in - garbage out" algorithm, so if the input HTML block is "nonsense malformed HTML", they just output the same thing.   This is all done with string manipulation, and no actual understanding of the AST structure of the markdown document.    This randomly happens to make it so when that you use `<details>` it works.

**Comment by williamstein** [comment]
A good example to illustrate the difference is:
```md
<div style="color:red">

# foo
  
</div>
```

In Jupyter (but not Github, due to sanitization), this makes the heading foo be red, but also formatted as a heading.  The reason is because it is parsed as:

```
- an html block that is mangled by itself `<div style="color:red">`
- a heading
- another html block that is mangled by itself `</div>`
```

The markdown renderers then just spit those html fragments right back out and you get a nice red heading in Jupyter.  In CoCalc you don't.  Instead you get:
```
- the mangled html block is made into the valid block `<div style="color:red"></div>` and output
- the heading (which is of course black)
- the mangled html block `</div>` is turned into noting and output.
```

Incidentally, in CoCalc the library https://github.com/remarkablemark/html-react-parser converts strings of html into react.
There is really no possible way in general to combine react components and random html snippets... It simply isn't meaningful to do that in general.

**Comment by mforbes** [comment]
Ah.  I see why, but don't see a simple workaround.  Some Markdown parsers provide a `[details][/details]` pair. (Discourse does this for example.)  If we get to MyST rendering, then this can be provided by ```` ```{admonition}...``` ```` blocks.  Not sure what the best option is for Jupyter notebooks.

**Comment by williamstein** [comment]
I've decided to close this, since there's no possible way cocalc can support such use of "invalid fragments of html" mixed with markdown.  It's just not in the cards.  Sorry.

**Comment by williamstein** [comment]
Sorry, I didn't see your message. You have a very good point that I've offered no viable workaround.

**Comment by williamstein** [comment]
So... hmm, if a minimum requirement is  "compatibility with Jupyter", maybe the only choice is to make `<details>` work much like Collapsible markdown-it extension?  I could probably do this by writing a new markdown-it extension.

**Comment by mforbes** [comment]
I am not sure what to suggest.  For me, since I use CoCalc a fair bit, any way of toggling data would be fine.  But, others might expect the compatible (mis-)behavior, so if your suggestion is technically feasible, it seems like a good option.

**Comment by williamstein** [comment]
This is now implemented and live.

I did not yet implement support for `<summary>` to customize "Details" and will make another ticket about that.
