### ISSUE TITLE
link to file activity notification for boards leads to ipynb file

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5970]
1. someone is active in an `*.board` file
2. the avatar shows up in the "files" listing, next to the directory bar
3. if I click on it, it actually opens `.[name].board.ipynb`.

I guess some special case handling isn't implemented (or, the other way around, the default to open an `.ipynb` file should be removed).

**Comment by williamstein** [comment]
> the default to open an .ipynb file should be removed

That's the problem.  It's showing activity for both the board itself and, if you use a jupyter kernel, also for the auxiliary file.  Somehow I need to change the code for file activity to not report that... unless you explicitly open that file.  I thought I might have already done that?      Note that I actually *did* explicitly open the auxiliary files for the presentation today a few times, so we should double check this.

Since opening that file by the whiteboard does NOT create an actual tab, that's probably a good extra filter to put on the file activity notifier -- move the code that does the notification to only be triggered if the tab itself is visibly opened.

**Comment by williamstein** [comment]
I confirm this is broken exactly as Harald was worried it is.
