### ISSUE TITLE
share server: copying files to newly created project requires clicking a button, which is incredibly confusing because  people don't read and just click on the first thing their eyes see

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#6025]
Seen with Chrome and Firefox on macOS 12.4.

1. Open an Incognito window with Chrome or a Private window with Firefox.
2. Visit https://cocalc.com/drxyzzy/today-i-learned/latex-title-date
3. Click "Edit" while viewing the folder.
4. Click "Use CoCalc anonymously".
5. In "In a new project", enter "pyt_anon" and click "Create Project".
6. In the line "Created project pyt_anon", click the link for "pyt_anon".
7. When the tab for the new project opens, observe that the Files list is empty (see below).
8. Wait a minute and refresh the browser. Observe that Files list is still empty.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/528072/176518178-56f4343c-b4c1-41f0-b1f9-25bd401d5a3f.png">

**Comment by williamstein** [comment]
I just tried this and it worked perfectly first try.  I've also tested this many times and it has always worked.

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/1276278/176518996-ab5a4ec2-31ee-47e1-bec5-a1c238b0812a.png">

I think what's happening in your steps above is that you are simply ignoring the step after creating the project! I don't know why.  Step 1 is to create the project, and it gets created.  Then there is a HUGE button right below it that says "Copy XXX to YYY.":

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/1276278/176519242-603c0bc3-36c1-4067-8985-c03e78d4994f.png">

Somehow you didn't think to read or click that button, and instead jumped immediately to the project, which is empty because you never copied any files to it. 

So I don't think this is a bug.  It may be a good argument to change the UX to automatically start the copy process after creating the project, or simply to delete the link to the project -- since you wouldn't click on it, and you would be sitting there thinking -- what do I do next?  Maybe click this massive big blue button?  There's nothing else I can do...

Thoughts?

**Comment by haraldschilly** [comment]
to me, such a large button looks very weird.

**Comment by williamstein** [comment]
I have to rewrite this code anyways to support automatic cloning from git, and I'll just entirely eliminate the explicit copy step, instead making it fully automatic.  That should resolve this issue.

**Comment by williamstein** [comment]
fixed in 8f107277326c10624b1d150d698d84f8d896fc04
