### ISSUE TITLE
zig formatter regression

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6089]
I recently made a change to project feature detection for `quarto`, and well, something must have gone wrong for `zig`.

![Screenshot from 2022-08-19 16-27-58](https://user-images.githubusercontent.com/207405/185640691-6570cf7c-6024-4e32-986b-6723d5763038.png)

**Comment by williamstein** [comment]
Setting this to blocker since I use precisely this feature a lot.

I haven't noticed only because I hadn't restarted my project on cocalc, and also I'm working on a local copy of cocalc that I hadn't updated.  I just restarted my cocalc dev project and now zig formatting detection is broken.   This project has its own copy of zig installed in the PATH, but that didn't make any difference.
