### ISSUE TITLE
Jupyter Notebook scrolling stops too early

### ISSUE THREAD

**Issue by NicoJG** [sagemathinc/cocalc#6141]
I feel like there are a few things about the CoCalc Notebooks that make them feel weird to work with. 
And one of those things should be really easy to fix:
Let the user scroll further down than the last cell. In almost all Jupyter environments I use (Jupyter Lab, VSCode, Google Colab...), the scrolling does not stop when the end of the last cell is at the bottom of the screen but rather when it is almost at the top of the screen. 
This enables the user to write code on the top/middle of the screen rather than always being stuck at the bottom of the screen.

**Comment by williamstein** [comment]
Good idea!

**Comment by williamstein** [comment]
Here's what other notebooks and related software do:

- CodeMirror code editor and browser text areas (like the one I'm writing this comment in): same as cocalc -- no extra padding
- vim in a terminal: up to almost a whole screen of padding depending on *how* you scroll down. It's weird.
- Emacs in a terminal: seems very similar to vim in that it can be "up to everything but a line" (or almost nothing) and depends randomly on how you scroll down. 
- Jupyter classic: almost the same as cocalc but you get a hard coded 100px of margin at the bottom.
- JupyterLab: about 90% of a page of extra padding.  This seems like too much to me, since in can be confusing and make you almost think your notebook is blank.  Unlike vscode, you get this full 90%+ even if you only use the keyboard.
- Microsoft Word: it's based on pages, which are like cells, and you get no extra space below the last *page*.  But of course, you just make a new page for more space. Really it's like Jupyter classic with maybe 50px of margin at the bottom.
- VS Code: about 95% of page of extra padding (all but one line). This is similar to JupyterLab but even more extreme.  With vscode if you are scrolling using the keyboard only you get NOTHING, but if you scroll using the mouse you get your extra blank page.
- Colab: always exactly 400px, irregardless of your screen height.  If your screen is short, you can scroll everything way off the screen and see a blank page, and if tall it could be very small. 


JupyterLab discussions where they are adding this feature, and maybe implement several approaches: 
- https://github.com/jupyterlab/jupyterlab/issues/488
- https://github.com/jupyterlab/jupyterlab/pull/1696

They started with 100px in the original PR, but now it is this complicated formula, which can be customized by each theme:

```css
  /* The scroll padding is calculated to fill enough space at the bottom of the
  notebook to show one single-line cell (with appropriate padding) at the top
  when the notebook is scrolled all the way to the bottom. We also subtract one
  pixel so that no scrollbar appears if we have just one single-line cell in the
  notebook. This padding is to enable a 'scroll past end' feature in a notebook.
  */
  --jp-notebook-scroll-padding: calc(
    100% - var(--jp-code-font-size) * var(--jp-code-line-height) -
      var(--jp-code-padding) - var(--jp-cell-padding) - 1px
  );
```

So anyway, everybody does this differently, and JupyterLab has done it three different ways over the years.  I'll likely implement something right now that is different than every single one above!
