### ISSUE TITLE
possible antd@5: notification number in bell and single-character in avatar are offset

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6268]
see screenshots, in Firefox.

![Screenshot from 2022-12-08 10-44-22](https://user-images.githubusercontent.com/207405/206417115-1e8d9627-bb84-409f-9f33-3a1f874bfaea.png)

![Screenshot from 2022-12-08 10-31-35](https://user-images.githubusercontent.com/207405/206417155-fe770766-3788-453e-95b2-b126020dfb0a.png)

**Comment by haraldschilly** [comment]
hmm, I still like it, though. I'll look into this, probably just a small detail.

**Comment by williamstein** [comment]
I rewrote it using the badge just now.  I like the badge better since it clearly has way more thought put into it and also the badge design scales to any number (whereas a bell doesn't -- the shape simply doesn't work).  The bell number has never been "perfect".  I did *keep* the css style to make it move around a bit, which you added.

**Comment by williamstein** [comment]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/1276278/206515204-30088299-4d97-4c00-a427-5ad4e1f60d0b.png">

**Comment by williamstein** [comment]
Also, the antd badge has a very nice animation when it changes values.
