### ISSUE TITLE
Markdown - - - Horizontal line scrambles table definition

### ISSUE THREAD

**Issue by vossrf** [sagemathinc/cocalc#6311]
Problem described in **[MarkdownLineTableProblem](https://docs.google.com/document/d/1SYe574Y2VJQCwRmX4yg8GJd26Lt0PbUmkrSdUcMFGhU/edit?usp=sharingl)**
with code in **[Jupyter notebook](https://drive.google.com/file/d/1Lmq45oO7CsSC6dDWhOB-E8N8wXHudDtp/view?usp=share_link)**

Table is scrambled in Jupyter notebook Text cell display and in HTML from **Save and Download as... HTML**,
but correct in **Save and Download as... HTML via classic** or **JupyterLab nbconvert**.

**Comment by williamstein** [comment]
This is a conflict between how YAML headers are used as an extension to markdown and the use of an `<hr/>` (via three dashes) as the first line in a markdown file.

Right now the document is considered to start with a YAML header if the first three characters are `---` and there's three dashes in a row somewhere later in the document.  Probably the best fix is to make the additional requirement: "The document contains another line with exactly three dashes in it (and nothing else)."    That's not the case in the linked to example, where the three dashes appear in the middle of a table.

Note that no matter what we do, even making the additional constraint above, somebody will get annoyed by this and tripped up.  It is simply the nature of markdown extensions that they always cause confusion, because -- unlike latex or xml -- ** all strings are valid markdown!**  (see   https://stackoverflow.com/questions/4751032/whats-an-example-of-some-invalid-markdown) Thus absolutely any possible extension to markdown will conflict with some existing valid markdown.  YAML headers are an extension.  

WORKAROUND: Don't start your document with three dashes or use `<hr/>` instead

**Comment by vossrf** [comment]
I found the problem when a Markdown cell, which worked correctly in the past, stopped working when I returned to CoCalc in the last weeks (knowing nothing about YAML). I had already discovered that I could use 3 underscores to designate a horizontal line as a work around.

While it may be theoretically true that "absolutely any possible extension to markdown will conflict with some existing valid markdown", there is no excuse for a new extension to use an existing Markdown shortcut (---) as a delimiter. Certainly specifying YAML between "**-YAML-**" delimiters would cause far fewer conflicts.

**Comment by williamstein** [comment]
I'm not personally making up the YAML header format spec.  It's not up to me, since using ---'s is [already chosen](https://jekyllrb.com/docs/front-matter/).  However, I've very highly prioritized your bug report and changed the code c3cfacad336c4bbbcd4244287e2d1054c309fd91  in cocalc so that there's a yaml header only if there very first 4 characters of the file are "---\n" and there  is another line later in the file that exactly equals --- with a newline after it.  That change will be live within a day...
