### ISSUE TITLE
next/licenses/managed: awkward table columns

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6315]
This is probably a side effect of updating antd. The columns should be more evenly spaced. Also, maybe the whole content+table should be wider when the window has enough space...

Bonus points: the quotas should be human readable.

![Screenshot from 2023-01-04 15-05-51](https://user-images.githubusercontent.com/207405/210572735-6d6f8110-6fbf-4708-83ba-805f85500c34.png)

**Comment by williamstein** [comment]
Note that i think this only happens with ancient quotas where rendering falls back to JSON because it isn't implemented. With anything modern, the page looks like this:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/1276278/211208460-b104de88-2d59-4e41-bc09-3341f21b2941.png">

**Comment by williamstein** [comment]
Now like this (ignore part above json):

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1276278/211209146-0d537eaf-0bc8-4135-a283-ff6ff43eabdf.png">
