### ISSUE TITLE
Deprecation of Snippets

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#6351]
Some snippets use commands that have been deprecated (although a in my case a nice warning popped up for a quick modification!) 

Example: Under Snippets -> Sympy -> Calculus -> Finite Differences

Should be changed to:

from sympy import *
from sympy.abc import a, b, s, t, u, v, w, x, y, z
k, m, n = symbols("k, m, n", integer=True)
f, g, h = symbols("f, g, h", cls=Function)
dx0, dx1 = symbols("dx0, dx1")
formula = Derivative.as_finite_difference(f(x).diff(x), [x-dx0, x, x+dx1])
print(formula)

In general, it would be nice to update the templates to be: 
1) Working with no modifications.
2) More robust and relevant (easily searchable via Youtube).

**Comment by haraldschilly** [comment]
The repo is here: https://github.com/sagemathinc/cocalc-snippets and sure, some definitely need some update. Also, some are sourced from jupyter's "boilerplate" extension, which is probably not maintained any more. If you have specific fixed in mind, please feel free to open a ticket at the snippets project.
