### ISSUE TITLE
projects do not delete process.env.NODE_ENV

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6365]
I'm not sure why this became necessary, but it's very confusing for me to have `NODE_ENV` set to production. i.e. it deletes stuff from the cocalc dev project.

So, why exactly was removing the env var from the project setup necessary? I hope there is another way to fix this.

**Comment by williamstein** [comment]
> I'm not sure why this became necessary,

It is necessary because the following definitely does horribly breaks things:

1. Start a node.js process with process.env.NODE_ENV = 'production'
2. Import some things
3. Change  process.env.NODE_ENV
4. Import some more things, e.g., via `await import('...')`.

In particular, for us this breaks importing react in step 4.    We were doing exactly the above for a long time, but 
with step 4 "highly unlikely" to happen.  However, I profiled project startup and it turned out that a *huge* amount of time was spent importing some jupyter-related functionality from the frontend.  With the slow filesystem on cocalc.com (via NFS), this could easily be around 15 seconds (or worse) when the cache is cold.  I changed the project to not important that code until it's actually needed, e.g., when opening a Jupyter notebook, rather than whenever a project starts.  This makes it so step 4 above is 100% likely to happen on first opening a Jupyter notebook.  There could have also been any number of subtle bugs caused by this situation that we didn't notice.

We could make it so NODE_ENV is not set for subprocesses, but this cannot be done by deleting process.env.NODE_ENV.    Instead we need to systematically set the `env` option when spawning subprocesses.  That's pretty reasonable to do.  What do you think?

**Comment by williamstein** [comment]
I'm going to just not set NODE_ENV in the first place.  It's not set when running projects in cocalc-docker, and there's no reason I can think of to use it.  We don't change behavior of cocalc-project's based on it.  It's mainly a flag to impact how express and webpack and next work, none of which are used much in cocalc project's.

This discussion is interesting: https://stackoverflow.com/questions/16978256/what-is-node-env-and-how-to-use-it-in-express
