### ISSUE TITLE
file/rename: disallow file names to end with spaces

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6370]
It's possible to rename a file `foo.ipynb` to `foo2.ipynb ` with a space at the end. There is a warning banner, but it still causes users to rename the file and no longer be able to open the notebook. I suggest to block renaming completely, if the name ends with a space. If someone really wants a space at the end, they have to resort to the terminal.

**Comment by williamstein** [comment]
>  I suggest to block renaming completely, if the name ends with a space.

This problem (renaming a file in a way that is extension aware) has been solved in operating system graphical interfaces.   We should be  aware of what they do before making up our own solution.

## Here is what macOS does:

1. When you click to rename a file it appears to only show you and let you edit the name itself, without the extension.   I.e., you don't even see the extension.  So if you try to rename `foo.png` it just shows you an edit with `foo` in it.
2. If, when renaming the file, you explicitly type a new extension (so in the above, you type `foo.txt` where `foo` was), then it shows the following prompt:  "Are you sure you want to change the extension from “.png” to “.txt”?"
<img width="350" alt="image" src="https://user-images.githubusercontent.com/1276278/214893279-fb2e5c08-c94a-4816-9e53-2dcbfd146f57.png">
3. If you instead change `foo` to `foo.txt[space]` then it creates the file `foo.txt .png`, and I guess you could then rename it `foo.txt` in another step.

I don't really like this.  It's some weird "magic" and makes renaming `foo.ts` to `foo.spec.ts` (say), which is a natural thing to do (!), only possible via multiple steps (?).  It just feels like an unprofessional hack to me.

## What MS Windows Does

You have to click View --> Show File Name extensions in Explorer to get it to show extensions at all, otherwise you're not able to edit them.  Once you do that, then right click and select Properties, you can edit the extension, and it works almost exactly the same as cocalc.  You just directly edit the entire filename, including the extension, and get a warning, pretty much exactly as in cocalc.  However, there is a significant change regarding whitespace:

- if you put any trailing spaces after they extension, they are automatically silently removed.  This is very close to what you are proposing doing.
- if you put a leading space, then the file seems to completely disappear!  Yes, I tried this with multiple files, and the files appear to be completely gone from Explorer, as far as I can tell!  They still exist from the terminal when you do `dir`, and they do not appear to have a space in the beginning of the filename from the terminal.  This seems insane and horrible, and weird that I stumbled on this in a few minutes.

## Conclusion

Your solution is better than either of the above.

**Comment by williamstein** [comment]
Harald fixed this.
