### ISSUE TITLE
Unauthenticated user landing page should load instantly 

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#639]
I don't think our longish load time sends a good message for first time users. I'd prefer the landing page for unauthenticated users be as fast as going to https://cloud.sagemath.com/policies/ and use simple javascript to test for cookies. If cookies then attempt a redirect to the projects listing url. 

See https://blog.kissmetrics.com/speed-is-a-killer/

**Comment by haraldschilly** [comment]
well, I don't really know how to do this, might be a lot of work. from a pure technical perspective, the initial page does load extremely fast. what takes time is to actually get to the app itself after all the initializations. that's a constant effort for optimization and experimenting around.

more generally, my initial vision was to have www.sagemath.com as the overall landing page -- as a simple one-page intro with some info, but I spent maybe 2-3 hours on it and it never grew into anything. this page would satisfy the pageload + information requirement. now we did agree to just redirect to smc, so that's gone ...

besides that, I know how to display content immediately when the page shows up. that's this loading banner with the logo and some extras. I'm not sure if we should expand this into an incomplete website, that's being loaded quicker, and then it somehow adds new  stuff to itself after some random timeout. feels completely like a waste of time and optimizing the startup process in itself is much better.

my overall impression is, that everyone who is using smc, is expecting to have some loading time. e.g. think of gmail, which shows you a small progress bar. so, compared to that, IMHO what does matter is to show a startup banner confirming, that you are actually on the page and you just have to wait ~10 secs to get started. (there was a time when this was just white only)

I would rather focus on writing content, which is then indexed and can be used in general. i.e. self-consistent sub-pages like /learn/*.html or /why/*.html

**Comment by williamstein** [comment]
On Tue, Jun 21, 2016 at 1:20 PM, Harald Schilly <notifications@github.com>
wrote:

> well, I don't really know how to do this, might be a lot of work. from a
> pure technical perspective, the initial page does load extremely fast.
>

I don't totally agree.  You can make it load very quickly using webpack and
require.ensure (?).   I did do precisely this when we first switched to
webpack.  However, I hit subtle issues later with lazy loading of the rest
of the js/etc., which overall led to a bad experience.  I thus
removed/disabled this optimization, since actually working well is always a
higher priority.

You don't see the landing page until about 2.8MB loads.  On a low-bandwidth
connection, that can be 20-30s.  That's not "extremely fast".     We could
make the landing page more like 500k, right?  We just need websockets and
some static html, which could be rendered on the backend (like with
policies).  *That* is something I haven't done yet.

That said, for now I totally agree with everything Harald said and what we
should focus on right now.    Nonetheless, technically there are some cool
options that would make initial load for a new visitor to the site nearly
instant.  I don't know when to focus on that, but I'm definitely not going
to do so right now :-)



> what takes time is to actually get to the app itself after all the
> initializations. that's a constant effort for optimization and
> experimenting around.
>
> more generally, my initial vision was to have www.sagemath.com as the
> overall landing page -- as a simple one-page intro with some info, but I
> spent maybe 2-3 hours on it and it never grew into anything. this page
> would satisfy the pageload + information requirement. now we did agree to
> just redirect to smc, so that's gone ...
>
> besides that, I know how to display content immediately when the page
> shows up. that's this loading banner with the logo and some extras. I'm not
> sure if we should expand this into an incomplete website, that's being
> loaded quicker, and then it somehow adds new stuff to itself after some
> random timeout. feels completely like a waste of time and optimizing the
> startup process in itself is much better.
>
> my overall impression is, that everyone who is using smc, is expecting to
> have some loading time. e.g. think of gmail, which shows you a small
> progress bar. so, compared to that, IMHO what does matter is to show a
> startup banner confirming, that you are actually on the page and you just
> have to wait ~10 secs to get started. (there was a time when this was just
> white only)
>
> I would rather focus on writing content, which is then indexed and can be
> used in general. i.e. self-consistent sub-pages like /learn/*.html or
> /why/*.html
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sagemathinc/smc/issues/639#issuecomment-227559375>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABN5dpekuK3FCezUnCCG-IvU3ghnFTfMks5qOEeIgaJpZM4I7FQs>
> .
>



-- 
William (http://wstein.org)

**Comment by haraldschilly** [comment]
> You don't see the landing page until about 2.8MB loads.  

We mixed up what we mean. With "landing page" I did refer to the initial banner page. That one should show up right after the first response from the server. The real landing page does take longer, I know, and finding a good way to load everything is not so easy.

**Comment by haraldschilly** [comment]
experimented around and found a way which is not at all intrusive and solves this problem. benefits are, that content from the current "embedded" landing page would move to this static one (which means, that there is much less confusion with too much content), we can have more than one such page,  and they are indexed by search engines. drawbacks are one additional query to the db, which doesn't seem to  add any noticeable overhead at all.

**Comment by GregoryBard** [comment]
I am not knowledgable enough to contribute to the discussion of solutions
here. Yet, I agree with Tim that some change in this direction could help
improve the first impressions of new users.
---Greg

**Comment by haraldschilly** [comment]
Cocalc has a different landing page now. IMHO there is no page that does load instantly -- or put differently -- even our previous landing page did load instantly but then continued to load all those additional libraries. 

How instant is instant? What exactly qualifies for instant?

With that last question I'm closing this.

**Comment by williamstein** [comment]
> How instant is instant? What exactly qualifies for instant?

 Loading the new landing page takes 9s over 1.5Mbps:

<img width="1335" alt="screen shot 2017-05-22 at 11 26 06 am" src="https://cloud.githubusercontent.com/assets/1276278/26322823/7e5c26c8-3ee1-11e7-8fe7-5a38fd161205.png">

That seems pretty good to me.  I'm happy with closing this.
