### ISSUE TITLE
make clicking on bulleted/numbered list button when selected remove that formatting in the current line

### ISSUE THREAD

**Issue by Blaec-CoCalc** [sagemathinc/cocalc#6451]
When creating a list in a Markdown document, there is no easy way to deselect the bulleted/numbered list mode while strictly using the rich text editor. This can be frustrating when trying to continue writing standard text after creating a list.

It would be more user-friendly to have the ability to deselect a list once it has been created via the rich text editor. Unfortunately, the button does not toggle the list mode off; that visual indicator would be helpful.

This feature would make working with Markdown documents much more efficient and intuitive, especially for users who frequently use lists and the rich text aspect.

Thank you for considering this suggestion!

**Comment by williamstein** [comment]
>  there is no easy way to deselect the bulleted/numbered list mode while strictly using the rich text editor. 

I think I don't understand this question, since there are several easy ways to do that.

1. Press the down arrow at the end of the list.  You are now out of the list
2. Hit shift+tab at the end of the list and the last item is no longer a list
3. Click the unindent button at the top in the button bar.

I tried google docs, and for them (1) doesn't work -- the cursor is just stuck.  For (3) there is a hidden button but clicking it does nothing.   For (2) in google docs, hitting shift tab just does nothing in a list -- you're stuck.  However, in docs you can hit backspace in the last blank item and that gets you out of the list.  Also, there is a bulleted list button that is selected (though it is hidden on my 13" MBP), and clicking that button does the same as 2 or 3 in my list above.

So things do work differently for rich text editing between google drive and cocalc, but it's a little unfair to say that " there is no easy way to ...", if I understand the question correctly.  I'm personally not impressed that the three most obvious (to me) ways to get out of a list just do nothing in google docs.

**Comment by Blaec-CoCalc** [comment]
<img width="726" alt="Screenshot 2023-02-18 at 11 10 54 AM" src="https://user-images.githubusercontent.com/101306074/219883869-bd1d8dfc-d453-4eda-b4fc-8e5b87ab7a31.png">

This case refers only to 2. and 3.

Ex. If you are actively working on the bottom line of a bulleted list, it would be nice to click the currently selected "bulleted list button" to deselect the list mode, end the list at the bullet above, and return the current line to standard text mode. 

Specifically, I feel like it would be intuitive to have my cursor be on the bullet with "d" written, click the bulleted list button, and that bulleted list line with "d" becomes standard (non-list oriented) text. (Rather than using shift+tab). I mention this because the button is highlighted (which draws attention to it) and naturally makes you wonder what happens if you click it again. As opposed to the unindent (shift+tab) button to the right on the toolbar. I point to Microsoft Word as to why I feel this way.

**Comment by williamstein** [comment]
OK, that make sense.  Thanks for the clarification.  I've updated the title for clarity.
