### ISSUE TITLE
jupyter: code output stays around after switching cell type to text

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6506]
It's possible to get the notebook UI into a weird state, where there is code output (stdout or err) of a cell in markdown/text mode. That output shouldn't be there, or at least removes itself when evaluating the markdown/text cell.

To get into this:

1. Run this code (and immediately do step 2)
    ```py
    from time import sleep
    sleep(5)
    print("hi")
    ```
2. select that cell with the code and switch to text/markdown mode. The code is now a string, that's fine, but once the 5 seconds are over, there is an output "hi".

My first odd observation was that when I "evaluate" the text cell, that "hi" output sticks around. I think it should be removed. … or maybe it should never show up in the first place.

![Screenshot from 2023-03-02 15-42-41](https://user-images.githubusercontent.com/207405/222461557-4cd10f10-2ec8-453e-8059-2040bf8cb1a2.png)

**Comment by williamstein** [comment]
> code output stays around after switching cell type to text

I don't think this describes what actually happens.  It's not that the code output stays around, it's that the newly created output from the running computation is actually displayed, rather than ignored.

I've fixed this.  

Beyond that I'm not sure what the right semantics are if you run both of these cells:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/1276278/223923280-208eb9a5-268d-4351-bbf6-39fb1db02ce6.png">

then change the second cell to markdown.  Should that code still run, or should it get skipped, or should evaluation be interrupted.  In JupyterLab and CoCalc right now, the second cell *does* still run.

```py
from time import sleep
print('x')
sleep(7)
print('y')
---

from time import sleep
import sys
while True:
    print('x')
    sys.stdout.flush()
    sleep(1)
```

It's difficult to implement something different, but certainly possible.  I'm just going to leave things as is, and fix exactly the issue you described here.
