### ISSUE TITLE
no need to check subscription status after completing a voucher order

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#6523]
In the "Congrats" page after a voucher order is completed, under "Here are your next steps", there is a link for "check on the status of subscriptions". I don't think that makes sense, since vouchers are only for non-subscription licenses.

**Comment by williamstein** [comment]
> In the "Congrats" page after a voucher order is completed, under "Here are your next steps", there is a link for "check on the status of subscriptions". I don't think that makes sense, since vouchers are only for non-subscription licenses.

Note that currently the "Congrats" page is stateless, in that it doesn't depend on what you just did.  It just shows information about anything recent.  This is nice since you can refresh the page, visit it from anywhere, and see that info.  It's also the same page for voucher creation and license purchases.  So probably the right way to address your concern would be to only show that subscription link if a subscription was purchases recently?
