### ISSUE TITLE
this forced flyout panel popover doesn't make sense

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#6964]
There's a forced popover that you see until you explicitly click a button:

<img width="273" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/2257f9ba-bf87-4cb8-a5d5-bfd6ffbb665e">

Any brand new user to cocalc will see this.  There's hundreds of UI elements that are completely equivalent in important and relevance that this new user sees.  And yet this one, and only this one, has a forced tip.  That doesn't make sense.

What may make sense would be having it maybe for a while for existing users?  At least then there is some logic -- it's a recent change to highlight.  But showing it to all new users when it's very much not a change to them, but just a completely random choice of something in a UI, where absolutely everything is entirely new to them, makes little sense.

**Comment by novoselt** [comment]
I agree. This is probably not the new user's concern at all. In general my feeling is that CoCalc interface is overwhelming at first, there is too much flexibility exposed right away. If anything is worth highlighting - it is how to remove some parts of the interface to make it easier to orient.

Regarding existing users - it makes a lot of sense to highlight every new addition to the interface, since they probably figured out how things that they need are working and no longer spend time exploring all the buttons and menus.

**Comment by haraldschilly** [comment]
Well, the main fear was users no longer know how to get to the full page. In any case, I get the point that this is annoying. Maybe a less obtrusive variant would be to highlight the button, but not show the popup. The highlight goes away if the button is either used once or the popup is revealed once.

**Comment by williamstein** [comment]
> Maybe a less obtrusive variant would be to highlight the button, but not show the popup. The highlight goes away if the button is either used once or the popup is revealed once.

Imagine you are a brand new users to cocalc.  Why is exactly that one button getting this treatment, but absolutely nothing else anywhere else in the UI?
