### ISSUE TITLE
Current and running balance calculation is wrong for admins looking at users

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#6974]
When an admin is looking at transactions for another user, admin's own balance is used in some calculations that make the result very different from the correct user view.

**Comment by schrodingersket** [comment]
I might be way off base, but will this require a new API endpoint à la the `/purchases/get-purchases` and `purchases/get-purchases-admin` endpoints for an admin to fetch a particular user's account balance, or does that capability already exist in the API?

**Comment by williamstein** [comment]
I think you're very likely right. To add a new api endpoint:

1. Add a file to packages/next/api/v2/purchases similar to the other ones there.
2. Add a call to use it to frontend/purchases/api.ts similar to the other ones there.
3. Think about security -- i.e., do what get-purchases.ts does to check that the caller is an admin.

You shouldn't have to restart any servers or anything after doing the above for it to take effect, since nextjs automatically reloads itself in dev mode when api endpoints change.  You do have to do `pnpm tsc` in the packages/server and also it's good to do `pnpm tsc` in the packages/next directory, so nextjs sees the new javascript code.
