### ISSUE TITLE
Cursor/focus jump when selecting a part of long output

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7071]
This was driving me nuts on a regular basis when trying to copy-paste something from a data frame! I can reproduce it now with a cell
```python
for i in range(100):
    print(i)
```
1. Execute this cell to print out 100 lines, hopefully they do not fit on your screen.
2. With the cursor in the cell below, use your mouse to select one of the bottom numbers in the output above.
3. The result for me - the cursor jumps to the code cell above, scrolling the view to make it visible and cancelling mouse selection.
4. Trying to select the same number again works fine, but if you put the cursor back into the bottom cell, selection attempt leads to the same results. And this is really really annoying ;-)

**Comment by novoselt** [comment]
The same thing happens when I just click on the long output, e.g. to double click and automatically select a word. If the cell of this output is not in focus, it gets focused, but the cursor is placed in the code part and the notebook scrolls to it. Getting focus to the cell is perfectly fine, but the cursor should not appear and no scrolling should happen!

**Comment by williamstein** [comment]
If you're in command mode then everything works exactly as you expect.  It's only in *EDIT* mode that the behavior you describe happens.

In Jupyter classic when you're in edit mode, if you click to select text in the output of a cell, you switch to command mode.  So that's the real issue.  We should change Jupyter in cocalc to switch to command mode when a cell goes out of focus for any reason (except switching focus to another cell).

**Comment by williamstein** [comment]
WORKAROUND: Hit escape to switch to command mode before selecting output.
