### ISSUE TITLE
Cancelling a subscription should NOT depend on available balance!

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7161]
Yet I got this message for this transaction:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/e75bbbb2-57d6-440e-b7e8-63e5c000c961)

**Comment by schrodingersket** [comment]
One (likely related) observation I made while investigating #7141: when a license is cancelled, its new end date is set 10 minutes into the future (see https://github.com/sagemathinc/cocalc/blob/master/src/packages/server/purchases/cancel-subscription.ts#L35) and the remaining subscription amount is refunded from that point up through the natural termination of the subscription. This results in a non-zero charge to the account (i.e., the `$0.01` amount seen above) and the rest is refunded after this change. If the user cannot charge anything to their account (due to, e.g., a negative account balance), that would almost certainly trigger the above error.
