### ISSUE TITLE
Round up per project cost before taking the number into account

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7207]
An example of the current discrepancy:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/7d2bd532-e414-44b0-809f-d82bd847caaf)

**Comment by williamstein** [comment]
If it says $352.52 and $705.03 you're then going to complain that it should say $705.04, right?    So you're not complaining about the display but the actual cost.

**Comment by novoselt** [comment]
Yes, the cost of the single project should be in whole cents, so that there are no surprises in any direction with the total amount. I also want more and more to have licenses with terms in whole days only - no user that I have seen, including myself, can figure out how to use the date-time selector. Those who want a workshop license should deal with the fact that the minimum amount is one day or use upgrades. Just like subscriptions are per month or per year, not per week, per term etc.

**Comment by williamstein** [comment]
Unfortunately, rounding up, then multiplying, then rounding up, etc., will never address the actual issue because these decimal numbers can't in general be represented exactly in binary.   E.g., in floating point arithmetic we have:

```
> 9.05 * 3
27.150000000000002


> 9.05.toString(2)
'1001.000011001100110011001100110011001100110011001101'
```

So no matter how you round "before taking the number into account", there's going to be similar issue since we round up afterward multiplying by the quantity.

I think what you really want is to do all arithmetic involving money in base 10, e.g., like this in Python:
```
>>> from decimal import Decimal
>>> Decimal('9.05')*Decimal(3)
Decimal('27.15')
```

Rewrite all code that involves money to do that will be difficult and error prone, but could happen someday.

CoCalc money computations are in PostgreSQL and Javascript mostly. There is a new proposal to add something like decimal to Javascript here:  https://github.com/tc39/proposal-decimal?tab=readme-ov-file

It mentions a package that implements something like that here: https://www.npmjs.com/package/decimal128

Postgresql already has a nice decimal type:

```sql
smc=# select 3.0::float*9.05::float;
      ?column?      
--------------------
 27.150000000000002
(1 row)

smc=# select 3.0::decimal * 9.05::decimal;
 ?column? 
----------
   27.150
(1 row)
```

See https://github.com/sagemathinc/cocalc/issues/7885
