### ISSUE TITLE
Eliminate member-hosting selector

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7283]
Data strongly point out that it is rarely used, yet I feel it is the hardest concept to communicate to users. Let's clean up user interface and simplify purchasing process by making every license automatically include member hosting.

(I would like the same for network access, actually, and it would simplify banner logic and messages.)

**Comment by williamstein** [comment]
> (I would like the same for network access, actually, and it would simplify banner logic and messages.)

The license configuration page doesn't have anything separate for network access.    We long ago got rid of separate "member hosting" and "network" license configuration:

<img width="591" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/e5372b03-9cc2-447d-a6aa-6022ed7336e1">

and

<img width="583" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/7900c421-88cb-4fd3-8337-3c06c260e6f8">

Also note that we say "All licensed projects, with or without member hosting, have network access, so they can connect to the network to clone Git repositories, download data files and install software.":

<img width="879" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/4c56a73e-28dd-47ca-8807-597be9c9bbe0">



---

The "Usage and Quotas" panel does explicitly separate member hosting and internet access:

<img width="1500" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/13f6dd8d-ceac-4021-81fa-3a918bed2cf3">

This is very important because instructors can (and often do) explicitly disable internet access, even for students with member hosting licenses.  There needs to be a clear way that this limitation is conveyed to such students.  They see a banner about no network access, and also it is in this usage and quotas section.

---

The "Pay as you go" upgrade option does explicitly separate internet and member hosting.   This is a very reasonable place to eliminate the internet access, or to just always make it enabled (and not disable-able) since it doesn't impact the cost at all, and is orthogonal to member hosting.

--- 


In any case, I have an alternative suggestion, which is that we slightly change https://cocalc.com/store/site-license so that instead of this:

<img width="1040" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/30b608d5-f877-4c9e-97b8-aff2e722a03c">


It looks like this:

<img width="1050" alt="image" src="https://github.com/sagemathinc/cocalc/assets/1276278/663880b1-4aed-417e-8046-3ecb53c38abd">

I.e., the Member hosting and idle timeout sections are hidden, unless you click the "Expert configuration" tab.  

This is very logical, since several params are already hidden!  It's inconsistent to hide about half of them, but not the other half.  After all Idle timeout *is* impacted by the chosen preset.  Hide everything that preset changes.

**Comment by novoselt** [comment]
I guess what I want is to replace "member hosting" which I am not even sure how many users really understand, with "licensed" - if you have a license, your project runs in a better place and with network access, unless disabled by instructor. And no hosting/network upgrades - if someone configures any resources and starts paying for them, better hosting and network are included.

I strongly support hiding timeout when presets are in use!

There are also two improvements that can be done to license description:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/1fca9f00-71e5-4e9f-bcc1-26221c9f057a)

Here "member hosting" and "network" are explicitly listed and separated, but I propose to eliminate them both because they should be automatic. More confusing is to see that the license is $8.60, but cost per project is $8.59. Rounding should be done on per-project level and then multiplied by the number of projects. This helps to avoid surprises when the number of project changes.

I also think it would be better to have "Specific dates" be the top default with sensible dates, e.g. one month starting now, with subscriptions below offering discounts. Similar to "Business" first and then "Academic" offering a discount.

**Comment by williamstein** [comment]
Labeling unclear, since there's all kinds of subtlety in doing this...
