### ISSUE TITLE
Opened file view not updated when the file is updated

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7313]
- I have generated and opened a CSV file
- I ran the script again and generated a different file under the same name
- I switched to the tab with the CSV file and is still shows the old version
- Since I know that the file has changed, I could refresh the view, but I actually have no idea how to do it apart from closing the file and opening it again (which does show the new version)

I would expect that when I switch to the tab with a file few it would check if the file has been updated and display a new version if it was.

**Comment by williamstein** [comment]
I'm adding the "Heisenbug" label, since if I just go through the steps to try this everything works fine and the file updates.     You must have hit an issue with the filesystem watcher library.

I rewrote some of this code recently to reduce dependence on some complicated external libraries.  I will consider switching it back to use those libraries, since I bet they have some useful workarounds for subtle edge conditions.
