### ISSUE TITLE
Adjust the message about non-existing kernels for compute servers

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7318]
It is confusing to say that Sage kernel does not exist on CoCalc:
![image](https://github.com/sagemathinc/cocalc/assets/1993227/e08c6cbf-83a9-4508-9ca1-21fcd3c7cb37)

**Comment by williamstein** [comment]
Nice find -- the problem is just that none of these components are even aware of whether or not the notebook is running on a compute server, and that needs to change.     I also need to make refreshing the list of available kernels happen immediately, rather than a confusing several seconds after you switch the notebook to the compute server.
