### ISSUE TITLE
add to the support page a way to require certain placeholders to be filled in before allowing submission

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7647]
We add a live demo request via support, and instantly started getting many requests.  However, of the first 6+ we got, not a single person filled in any of the required information.   So make it impossible to submit the form without filling that in.

One stupidly easily way to do this would be to just put the string [REQUIRED] in each place where we want something, and don't allow submission until the string "[REQUIRED]" doesn't exist in the input.  It's simple but flexible.  The string "[Required]" would also be a query parameter.

**Comment by novoselt** [comment]
It may not be obvious, however, that the user HAS to remove REQUIRED from the text!

Another probably easy way - can the submit button detect if the default text was altered in any way at all? Maybe it can be disabled until a change in the input area is detected? Then there is no need to explain the required action, I think. Obviously, one can just enter a random symbol instead of something meaningful, but it is already more brain activity than just clicking one button.

**Comment by williamstein** [comment]
> It may not be obvious, however, that the user HAS to remove REQUIRED from the text!

It will be obvious if they are able to actually read English, because next to the submit button in READ bold it will say "make sure to fill in the required section above".  If they can't read that, then they shouldn't submit a support ticket.

Your suggestion for any alteration at all is not sufficient, IMHO.

**Comment by williamstein** [comment]
I'm raising this to blocker -- it's striking that we get several distinct live demo requests from different people every hour... and yet not a single one shows any brain activity.  And the same button for asking a question has been in the upper right for months -- the difference is just the text "Live demo".
