### ISSUE TITLE
@ mentions hijack arrow keys (until you press space bar)

### ISSUE THREAD

**Issue by novoselt** [sagemathinc/cocalc#7726]
**Describe the bug**
Arrow keys stop responding when it should not while typing a chat message

**To Reproduce**
1. Go to chat
2. Type **I am writing a message in chat and my arrow keys work. Next I make @me**
3. Observe during the process that indeed arrow keys work initially!
4. When @ is typed, the menu with collaborators appears, up-down arrows control the menu, left-right do not do anything.
5. When "me" is typed, the menu disappears (assuming you have no collaborators that match it), as expected.
6. Left-right arrow keys still do NOT work!
7. Pressing Esc makes them work again. My speculation is that selection menu remains open/active/focused/whatever, but it is empty and invisible because there are no matches. The effect of pressing Esc should happen as soon as there are no matches.

**Expected behavior**
If there is no active menu, arrow keys should move the cursor through the text.

**Comment by williamstein** [comment]
WORKAROUND: Hit the space bar and everything is back to normal.

All that is happening is that there are no displayed matches, but the mentions search is still fully active.  In fact, hit backspace and you'll see the matching results appear again.

A natural solution for this would be to just make it so that hitting the forward or backward arrows is the same as escape and terminates the @mentions search. That is precisely what github @mentions does.   However, we can't do that because there is a submenu, and the left-right arrow keys are used to move into and out of that submenu.   

So I don't even know what the right fix is for this issue.  Marking it unclear.

**Comment by novoselt** [comment]
Is it possible to completely terminate mentions search as soon as there are no matches? The downside may be that someone trying to delete a portion of the typed name may have to delete @ and then start fresh, but I think this would be much less annoying/confusing.

**Comment by williamstein** [comment]
> Is it possible to completely terminate mentions search as soon as there are no matches? 

Yes.  But it's not at all clear that this is a good idea.  For example, that's definitely not what GitHub's @mentions (right here) does.  If there are no results and I hit backspace, I'm back to seeing results.  

>  but I think this would be much less annoying/confusing.

Some people will have the opposite opinion...

**Comment by williamstein** [comment]
The closest to github would just be to make the left/right arrow keys *always* close the mentions popup (like escape).  That's very easy to implement.  It breaks using the keyboard to select from the submenu of less popular AI models, but maybe that is fine, since that's now a common thing, and you can still use the mouse.

**Comment by novoselt** [comment]
It seems to me that the same thing happens with # hashtags. The workaround with the space bar does NOT work for me (Chrome on Kubuntu 24.04), and if it did, it really would not be an issue since it is pressed a lot while typing. What happens for me is that I type a line, then want to correct something, long after any popups appeared on my screen, and then discover that arrow keys mysteriously do not work. Hitting Esc does help and now that I know it, it is easy to deal with. But it took me a while to understand what is going on and I imagine many users may be stumbling on it.

The required logic seems very clear to me - if there is no search box shown, no keys should be intercepted to go to it, even if "it is active behind the scene". Technical implementation may be tricky, of course.

**Comment by novoselt** [comment]
I've just typed a sentence in a chat that happened to include @ with no matches, hit Enter, and my sentence got replaced with an @match that of course didn't work anymore.

**Comment by novoselt** [comment]
As another approach - apparently zendesk has @ mentions as well and where there are no matches, there is an empty box showing no matches, which I find annoying, but at least it is clear that I need to hit Esc or do something to get rid of it:
![image](https://github.com/user-attachments/assets/3d5ecad0-ed11-477b-8f15-ee569c3e2d5f)

**Comment by novoselt** [comment]
On a related note: if my mouse cursor happens to hang over the popover when it appears, it may select a different collaborator than the one I am typing and when I narrow the search the intended person is not highlighted. Using arrow keys to somehow get the focus is possible, but is very weird - I don't understand what exactly is going on, but probably somehow arrow keys can navigate over "hidden parts".
