### ISSUE TITLE
closing lean causes stacktrace -- so deprecate (?)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7792]
I opened a `lean.lean` file, typed in "1" after lean loaded. There was an error, so, it did something … 

… however, upon closing the editor tab, this happens:

```
Actions.ts:44 Uncaught (in promise) Error: unable to destroy actions because this.name is not defined
    at Actions.destroy (Actions.ts:44:1)
    at AppRedux.removeActions (AppRedux.ts:195:1)
    at Object.remove (register.ts:116:1)
    at Module.eval (file-editors.ts:288:1)
    at step (file-editors.ts:4:1)
    at Object.eval [as next] (file-editors.ts:4:1)
    at asyncGeneratorStep (file-editors.ts:4:1)
    at _next (file-editors.ts:4:1)
```

and afterwards, when trying to open the editor again:

```
Error: store editor-20e4a191-73ea-4921-80e9-0a5d792fc511-lean.lean already exists
```

I've not touched lean in quite a while, so, no idea if this is old or new. My first hunch is calling `close(this);` in its `Actions::close()` method is causing this.

**WORKAROUND**: reload the cocalc page, then the editor+store is created fresh.

**Comment by williamstein** [comment]
I spent a solid 1+ months of my life writing this, but the reality is that lean3 is very out of date, and it's much better to use lean via VS Code in a compute server.   We have no paying customers in a while using lean via cocalc.  Only four .lean files were opened in the last month.   

https://doc.cocalc.com/ contains absolutely zero help about how to use Lean in cocalc, and there's a lot of caveats.

We should just deprecate lean rather than fixing this, even if it is easy to fix.  It would mean less to maintain.   

The supported way to use lean should be either via [a compute server and vscode](https://github.com/sagemathinc/cocalc-howto/blob/main/lean.md), or just via vscode in a project.

**Comment by williamstein** [comment]
We could deprecate it by just removing it being registered and leave in the code for a year, just in case.

**Comment by williamstein** [comment]
Deprecated
