### ISSUE TITLE
A "Collect and delete" button to assignment page

### ISSUE THREAD

**Issue by math-sl** [sagemathinc/cocalc#7882]
When we use "assignments" for exams, in certain situations we don't want the exam material to be available as soon as a student finish the examen and leave the room. 

We can manually delete material in student's assignment folders, but this is quite cumbersome: collect, open student project, delete files. This is also prone to errors, like accidentally deleting the exam copy before collecting it. 

A "Collect and delete" button added beside the current collect button would solve this. Maybe with some form of quick confirmation.

Related issue: #7110

**Comment by williamstein** [comment]
Thanks for spelling this out clearly.

Unfortunately, nothing along these lines will work because of TimeTravel and filesystem snapshots, which are not immediately user-deletable. There is no way to reliably ensure students can't view the exam except to remove the student from the project.  If you remove the student, there is no need to worry about collecting or deleting, since the student can no longer access the exam.    What's more important is having a new exam-specific project.  

Note that it is really not possible to use assignments for exams if you must ensure the student doesn't have access to the exam.  The exam MUST be in another project.

**Comment by math-sl** [comment]
Ok, I naively thought that doing a rm directly bypassed the backup system, the internal of which I know nothing about. 

I can modify the idea taking your comment into account: I guess it would be possible to automate a specific exam project creation and deletion from the course. This new project would need to have the same settings as the course student's projects. 

I will make this a new issue.
