### ISSUE TITLE
jupyter ESC key to exit edit mode not working

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7889]
**Describe the bug**

Editing a cell, then pressing the ESC key, keeps me in edit mode

**To Reproduce**
See above, it fails reliably.

**Expected behavior**
to be in command mode

**Additional context**
* Linux Ubuntu 22.04
* Chrome 130.0.6723.19 (beta)
* German keyboard

What helps, kind of, is to click on the area outside of another cell (not the codemirror interior) – or to evaluate the cell. In both cases I'm back in that command mode. 

It's also not specific to a certain notebook.

**Comment by williamstein** [comment]
I cannot reproduce this on MacOS Chrome Version 129.0.6668.71 (Official Build) (arm64) with a US keyboard.  There are no other reports of this. 

1. Is it specific to a German keyboard?  
2. Is it NEW?  

The only relevant new changes I can think of are to antd, but even then I don't see how it would cause this, because I think it's handled by Codemirror, which is very stable.

**Comment by haraldschilly** [comment]
Well, I don't know how new it is, I noticed it today with some testing. A few weeks ago it certainly worked fine. Could be the browser, sure. I just wanted to open it as a note to keep an eye on it.

**Comment by williamstein** [comment]
> Well, I don't know how new it is, I noticed it today with some testing. 

Can you:

1.  Do a test using cocalc's frontend from 2 months ago?   
2. Test using the stable version of Chrome (NOT beta) with a German keyboard?

It would be good to know if this is just an upstream bug that will come and go, or something for us to worry about.

**Comment by williamstein** [comment]
Conclusion: this is caused by a browser extension.
