### ISSUE TITLE
chatroom preview when editing past messages

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#795]
There's now preview when typing a new message, but what about when editing a past message?

**Comment by simonluu** [comment]
I started working on this yesterday and now I'm thinking about the complaints everyone had with the previews.

So I'm thinking of doing something similar to the chat preview where by default it is off and there is a button in the message that toggles it on and an X inside the preview that turns it off.

The edit preview isn't as annoying as the chat previews because I'm making it show up right under (or right above not sure which will be better) and it doesn't scroll with the page like the chat preview because there is no need for it to scroll with it.
