### ISSUE TITLE
Instructor configures different path to assignment

### ISSUE THREAD

**Issue by rbeezer** [sagemathinc/cocalc#85]
It would be nice for the path to a student's copy of an assignment to be different than the instructors:  eg

instructor: `courses/2015-fall/math290A/assignments/one/one.sagews`

student: `math290/one/one.sagews`

So maybe have a per-assignment setting where the instructor would fill a field with `math290/one`.  This would need to be accounted for in colllection and returning, etc.

**Comment by novoselt** [comment]
This probably fits well the situation when an instructor has a single project for multiple courses, including multiple terms. I suspect, however, that a much more common scenario is to have a separate project for each course/section and the reason is that different sections are likely to have different TAs, which are added as collaborators and should not have access to students in other sections. So nothing wrong with having such a feature, but usually it is not needed.

**Comment by williamstein** [comment]
I agree with @novoselt here that this is a workaround for something that we should strongly discourage. Implementing this will mean added complexity, which may lead to confusion and bugs.

It's utterly clear that with the collaborator model for projects, that we *should* make strongly encourage (but not force) having only one course per cocalc project.   I'm closing this current issue as "wontfix" for now.  If there is a compelling case for it, then it can be reopened.
