### ISSUE TITLE
Have a special url for projects, so that when people click that URL they get auto added

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#885]
Example related situations cases:
- Have a course webpage only students can access. Put a link to the course.
- In slack put a link for your team to sign up

**Comment by williamstein** [comment]
Closely related to #886

**Comment by williamstein** [comment]
I think this is still pretty vague -- what about security implications?  What is the URL like?  Long/short?  How do you create it and how do you disable it.  Also labeled hard since it involves security, frontend, and backend coding.

**Comment by williamstein** [comment]
Interestingly, this also solves a different problem that became popular with everything going remote, which Michael Forbes asked me about.

Current hack "solution":

1. Create a new cocalc account specifically for seminar chat.
2. Get an API key for that account (in account prefs).
3. Use the API key and the terminal to generate an auth_token before the seminar as explained here: https://doc.cocalc.com/api/user_auth.html
4. Share the URL like `https://cocalc.com/app?auth_token=BQokikJOvBiI2HlWgH4olfQ2` with all participants.  You could make it be the URL directly to the chatroom (or markdown file). 
5. When they click the link they get signed into cocalc as *that user you created*, then see the chatroom.

---

Of course, it would be nice to add a new feature to cocalc where there's a link that lets anybody with the link automatically become a collaborator on a project.  Basically a sort of "auth_token" but for a project.  It could be made to work for either signed in users are "anonymous" users that haven't entered any info about themselves at all...  I'll make an issue for this.

**Comment by mforbes** [comment]
The security question here is somewhat important: The use case I was envisioning would work best if these add-by-click users could be quarantined appropriately to either specified files or folders within a project (which I suspect is not how the system is designed).  Giving them edit access to only public files might also be fine too.

Of course, this can be mitigated by creating a special project just for the discussion, so it is not a show stopper. It just makes a bit more work for the organizers.

For this use-case to be successful, the interface presented to these add-by-click users must be very clean and easy to use so that people unfamiliar with CoCalc (or technophobes in general) are not dissuaded from participating.

**Comment by williamstein** [comment]
> quarantined appropriately to either specified files or folders within a project

That is absolutely not possible and won't be, since there are many many subtle security issues with changing to such a security model.   You have to use a specific project just for this purpose.  However, note we are about to role out a new license scheme that makes it so you can "upgrade" many projects and the limit is only on how many are **running simultaneously**.

> For this use-case to be successful, the interface presented to these add-by-click users must be very clean and easy to use so that people unfamiliar with CoCalc (or technophobes in general) are not dissuaded from participating.

The UI would just be that they click a link then are using a specific file in a project.  They don't have to do anything (if they have an account already, they get added to the project using that account; if they have no account, they get a temporary anonymous account, which they can optionally convert to be permanent -- this would all happen automatically). 

> Expiring access is also probably somewhat important.

I think that would be a discussion for another ticket later after the feature on this ticket is done.  There are issues with removing users from projects, e.g., what if they contribute a lot of content and are frustrated that it's suddenly "gone" from their point of view?   Maybe just a way to remove *all* other users (besides yourself) easily from a project would suffice for this problem.

**Comment by williamstein** [comment]
Implementing something in https://github.com/sagemathinc/cocalc/pull/4744

**Comment by williamstein** [comment]
This is now implemented.   Here is what it looks like in project settings:

![image](https://user-images.githubusercontent.com/1276278/87637354-ec7b9d00-c6f6-11ea-995e-38abed8e7ab8.png)

Just toggle the "Or invite people via a project invite token..." link, then make a new code, then click + to see the link.   If somebody visits that URL and they have no account they get an ephemeral anonymous account and access to the project.  Their name is 'Anonymous User-[number]".  If they are instead already signed in to a cocalc account, then they just get added to the project and the project is opened for them.

Somebody already signed in can also enter the code directly in the upper right of project settings:

![image](https://user-images.githubusercontent.com/1276278/87637441-0fa64c80-c6f7-11ea-87fa-e5fd182b87ab.png)

The link currently expires after 2 weeks, or when you click the "Expire" button (which expires it immediately).  There is no limit on how many times it can be used, and anonymous users are NOT automatically removed from the project.  Also, there is no limit on what they can see in the project.   If you want to add people this way and post the link (quasi-) publicly, only do so in a project without private information!

**Comment by williamstein** [comment]
There are some natural things to do to make this more useful, which will be later and in a follow-up ticket or tickets:

- configure the number of times the invite can be used (this is supported by the backend but the UI isn't implemented in the frontend... so it would be easy).
- make it easy to change the expire date (same as above -- just easy ui work).
- make it so only the project owner can use the "Or invite people via a project invite token..." functionality.  E.g., right now any random user could anonymously just expire the token or make new tokens.  But before doing this, maybe we need a way to have more than one project owner (?). Alternatively, maybe just better logging or only allow non-anonymous users to edit this.
-

**Comment by williamstein** [comment]
For now though, these solve the following problem: 

> "Ever give a talk and wanted everybody in the audience to easily add themselves as realtime collaborators on #jupyter notebooks or markdown files in https://cocalc.com?  "

**Comment by mforbes** [comment]
The only thing missing are instructions or some way of automatically including the `?project-invite=...` at the end of the URL.  It is not at all obvious how to do this.  (Perhaps this is a browser issue?  I do not see the `Make this link available to people you would like to join the project...` information at all in Chrome. 

![Screen Shot 2020-07-17 at 10 09 00 AM](https://user-images.githubusercontent.com/1028433/87812763-8afe2000-c815-11ea-9653-159e9e40e1f7.png)

**Comment by haraldschilly** [comment]
@mforbes that's the "[+]" button on the left, which shows additional information for table rows. 

I'm thinking, maybe the copy button of the token should just copy that URL? Or maybe another little button with a :chains: icon to symbol a link, while not taking up too much space...

**Comment by mforbes** [comment]
Another confusion is the message about all your work being deleted when you log out as an anonymous user.  I assume this means any projects started by that anonymous user will be deleted and not edits to someone else project... but this is confusing - especially for users who want to sign in with their account.

Is there some way to merge the anonymous user into an existing account?  That would solve some issues.  (Currently, one should recommend people login to CoCalc first before using the token.)

**Comment by mforbes** [comment]
> @mforbes that's the "[+]" button on the left, which shows additional information for table rows.

So it is!  I would have never thought of that.  I thought that was for adding additional tokens.

**Comment by williamstein** [comment]
> Is there some way to merge the anonymous user into an existing account? 

No, there isn't.
