### ISSUE TITLE
Make a generic invite code system

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/cocalc#886]
Similar to #572. In project settings one can set a code. When people go to project they would see request to join or enter invite code. Request to join is ticket #872

**Comment by williamstein** [comment]
WORKAROUND: We do NOT require verification of email addresses, so one can work around this missing feature right now as follows.

Assign fake email addresses to all students in your class, e.g.,
```
student+<student_id>@your-class.edu
```
and then tell the students to sign up for cocalc using that "fake" email address (I assume you can communicate with your students in some way -- perhaps in class).

Once they sign up, they will be added as collaborators to their project for the course. At that point, they can change their email address to anything they want, in order to ensure they get @mention notifications, can do password reset, etc.

If student_id's need to be secret/sensitive, you could use something derived from them, e.g., the last two digits.

**Comment by matthew-brett** [comment]
Just to check I understand - the idea here is to somehow transmit a code to a student, maybe via email, so that, when the they somehow use or apply this code, it makes them a collaborator on a particular course.  The benefit is that there is a semi-automatic way that the student can be added to a course without the student having to have made an account on CoCalc already, and without the instructor knowing the student's email address.

This would work maybe by having something in Account tab, like "Subscription codes", where the student enters one or more codes, and CoCalc would automatically add the account to matching projects.

I guess knowing the code will get you subscribed, at least for some time-window, so if the student somehow gives away the code, the person who has it, could also get added to the course.

**Comment by williamstein** [comment]
> I guess knowing the code will get you subscribed, at least for some time-window, so if the student somehow gives away the code, the person who has it, could also get added to the course.

That's a good point.  We might want to make it a single-use code.    That of course complicates distribution of the code itself though.   In practice, people rarely try hard to sneakily get added to courses, since they are already so busy.

**Comment by matthew-brett** [comment]
The worrying use-case for sneaky adding would be to cheat on group homework.  For example, my students could benefit from reading the other students' projects to get ideas for code and analysis.

**Comment by haraldschilly** [comment]
I'm closing this. It's possible to join a project via an invite token already. The aspect about courses (join a course via  code) is more or less #572
